from v2.models.knowledge_models import Topic

QUESTIONS_CLIENTS_TOPICS: list[Topic] = []

Topic(
    id="assurance_vie_questions_retirer_argent",
    title="Puis-je retirer mon argent quand je veux ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="questions_clients",
    description="Comprendre les conditions dans lesquelles un souscripteur peut retirer tout ou partie de l'épargne investie sur son assurance-vie.",
    objective="Expliquer que l'assurance-vie est un placement disponible : le souscripteur peut effectuer un rachat total ou partiel à tout moment, même si ce retrait peut avoir des conséquences fiscales selon la situation.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "retrait",
        "rachat",
        "rachat partiel",
        "rachat total",
        "liquidité",
        "assurance-vie",
        "épargne",
        "disponibilité",
    ],
    key_points=[
        "L'épargne placée sur une assurance-vie reste disponible à tout moment.",
        "Le souscripteur peut effectuer un rachat partiel ou un rachat total.",
        "Un rachat partiel permet généralement de conserver l'ancienneté fiscale du contrat.",
        "Le retrait peut avoir des conséquences fiscales selon l'ancienneté du contrat et les gains concernés.",
        "L'assurance-vie est un placement de long terme, mais elle n'est pas un placement bloqué.",
    ],
    examples=[
        "Julie, 36 ans, doit financer des travaux imprévus dans sa résidence principale. Plutôt que de souscrire un crédit, elle effectue un rachat partiel sur son assurance-vie tout en conservant le reste de son épargne investie.",

        "Marc, 59 ans, souhaite compléter ses revenus avant son départ à la retraite. Il met en place des rachats partiels programmés afin de percevoir un complément régulier sans clôturer son contrat.",

        "Claire, 42 ans, hésite à ouvrir une assurance-vie car elle pense que son argent sera bloqué pendant plusieurs années. Après s'être renseignée, elle comprend qu'elle peut récupérer son capital à tout moment si nécessaire.",
    ],
    vocabulary=[
        "rachat",
        "rachat partiel",
        "rachat total",
        "liquidité",
        "capital",
        "plus-value",
        "ancienneté fiscale",
        "disponibilité",
    ],
    legal_sources=[
        "Code des assurances",
        "Code général des impôts",
        "BOFiP - Assurance-vie",
    ],
    analogies=[
        "L'assurance-vie fonctionne comme un compte d'épargne évolué : votre argent reste disponible, mais plus vous laissez le contrat vivre longtemps, plus vous pouvez bénéficier de certains avantages fiscaux.",
    ],
    misconceptions=[
        "Mon argent est bloqué pendant huit ans.",
        "Je ne peux récupérer mon capital qu'à la retraite.",
        "Un retrait entraîne automatiquement la fermeture du contrat.",
        "Retirer de l'argent signifie perdre tous les avantages de l'assurance-vie.",
    ],
    common_mistakes=[
        "Clôturer entièrement son contrat alors qu'un simple rachat partiel aurait suffi.",
        "Reporter un projet par peur de ne pas pouvoir récupérer son épargne.",
        "Confondre disponibilité des fonds et fiscalité des retraits.",
        "Croire qu'un retrait fait repartir l'ancienneté fiscale à zéro.",
    ],
    expert_tips=[
        "L'assurance-vie doit être considérée comme une épargne de long terme, mais cela ne signifie pas qu'elle est indisponible. En pratique, un rachat partiel est souvent une solution plus pertinente qu'une clôture complète du contrat.",
    ],
    attention_points=[
        "Le délai de versement des fonds dépend de l'assureur.",
        "Chaque retrait peut avoir des conséquences fiscales qu'il convient d'anticiper.",
        "La stratégie de retrait doit être cohérente avec les objectifs patrimoniaux du souscripteur.",
    ],
    client_questions=[
        "Puis-je récupérer mon argent quand je veux ?",
        "Combien de temps faut-il pour recevoir les fonds ?",
        "Mon contrat est-il fermé après un retrait ?",
        "Puis-je effectuer plusieurs retraits ?",
    ],
    client_objections=[
        "Je ne veux pas bloquer mon épargne.",
        "J'ai peur de ne plus pouvoir récupérer mon argent.",
        "Je préfère un livret parce que je peux retirer mon argent facilement.",
    ],
    client_fears=[
        "Ne pas pouvoir financer un imprévu.",
        "Perdre les avantages de mon contrat.",
        "Payer trop d'impôts lors d'un retrait.",
    ],
    client_goals=[
        "Disposer d'une épargne disponible.",
        "Financer un projet.",
        "Préserver les avantages de son assurance-vie.",
        "Conserver de la flexibilité.",
    ],
    client_intents=[
        "retirer de l'argent",
        "faire un rachat",
        "récupérer son capital",
        "comprendre les retraits",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_plus_value",
        "assurance_vie_fiscalite_8_ans",
        "assurance_vie_questions_bloquee_8_ans",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_fiscalite_rachat",
    ],
    next_topics=[
        "assurance_vie_questions_bloquee_8_ans",
    ],
),

Topic(
    id="assurance_vie_questions_bloquee_8_ans",
    title="Mon assurance-vie est-elle bloquée pendant 8 ans ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="questions_clients",
    description="Comprendre pourquoi l'assurance-vie n'est pas un placement bloqué et ce que représente réellement le délai de huit ans.",
    objective="Expliquer que le seuil des huit ans correspond à un jalon fiscal et non à une période d'indisponibilité des fonds.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "8 ans",
        "placement bloqué",
        "assurance-vie",
        "rachat",
        "retrait",
        "ancienneté fiscale",
        "liquidité",
        "épargne",
    ],
    key_points=[
        "L'assurance-vie n'est pas un placement bloqué.",
        "Le souscripteur peut effectuer un rachat total ou partiel à tout moment.",
        "Les huit ans correspondent à une étape fiscale et non à une durée de blocage.",
        "Retirer son argent avant huit ans est parfaitement possible.",
        "La décision de retirer son épargne doit être guidée par les objectifs patrimoniaux et non uniquement par le seuil des huit ans.",
    ],
    examples=[
        "Julie, 34 ans, ouvre une assurance-vie pour préparer sa retraite. Trois ans plus tard, elle doit financer un apport immobilier. Elle réalise un rachat partiel sans attendre huit ans, car son projet le justifie.",

        "Marc, 47 ans, renonce pendant plusieurs années à ouvrir une assurance-vie parce qu'il pense que son argent sera immobilisé. Il découvre finalement que cette croyance est erronée et qu'il aurait pu investir plus tôt.",

        "Sophie, 62 ans, possède un contrat ouvert depuis six ans. À la suite d'un imprévu familial, elle effectue un retrait sans difficulté tout en comprenant que les conséquences sont essentiellement fiscales et non liées à un quelconque blocage.",
    ],
    vocabulary=[
        "ancienneté fiscale",
        "rachat",
        "rachat partiel",
        "rachat total",
        "liquidité",
        "disponibilité",
        "fiscalité",
        "épargne",
    ],
    legal_sources=[
        "Code des assurances",
        "Code général des impôts",
        "BOFiP - Assurance-vie",
    ],
    analogies=[
        "Les huit ans ressemblent davantage à une carte de fidélité qu'à un cadenas : vous pouvez partir quand vous le souhaitez, mais rester plus longtemps peut vous permettre de bénéficier de certains avantages.",
    ],
    misconceptions=[
        "L'assurance-vie est bloquée pendant huit ans.",
        "Il est interdit de retirer son argent avant huit ans.",
        "Un retrait avant huit ans entraîne une pénalité.",
        "Les huit ans correspondent à la durée minimale du contrat.",
    ],
    common_mistakes=[
        "Attendre huit ans avant d'investir alors que l'on dispose déjà d'une capacité d'épargne.",
        "Reporter un projet par peur de ne pas pouvoir récupérer son argent.",
        "Confondre disponibilité des fonds et fiscalité des rachats.",
        "Croire qu'un retrait avant huit ans est forcément une mauvaise décision.",
    ],
    expert_tips=[
        "Le véritable intérêt d'une assurance-vie est de commencer le plus tôt possible à faire courir son ancienneté fiscale. Attendre huit ans pour ouvrir un contrat est souvent plus pénalisant que d'effectuer un retrait avant ce délai si un projet le justifie.",
    ],
    attention_points=[
        "Les retraits restent possibles à tout moment.",
        "Le traitement fiscal dépend notamment de l'ancienneté du contrat.",
        "Chaque rachat mérite une réflexion patrimoniale globale plutôt qu'une décision fondée sur une idée reçue.",
    ],
    client_questions=[
        "Mon argent est-il bloqué ?",
        "Puis-je retirer mon épargne avant huit ans ?",
        "Existe-t-il une pénalité si je retire avant huit ans ?",
        "Pourquoi parle-t-on toujours des huit ans ?",
    ],
    client_objections=[
        "Je préfère un placement totalement liquide.",
        "Je ne veux pas immobiliser mon argent.",
        "On m'a toujours dit qu'il fallait attendre huit ans.",
    ],
    client_fears=[
        "Ne plus pouvoir récupérer mon épargne.",
        "Faire une erreur fiscale.",
        "Bloquer mon argent pendant plusieurs années.",
    ],
    client_goals=[
        "Comprendre le fonctionnement de l'assurance-vie.",
        "Conserver une épargne disponible.",
        "Préparer des projets tout en optimisant sa fiscalité.",
    ],
    client_intents=[
        "assurance-vie bloquée",
        "retirer avant huit ans",
        "fonctionnement des huit ans",
        "récupérer son argent",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_questions_retirer_argent",
        "assurance_vie_fiscalite_8_ans",
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_abattement",
    ],
    prerequisites=[
        "assurance_vie_questions_retirer_argent",
        "assurance_vie_fiscalite_8_ans",
    ],
    next_topics=[
        "assurance_vie_questions_combien_rapporte",
    ],
),

Topic(
    id="assurance_vie_questions_combien_rapporte",
    title="Combien rapporte réellement une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="questions_clients",
    description="Comprendre pourquoi il est impossible d'annoncer un rendement unique pour une assurance-vie et quels sont les facteurs qui influencent sa performance.",
    objective="Expliquer que l'assurance-vie est une enveloppe d'investissement dont le rendement dépend des supports sélectionnés, du mode de gestion et de l'horizon de placement.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "rendement",
        "performance",
        "assurance-vie",
        "fonds euros",
        "unités de compte",
        "gestion",
        "placement",
        "investissement",
    ],
    key_points=[
        "Une assurance-vie n'a pas de rendement unique.",
        "La performance dépend principalement des supports d'investissement choisis.",
        "Les fonds euros et les unités de compte présentent des profils de rendement et de risque différents.",
        "Les performances passées ne préjugent pas des performances futures.",
        "Le rendement doit toujours être analysé en tenant compte du niveau de risque accepté.",
    ],
    examples=[
        "Julie, 32 ans, compare deux assurances-vie et constate que leurs rendements sont différents. Elle découvre que cette différence provient principalement des supports d'investissement sélectionnés et non du contrat lui-même.",

        "Marc, 58 ans, recherche avant tout la sécurité de son capital. Il privilégie une allocation majoritairement investie en fonds euros, avec un potentiel de rendement généralement plus limité mais un niveau de risque différent des unités de compte.",

        "Claire, 40 ans, investit sur un horizon de vingt-cinq ans. Elle accepte davantage de volatilité en contrepartie d'un potentiel de performance supérieur grâce à une part importante d'unités de compte.",
    ],
    vocabulary=[
        "rendement",
        "performance",
        "fonds euros",
        "unités de compte",
        "allocation",
        "volatilité",
        "gestion pilotée",
        "gestion libre",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
    ],
    analogies=[
        "Demander combien rapporte une assurance-vie revient à demander combien rapporte un panier de courses : tout dépend de ce que vous mettez à l'intérieur.",
    ],
    misconceptions=[
        "Toutes les assurances-vie rapportent la même chose.",
        "Le rendement dépend uniquement de l'assureur.",
        "Une assurance-vie garantit toujours une forte performance.",
        "Le meilleur rendement est toujours le meilleur choix.",
    ],
    common_mistakes=[
        "Choisir un contrat uniquement sur la base du rendement affiché l'année précédente.",
        "Comparer deux assurances-vie sans analyser les supports proposés.",
        "Confondre performance et niveau de risque.",
        "Construire une stratégie uniquement à partir des performances passées.",
    ],
    expert_tips=[
        "La bonne question n'est généralement pas 'Combien rapporte une assurance-vie ?', mais 'Quelle allocation est adaptée à mes objectifs et à mon horizon de placement ?'. Une performance n'a de sens que si elle est cohérente avec le risque accepté.",
    ],
    attention_points=[
        "Les performances passées ne garantissent jamais les performances futures.",
        "Le rendement dépend des choix d'investissement effectués.",
        "Une allocation adaptée est souvent plus importante que la recherche du meilleur rendement à court terme.",
    ],
    client_questions=[
        "Quel rendement puis-je espérer ?",
        "Quelle est la meilleure assurance-vie ?",
        "Les fonds euros rapportent-ils encore ?",
        "Comment améliorer la performance de mon contrat ?",
    ],
    client_objections=[
        "Le rendement me semble insuffisant.",
        "J'ai entendu dire que les assurances-vie ne rapportaient plus rien.",
        "Je cherche le contrat qui rapporte le plus.",
    ],
    client_fears=[
        "Obtenir un rendement inférieur à l'inflation.",
        "Prendre trop de risques pour rechercher de la performance.",
        "Choisir un contrat peu performant.",
    ],
    client_goals=[
        "Faire fructifier son patrimoine.",
        "Trouver un équilibre entre rendement et risque.",
        "Investir sur le long terme.",
        "Construire une allocation adaptée.",
    ],
    client_intents=[
        "combien rapporte une assurance-vie",
        "meilleur rendement assurance-vie",
        "performance assurance-vie",
        "choisir une assurance-vie",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_supports_fonds_euros",
        "assurance_vie_supports_unites_compte",
        "assurance_vie_supports_allocation",
        "assurance_vie_gestion_profil_investisseur",
    ],
    prerequisites=[
        "assurance_vie_supports_fonds_euros",
        "assurance_vie_supports_unites_compte",
    ],
    next_topics=[
        "assurance_vie_questions_plusieurs_contrats",
    ],
),

Topic(
    id="assurance_vie_questions_plusieurs_contrats",
    title="Peut-on avoir plusieurs assurances-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="questions_clients",
    description="Comprendre qu'il est possible de détenir plusieurs contrats d'assurance-vie et dans quelles situations cette stratégie peut présenter un intérêt patrimonial.",
    objective="Expliquer qu'aucune règle n'interdit de posséder plusieurs assurances-vie et que cette diversification peut répondre à différents objectifs patrimoniaux.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "plusieurs assurances-vie",
        "multi-contrats",
        "diversification",
        "assurance-vie",
        "épargne",
        "patrimoine",
        "allocation",
        "gestion",
    ],
    key_points=[
        "Il est possible de détenir plusieurs contrats d'assurance-vie.",
        "Chaque contrat peut répondre à un objectif patrimonial différent.",
        "Diversifier les contrats peut permettre de bénéficier de modes de gestion, de supports ou d'assureurs différents.",
        "Détenir plusieurs contrats ne remet pas en cause les règles fiscales applicables.",
        "Le nombre de contrats importe souvent moins que leur cohérence avec les objectifs patrimoniaux.",
    ],
    examples=[
        "Julie, 35 ans, possède un premier contrat destiné à financer les études de ses enfants et un second orienté vers la préparation de sa retraite. Chaque contrat répond à un objectif différent.",

        "Marc, 61 ans, conserve un ancien contrat bénéficiant d'une importante ancienneté fiscale tout en ouvrant un nouveau contrat offrant des supports d'investissement plus diversifiés.",

        "Claire, 48 ans, répartit son épargne entre plusieurs assureurs afin de diversifier ses partenaires et d'accéder à des modes de gestion complémentaires.",
    ],
    vocabulary=[
        "contrat",
        "diversification",
        "allocation",
        "assureur",
        "ancienneté fiscale",
        "gestion libre",
        "gestion pilotée",
        "supports d'investissement",
    ],
    legal_sources=[
        "Code des assurances",
        "Code général des impôts",
    ],
    analogies=[
        "Posséder plusieurs assurances-vie revient à disposer de plusieurs boîtes à outils : chacune peut être dédiée à un objectif différent plutôt que de vouloir tout faire avec un seul contrat.",
    ],
    misconceptions=[
        "On ne peut avoir qu'une seule assurance-vie.",
        "Détenir plusieurs contrats est fiscalement pénalisant.",
        "Il faut fermer son ancien contrat avant d'en ouvrir un nouveau.",
        "Tous les contrats se valent.",
    ],
    common_mistakes=[
        "Clôturer un ancien contrat uniquement pour en ouvrir un nouveau.",
        "Multiplier les contrats sans objectif patrimonial clair.",
        "Oublier de conserver l'ancienneté fiscale d'un contrat performant.",
        "Choisir plusieurs contrats identiques sans réelle diversification.",
    ],
    expert_tips=[
        "La question n'est généralement pas 'Combien de contrats faut-il ?', mais 'Chaque contrat répond-il à un objectif précis ?'. Un contrat pour préparer la retraite, un autre pour transmettre un capital ou investir différemment peut avoir tout son sens dans une stratégie patrimoniale globale.",
    ],
    attention_points=[
        "Chaque contrat doit avoir une finalité clairement identifiée.",
        "La multiplication des contrats ne remplace pas une bonne stratégie patrimoniale.",
        "Avant de clôturer un ancien contrat, il convient d'évaluer la valeur de son ancienneté fiscale.",
    ],
    client_questions=[
        "Puis-je ouvrir une deuxième assurance-vie ?",
        "Existe-t-il un nombre maximum de contrats ?",
        "Dois-je conserver mon ancien contrat ?",
        "Pourquoi détenir plusieurs assurances-vie ?",
    ],
    client_objections=[
        "Je pensais que la loi limitait le nombre de contrats.",
        "Plusieurs contrats me semblent compliqués à gérer.",
        "Je préfère tout regrouper sur un seul contrat.",
    ],
    client_fears=[
        "Faire une erreur fiscale.",
        "Perdre l'ancienneté de mon premier contrat.",
        "Complexifier inutilement mon patrimoine.",
    ],
    client_goals=[
        "Diversifier son patrimoine.",
        "Conserver son ancienneté fiscale.",
        "Adapter chaque contrat à un objectif précis.",
        "Optimiser la gestion de son épargne.",
    ],
    client_intents=[
        "ouvrir une deuxième assurance-vie",
        "plusieurs contrats assurance-vie",
        "conserver un ancien contrat",
        "diversifier son épargne",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_ouverture_pourquoi_ouvrir",
        "assurance_vie_gestion_arbitrage",
        "assurance_vie_fiscalite_8_ans",
        "assurance_vie_questions_pourquoi_assurance_vie",
    ],
    prerequisites=[
        "assurance_vie_ouverture_pourquoi_ouvrir",
    ],
    next_topics=[
        "assurance_vie_questions_combien_verser",
    ],
),

Topic(
    id="assurance_vie_questions_combien_verser",
    title="Existe-t-il un plafond de versement sur une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="questions_clients",
    description="Comprendre s'il existe une limite aux versements sur une assurance-vie et quelles sont les véritables contraintes à prendre en compte.",
    objective="Expliquer qu'il n'existe pas de plafond légal de versement sur une assurance-vie, tout en rappelant que des considérations patrimoniales, fiscales ou contractuelles peuvent influencer la stratégie de versement.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "plafond",
        "versement",
        "assurance-vie",
        "épargne",
        "capital",
        "investissement",
        "primes",
        "patrimoine",
    ],
    key_points=[
        "Il n'existe pas de plafond légal de versement sur une assurance-vie.",
        "Les versements peuvent être libres, programmés ou exceptionnels selon les conditions du contrat.",
        "Le montant investi doit rester cohérent avec les objectifs patrimoniaux et la situation financière du souscripteur.",
        "Des contrôles relatifs à l'origine des fonds peuvent être réalisés conformément aux obligations réglementaires.",
        "La fiscalité de la transmission peut varier selon l'âge auquel les versements sont réalisés.",
    ],
    examples=[
        "Julie, 38 ans, verse 200 € chaque mois sur son assurance-vie afin de préparer sa retraite. Elle apprécie la souplesse des versements programmés.",

        "Marc, 59 ans, reçoit un héritage et décide d'investir une partie du capital sur son assurance-vie. Avant de réaliser ce versement important, il vérifie les conséquences patrimoniales et fiscales de cette opération.",

        "Claire, cheffe d'entreprise, souhaite investir le produit de la vente de sa société. Son conseiller l'accompagne afin de déterminer si l'assurance-vie constitue une enveloppe adaptée à ce projet et comment organiser les versements.",
    ],
    vocabulary=[
        "versement",
        "prime",
        "versement libre",
        "versement programmé",
        "origine des fonds",
        "souscripteur",
        "capital",
        "allocation",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
        "Code général des impôts",
    ],
    analogies=[
        "Contrairement à certains livrets réglementés, l'assurance-vie ressemble davantage à un coffre dans lequel vous pouvez déposer autant que vous le souhaitez, sous réserve des règles applicables et de la cohérence de votre stratégie patrimoniale.",
    ],
    misconceptions=[
        "L'assurance-vie possède un plafond comme le Livret A.",
        "Au-delà d'un certain montant, il est impossible de verser davantage.",
        "Les gros versements sont automatiquement interdits.",
        "Plus je verse, plus ma fiscalité sera mauvaise.",
    ],
    common_mistakes=[
        "Comparer le fonctionnement de l'assurance-vie à celui d'un livret réglementé.",
        "Investir un capital important sans réfléchir à son allocation.",
        "Oublier que la transmission dépend notamment de la date des versements.",
        "Penser que le montant investi est le seul critère à prendre en compte.",
    ],
    expert_tips=[
        "La véritable question n'est généralement pas 'Combien puis-je verser ?', mais 'Combien est-il pertinent d'investir sur cette enveloppe au regard de mes objectifs patrimoniaux, de mon horizon de placement et de ma stratégie globale ?'.",
    ],
    attention_points=[
        "Les assureurs peuvent prévoir des montants minimums de versement selon les contrats.",
        "Les obligations de lutte contre le blanchiment peuvent conduire l'assureur à demander des justificatifs sur l'origine des fonds.",
        "Les versements importants méritent une réflexion patrimoniale globale.",
    ],
    client_questions=[
        "Existe-t-il un plafond ?",
        "Puis-je investir plusieurs centaines de milliers d'euros ?",
        "Puis-je effectuer un versement exceptionnel ?",
        "L'assureur peut-il refuser un versement ?",
    ],
    client_objections=[
        "Je pensais que l'assurance-vie était plafonnée.",
        "J'ai peur que mon versement soit refusé.",
        "Je préfère répartir mon épargne sur plusieurs placements.",
    ],
    client_fears=[
        "Dépasser une limite autorisée.",
        "Faire un mauvais choix patrimonial.",
        "Rencontrer un problème avec un versement important.",
    ],
    client_goals=[
        "Investir un capital.",
        "Préparer un projet de long terme.",
        "Organiser son patrimoine.",
        "Optimiser la transmission de son épargne.",
    ],
    client_intents=[
        "plafond assurance-vie",
        "combien puis-je verser",
        "versement important",
        "investir un capital",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_versements_libres_programmes",
        "assurance_vie_transmission_article_990_i",
        "assurance_vie_transmission_article_757_b",
        "assurance_vie_questions_plusieurs_contrats",
    ],
    prerequisites=[
        "assurance_vie_versements_libres_programmes",
    ],
    next_topics=[
        "assurance_vie_questions_enfant",
    ],
),

Topic(
    id="assurance_vie_questions_enfant",
    title="Peut-on ouvrir une assurance-vie pour son enfant ?",
    pillar="transmettre",
    family="assurance_vie",
    chapter="questions_clients",
    description="Comprendre dans quelles conditions il est possible d'ouvrir une assurance-vie au nom d'un enfant mineur et quels objectifs patrimoniaux cette démarche peut poursuivre.",
    objective="Expliquer qu'un enfant mineur peut être titulaire d'une assurance-vie ouverte par ses représentants légaux et que cette solution peut répondre à des objectifs d'épargne, de transmission ou de préparation de projets futurs.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "enfant",
        "mineur",
        "assurance-vie",
        "parents",
        "épargne",
        "transmission",
        "donation",
        "études",
    ],
    key_points=[
        "Un enfant mineur peut être titulaire d'une assurance-vie.",
        "Le contrat est généralement ouvert et administré par ses représentants légaux.",
        "L'assurance-vie peut servir à préparer des études, un premier achat immobilier ou un projet de long terme.",
        "Les versements doivent rester cohérents avec la situation patrimoniale et familiale.",
        "Une réflexion sur la disponibilité future des fonds et la stratégie d'investissement est essentielle.",
    ],
    examples=[
        "Julie et Thomas ouvrent une assurance-vie au nom de leur fille dès sa naissance afin de constituer progressivement un capital destiné à financer ses études supérieures.",

        "Marc verse chaque mois 100 € sur le contrat de son fils. Dix-huit ans plus tard, celui-ci dispose d'une épargne qui peut l'aider à financer son permis de conduire ou son premier logement.",

        "Claire reçoit une donation de ses parents qu'elle souhaite transmettre progressivement à ses petits-enfants. Avec son conseiller, elle étudie l'intérêt d'une assurance-vie adaptée à chacun d'eux.",
    ],
    vocabulary=[
        "mineur",
        "représentant légal",
        "souscripteur",
        "assuré",
        "versement",
        "épargne",
        "donation",
        "majorité",
    ],
    legal_sources=[
        "Code civil",
        "Code des assurances",
        "Code général des impôts",
    ],
    analogies=[
        "Ouvrir une assurance-vie pour un enfant revient à planter un arbre : plus il est planté tôt, plus il a le temps de grandir avant d'être utile.",
    ],
    misconceptions=[
        "Un enfant ne peut pas avoir d'assurance-vie.",
        "Il faut attendre la majorité pour ouvrir un contrat.",
        "L'argent est définitivement bloqué jusqu'à ses 18 ans.",
        "L'assurance-vie est réservée aux adultes.",
    ],
    common_mistakes=[
        "Ouvrir un contrat sans définir l'objectif patrimonial.",
        "Choisir une allocation inadaptée à l'horizon de placement.",
        "Confondre l'épargne des parents avec celle appartenant juridiquement à l'enfant.",
        "Négliger les conséquences des versements importants.",
    ],
    expert_tips=[
        "L'un des plus grands atouts d'une assurance-vie ouverte tôt est le temps. Commencer à épargner dès l'enfance permet de construire progressivement un capital tout en faisant courir l'ancienneté du contrat.",
    ],
    attention_points=[
        "Les représentants légaux administrent le contrat dans l'intérêt de l'enfant.",
        "Certaines opérations peuvent nécessiter des règles particulières de représentation ou d'autorisation.",
        "Le choix des supports d'investissement doit être cohérent avec l'horizon de placement.",
    ],
    client_questions=[
        "Puis-je ouvrir une assurance-vie pour mon bébé ?",
        "Qui est propriétaire de l'argent ?",
        "Mon enfant pourra-t-il récupérer les fonds à sa majorité ?",
        "Est-ce une bonne solution pour financer ses études ?",
    ],
    client_objections=[
        "Je pensais qu'un mineur ne pouvait pas détenir un contrat.",
        "Je préfère attendre qu'il soit majeur.",
        "Je crains de perdre le contrôle de l'épargne.",
    ],
    client_fears=[
        "Faire une erreur juridique.",
        "Bloquer inutilement l'épargne.",
        "Choisir un placement inadapté à mon enfant.",
    ],
    client_goals=[
        "Constituer un capital pour son enfant.",
        "Préparer les études ou un premier achat immobilier.",
        "Commencer à transmettre progressivement son patrimoine.",
    ],
    client_intents=[
        "ouvrir une assurance-vie pour un enfant",
        "épargner pour ses enfants",
        "préparer les études",
        "transmettre un capital",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_ouverture_pourquoi_ouvrir",
        "assurance_vie_versements_libres_programmes",
        "assurance_vie_transmission_principe_general",
        "assurance_vie_cas_particuliers_enfant_mineur",
    ],
    prerequisites=[
        "assurance_vie_ouverture_pourquoi_ouvrir",
    ],
    next_topics=[
        "assurance_vie_questions_faillite_assureur",
    ],
),

Topic(
    id="assurance_vie_questions_faillite_assureur",
    title="Que se passe-t-il si mon assureur fait faillite ?",
    pillar="proteger",
    family="assurance_vie",
    chapter="questions_clients",
    description="Comprendre les mécanismes de protection applicables en cas de défaillance d'un assureur proposant des contrats d'assurance-vie.",
    objective="Expliquer que le secteur de l'assurance est fortement réglementé et qu'il existe des mécanismes destinés à protéger les assurés en cas de défaillance d'une compagnie d'assurance.",
    difficulty="Intermédiaire",
    priority=8,
    version=1,
    keywords=[
        "faillite",
        "assureur",
        "FGAP",
        "garantie",
        "protection",
        "assurance-vie",
        "risque",
        "solvabilité",
    ],
    key_points=[
        "Les compagnies d'assurance sont soumises à une réglementation prudentielle particulièrement stricte.",
        "Les assureurs sont contrôlés par les autorités de supervision afin de protéger les assurés.",
        "En cas de défaillance d'un assureur, des mécanismes de protection existent.",
        "Le Fonds de Garantie des Assurances de Personnes (FGAP) peut intervenir dans les conditions prévues par la réglementation.",
        "Diversifier son patrimoine peut également contribuer à limiter certains risques.",
    ],
    examples=[
        "Julie souhaite investir une partie importante de son patrimoine sur une assurance-vie. Avant de choisir un assureur, elle s'interroge sur les conséquences d'une éventuelle faillite de la compagnie.",

        "Marc lit un article évoquant la défaillance d'un établissement financier et craint de perdre son épargne. Son conseiller lui explique que les compagnies d'assurance sont soumises à un cadre réglementaire spécifique et à des mécanismes de protection.",

        "Claire possède plusieurs assurances-vie auprès de différents assureurs. Cette diversification lui permet de ne pas concentrer l'ensemble de son patrimoine auprès d'un seul acteur.",
    ],
    vocabulary=[
        "FGAP",
        "solvabilité",
        "compagnie d'assurance",
        "assureur",
        "garantie",
        "supervision prudentielle",
        "ACPR",
        "défaillance",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
        "Réglementation Solvabilité II",
    ],
    analogies=[
        "Comme une banque est surveillée par les autorités financières, une compagnie d'assurance fait l'objet d'un contrôle permanent destiné à protéger les assurés et la stabilité du système.",
    ],
    misconceptions=[
        "Si mon assureur fait faillite, je perds automatiquement toute mon épargne.",
        "Les assurances-vie ne sont soumises à aucun contrôle.",
        "Toutes les compagnies présentent le même niveau de risque.",
        "Il n'existe aucun mécanisme de protection.",
    ],
    common_mistakes=[
        "Choisir un contrat uniquement en fonction de son rendement.",
        "Ignorer la solidité financière de l'assureur.",
        "Concentrer tout son patrimoine chez un seul assureur sans réflexion.",
        "Confondre les mécanismes de garantie bancaire et ceux de l'assurance.",
    ],
    expert_tips=[
        "Le risque de défaillance d'un assureur est généralement faible grâce au cadre prudentiel applicable. Pour les patrimoines importants, il peut néanmoins être pertinent d'intégrer la diversification des assureurs dans la réflexion patrimoniale globale.",
    ],
    attention_points=[
        "Les mécanismes de garantie répondent à des règles précises définies par la réglementation.",
        "Le montant des garanties peut évoluer au fil des réformes.",
        "La solidité de l'assureur constitue un critère de sélection au même titre que la qualité du contrat.",
    ],
    client_questions=[
        "Puis-je perdre mon argent si mon assureur fait faillite ?",
        "Existe-t-il une garantie ?",
        "Comment choisir un assureur solide ?",
        "Dois-je répartir mon patrimoine entre plusieurs assureurs ?",
    ],
    client_objections=[
        "Je préfère garder mon argent sur un livret.",
        "J'ai peur de confier mon patrimoine à une compagnie d'assurance.",
        "Les crises financières me rendent méfiant.",
    ],
    client_fears=[
        "Perdre son épargne.",
        "Choisir un assureur fragile.",
        "Ne pas comprendre les mécanismes de protection.",
    ],
    client_goals=[
        "Sécuriser son patrimoine.",
        "Comprendre les garanties existantes.",
        "Choisir un assureur fiable.",
    ],
    client_intents=[
        "faillite assurance-vie",
        "garantie assurance-vie",
        "FGAP",
        "sécurité assurance-vie",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_supports_fonds_euros",
        "assurance_vie_questions_pourquoi_assurance_vie",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
    ],
    next_topics=[
        "assurance_vie_questions_pourquoi_assurance_vie",
    ],
),

Topic(
    id="assurance_vie_questions_pourquoi_assurance_vie",
    title="Pourquoi ouvrir une assurance-vie aujourd'hui ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="questions_clients",
    description="Comprendre les principaux objectifs patrimoniaux auxquels peut répondre une assurance-vie et pourquoi elle demeure une enveloppe de référence.",
    objective="Expliquer que l'assurance-vie est une enveloppe patrimoniale polyvalente pouvant répondre à des objectifs d'épargne, d'investissement, de transmission ou de préparation de projets à long terme.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "assurance-vie",
        "épargne",
        "investissement",
        "transmission",
        "retraite",
        "patrimoine",
        "placement",
        "objectifs patrimoniaux",
    ],
    key_points=[
        "L'assurance-vie est une enveloppe patrimoniale particulièrement polyvalente.",
        "Elle permet d'investir sur différents supports selon son profil de risque.",
        "Elle offre une grande souplesse de versement et de retrait.",
        "Elle constitue un outil reconnu pour préparer la transmission de son patrimoine.",
        "Son intérêt dépend toujours des objectifs poursuivis et non d'un avantage isolé.",
    ],
    examples=[
        "Julie, 30 ans, ouvre une assurance-vie afin de constituer progressivement un capital pour un futur achat immobilier tout en gardant une certaine flexibilité.",

        "Marc, 52 ans, utilise son assurance-vie pour préparer un complément de revenus à la retraite grâce à une stratégie d'investissement de long terme.",

        "Claire, 67 ans, conserve son assurance-vie principalement dans une logique de transmission afin d'organiser le versement d'un capital à ses proches.",
    ],
    vocabulary=[
        "enveloppe patrimoniale",
        "épargne",
        "investissement",
        "allocation",
        "transmission",
        "fonds euros",
        "unités de compte",
        "rachat",
    ],
    legal_sources=[
        "Code des assurances",
        "Code général des impôts",
    ],
    analogies=[
        "L'assurance-vie est comparable à un couteau suisse du patrimoine : elle ne répond pas à un seul besoin, mais peut remplir plusieurs fonctions selon la manière dont elle est utilisée.",
    ],
    misconceptions=[
        "L'assurance-vie sert uniquement à transmettre un patrimoine.",
        "Elle est réservée aux personnes âgées.",
        "Elle ne présente plus d'intérêt aujourd'hui.",
        "C'est simplement un produit d'épargne comme un autre.",
    ],
    common_mistakes=[
        "Ouvrir une assurance-vie sans objectif clairement identifié.",
        "Choisir un contrat uniquement pour son rendement affiché.",
        "Négliger la rédaction de la clause bénéficiaire.",
        "Croire qu'une assurance-vie répond à tous les besoins patrimoniaux.",
    ],
    expert_tips=[
        "Une assurance-vie n'est généralement pas une fin en soi. Elle constitue une enveloppe patrimoniale qui prend tout son sens lorsqu'elle est intégrée dans une stratégie globale tenant compte de vos projets, de votre horizon de placement et de votre situation familiale.",
    ],
    attention_points=[
        "L'assurance-vie n'est pas systématiquement la solution la plus adaptée à tous les objectifs.",
        "Le choix des supports d'investissement reste déterminant.",
        "La stratégie doit évoluer avec les différentes étapes de la vie.",
    ],
    client_questions=[
        "Pourquoi ouvrir une assurance-vie aujourd'hui ?",
        "Est-ce encore intéressant ?",
        "À quoi sert réellement une assurance-vie ?",
        "Dans quels cas est-elle pertinente ?",
    ],
    client_objections=[
        "Je possède déjà un Livret A.",
        "Je suis encore trop jeune.",
        "Je préfère investir directement en Bourse.",
    ],
    client_fears=[
        "Choisir un placement inadapté.",
        "Immobiliser inutilement son épargne.",
        "Ne pas comprendre le fonctionnement du contrat.",
    ],
    client_goals=[
        "Faire fructifier son patrimoine.",
        "Préparer des projets futurs.",
        "Organiser la transmission de son patrimoine.",
        "Diversifier son épargne.",
    ],
    client_intents=[
        "pourquoi ouvrir une assurance-vie",
        "intérêt assurance-vie",
        "à quoi sert une assurance-vie",
        "choisir une assurance-vie",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_supports_principe_general",
        "assurance_vie_fiscalite_principe_general",
        "assurance_vie_transmission_principe_general",
        "assurance_vie_questions_plusieurs_contrats",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
    ],
    next_topics=[],
),

