from v2.models.knowledge_models import Topic

SUPPORTS_TOPICS: list[Topic] = []

Topic(
    id="assurance_vie_supports_fonds_euros",
    title="Qu'est-ce que le fonds euros en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="supports",
    description="Comprendre le rôle du fonds euros dans un contrat d'assurance-vie.",
    objective="Expliquer que le fonds euros est un support sécurisé, généralement garanti en capital, mais dont le rendement reste limité.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "fonds euros",
        "capital garanti",
        "sécurité",
        "rendement",
        "assurance-vie",
        "support sécurisé",
        "effet cliquet",
    ],
    key_points=[
        "Le fonds euros est le support sécurisé historique de l'assurance-vie.",
        "Le capital investi est généralement garanti par l'assureur, hors frais éventuels.",
        "Les intérêts acquis sont en principe définitivement sécurisés grâce à l'effet cliquet.",
        "Son rendement est généralement plus faible que celui des supports risqués sur le long terme.",
        "Il peut servir de poche de stabilité dans une allocation patrimoniale.",
    ],
    examples=[
        "Un épargnant prudent place une partie de son contrat sur le fonds euros pour limiter le risque de perte.",
        "Un retraité utilise le fonds euros comme poche sécurisée dans son assurance-vie.",
    ],
    vocabulary=[
        "fonds euros",
        "capital garanti",
        "effet cliquet",
        "participation aux bénéfices",
        "rendement",
        "frais de gestion",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Le fonds euros est comparable à une poche de sécurité dans le contrat : il ne cherche pas la performance maximale, mais la stabilité.",
    ],
    misconceptions=[
        "Le fonds euros rapporte toujours beaucoup.",
        "Le fonds euros est identique dans tous les contrats.",
        "Le fonds euros suffit toujours pour investir à long terme.",
    ],
    common_mistakes=[
        "Placer tout son contrat en fonds euros sans réfléchir à l'horizon de placement.",
        "Comparer uniquement le rendement d'une année.",
        "Oublier l'impact des frais sur la performance réelle.",
    ],
    expert_tips=[
        "Le fonds euros est utile pour sécuriser une partie du contrat, mais il doit être intégré dans une allocation globale.",
    ],
    attention_points=[
        "La garantie peut être brute ou nette de frais selon les contrats.",
        "L'accès au fonds euros peut être conditionné à une part minimale d'unités de compte.",
        "Le rendement futur n'est jamais garanti.",
    ],
    client_questions=[
        "Le fonds euros est-il garanti ?",
        "Puis-je perdre de l'argent sur un fonds euros ?",
        "Pourquoi le rendement varie-t-il selon les contrats ?",
        "Faut-il tout mettre sur le fonds euros ?",
    ],
    client_objections=[
        "Je veux uniquement du garanti.",
        "Je ne veux prendre aucun risque.",
    ],
    client_fears=[
        "Perdre mon capital.",
        "Ne pas comprendre les risques.",
        "Avoir un rendement trop faible.",
    ],
    client_goals=[
        "Sécuriser une partie de son épargne.",
        "Limiter le risque.",
        "Conserver une poche stable.",
    ],
    client_intents=[
        "sécuriser son épargne",
        "comprendre le fonds euros",
        "éviter la perte en capital",
        "investir prudemment",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_supports_unites_de_compte",
        "assurance_vie_supports_allocation",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
    ],
    next_topics=[
        "assurance_vie_supports_unites_de_compte",
        "assurance_vie_supports_risque",
    ],
),

Topic(
    id="assurance_vie_supports_unites_de_compte",
    title="Que sont les unités de compte en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="supports",
    description="Comprendre le fonctionnement des unités de compte et leur rôle dans une stratégie d'investissement en assurance-vie.",
    objective="Expliquer que les unités de compte permettent de rechercher une performance supérieure au fonds euros, en contrepartie d'un risque de perte en capital.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "unités de compte",
        "UC",
        "fonds d'investissement",
        "ETF",
        "actions",
        "obligations",
        "SCPI",
        "assurance-vie",
        "performance",
        "risque",
    ],
    key_points=[
        "Les unités de compte sont des supports d'investissement dont la valeur évolue à la hausse comme à la baisse.",
        "Contrairement au fonds euros, elles ne bénéficient généralement pas d'une garantie en capital.",
        "Les unités de compte donnent accès à une grande diversité d'actifs financiers et immobiliers.",
        "Le potentiel de rendement est généralement supérieur à celui du fonds euros sur le long terme, mais le risque est également plus élevé.",
        "Le choix des unités de compte doit être cohérent avec l'horizon d'investissement et le profil de risque du souscripteur.",
    ],
    examples=[
        "Julie investit une partie de son contrat sur un ETF mondial afin de rechercher une performance à long terme.",
        "Marc répartit son épargne entre un fonds euros, des actions internationales et une SCPI.",
        "Claire choisit une gestion pilotée investie principalement en unités de compte.",
    ],
    vocabulary=[
        "unité de compte",
        "ETF",
        "OPCVM",
        "SCPI",
        "action",
        "obligation",
        "allocation",
        "volatilité",
        "diversification",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Les unités de compte ressemblent à un panier d'investissements : leur valeur évolue en fonction des actifs qu'elles contiennent.",
    ],
    misconceptions=[
        "Les unités de compte sont toujours des actions.",
        "Les unités de compte garantissent le capital.",
        "Les unités de compte sont réservées aux investisseurs expérimentés.",
    ],
    common_mistakes=[
        "Investir uniquement sur un seul support.",
        "Choisir des unités de compte sans comprendre leur niveau de risque.",
        "Se focaliser uniquement sur les performances passées.",
        "Investir sur un horizon trop court.",
    ],
    expert_tips=[
        "Les unités de compte prennent tout leur intérêt lorsqu'elles sont diversifiées et conservées sur un horizon de long terme.",
    ],
    attention_points=[
        "Le capital investi peut fluctuer à la hausse comme à la baisse.",
        "Les performances passées ne préjugent pas des performances futures.",
        "Chaque unité de compte présente un niveau de risque spécifique qu'il convient d'analyser avant d'investir.",
    ],
    client_questions=[
        "Qu'est-ce qu'une unité de compte ?",
        "Puis-je perdre de l'argent ?",
        "Pourquoi investir en unités de compte ?",
        "Quelle différence avec le fonds euros ?",
    ],
    client_objections=[
        "Je ne veux prendre aucun risque.",
        "Les marchés financiers me font peur.",
        "Je préfère un placement garanti.",
    ],
    client_fears=[
        "Perdre mon capital.",
        "Investir au mauvais moment.",
        "Ne pas comprendre les supports proposés.",
    ],
    client_goals=[
        "Rechercher davantage de performance.",
        "Diversifier son patrimoine.",
        "Investir sur le long terme.",
        "Préparer des projets futurs.",
    ],
    client_intents=[
        "investir en unités de compte",
        "comprendre les UC",
        "diversifier son assurance-vie",
        "rechercher de la performance",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_supports_fonds_euros",
        "assurance_vie_supports_risque",
        "assurance_vie_supports_allocation",
        "assurance_vie_supports_etf",
        "assurance_vie_supports_scpi",
    ],
    prerequisites=[
        "assurance_vie_supports_fonds_euros",
    ],
    next_topics=[
        "assurance_vie_supports_risque",
        "assurance_vie_supports_allocation",
    ],
),

Topic(
    id="assurance_vie_supports_risque",
    title="Quel est le risque des supports en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="supports",
    description="Comprendre les différents niveaux de risque des supports d'investissement disponibles dans une assurance-vie.",
    objective="Expliquer que chaque support présente un couple rendement/risque spécifique et qu'il doit être choisi en fonction des objectifs patrimoniaux, de l'horizon de placement et de la tolérance au risque du souscripteur.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "risque",
        "rendement",
        "volatilité",
        "profil de risque",
        "assurance-vie",
        "fonds euros",
        "unités de compte",
        "investissement",
        "allocation",
    ],
    key_points=[
        "Plus le potentiel de rendement est élevé, plus le risque de perte en capital est généralement important.",
        "Le fonds euros présente un niveau de risque faible, contrairement aux unités de compte.",
        "Le risque dépend également de la durée d'investissement.",
        "La diversification permet de limiter le risque global d'un portefeuille.",
        "Le choix des supports doit être cohérent avec le profil de risque de l'investisseur.",
    ],
    examples=[
        "Julie investit principalement en fonds euros pour limiter les fluctuations de son épargne.",
        "Marc accepte davantage de risque en investissant sur des actions mondiales avec un horizon de 20 ans.",
        "Claire répartit son contrat entre fonds euros, obligations et actions afin de diversifier son patrimoine.",
    ],
    vocabulary=[
        "volatilité",
        "profil de risque",
        "perte en capital",
        "diversification",
        "allocation",
        "horizon d'investissement",
        "rendement",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
    ],
    analogies=[
        "Investir revient à conduire : aller plus vite permet parfois d'arriver plus rapidement, mais augmente aussi le risque d'accident.",
    ],
    misconceptions=[
        "Les placements les plus performants sont toujours les meilleurs.",
        "Le risque est forcément une mauvaise chose.",
        "Les unités de compte font systématiquement perdre de l'argent.",
    ],
    common_mistakes=[
        "Choisir un support uniquement parce qu'il a bien performé récemment.",
        "Sous-estimer son niveau de tolérance au risque.",
        "Investir à court terme sur des supports conçus pour le long terme.",
        "Ne pas diversifier ses investissements.",
    ],
    expert_tips=[
        "Le risque ne se supprime pas : il se pilote grâce à une allocation adaptée et un horizon d'investissement cohérent.",
    ],
    attention_points=[
        "Les performances passées ne préjugent jamais des performances futures.",
        "Une baisse temporaire n'est pas nécessairement synonyme de mauvais investissement.",
        "Le risque doit toujours être analysé au regard des objectifs patrimoniaux du souscripteur.",
    ],
    client_questions=[
        "Puis-je perdre de l'argent ?",
        "Quel support est le moins risqué ?",
        "Comment connaître mon profil de risque ?",
        "Pourquoi prendre du risque ?",
    ],
    client_objections=[
        "Je refuse toute perte en capital.",
        "Les marchés financiers sont trop dangereux.",
    ],
    client_fears=[
        "Perdre mon épargne.",
        "Choisir un investissement inadapté.",
        "Ne pas comprendre les risques encourus.",
    ],
    client_goals=[
        "Investir sereinement.",
        "Trouver le bon équilibre entre sécurité et performance.",
        "Construire une allocation adaptée.",
    ],
    client_intents=[
        "comprendre le risque",
        "choisir un support",
        "sécuriser son patrimoine",
        "investir intelligemment",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_supports_fonds_euros",
        "assurance_vie_supports_unites_de_compte",
        "assurance_vie_supports_allocation",
    ],
    prerequisites=[
        "assurance_vie_supports_unites_de_compte",
    ],
    next_topics=[
        "assurance_vie_supports_allocation",
        "assurance_vie_supports_etf",
    ],
),

Topic(
    id="assurance_vie_supports_risque",
    title="Quel est le risque des supports en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="supports",
    description="Comprendre les différents niveaux de risque des supports d'investissement disponibles dans une assurance-vie.",
    objective="Expliquer que chaque support présente un couple rendement/risque spécifique et qu'il doit être choisi en fonction des objectifs patrimoniaux, de l'horizon de placement et de la tolérance au risque du souscripteur.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "risque",
        "rendement",
        "volatilité",
        "profil de risque",
        "assurance-vie",
        "fonds euros",
        "unités de compte",
        "investissement",
        "allocation",
    ],
    key_points=[
        "Plus le potentiel de rendement est élevé, plus le risque de perte en capital est généralement important.",
        "Le fonds euros présente un niveau de risque faible, contrairement aux unités de compte.",
        "Le risque dépend également de la durée d'investissement.",
        "La diversification permet de limiter le risque global d'un portefeuille.",
        "Le choix des supports doit être cohérent avec le profil de risque de l'investisseur.",
    ],
    examples=[
        "Julie investit principalement en fonds euros pour limiter les fluctuations de son épargne.",
        "Marc accepte davantage de risque en investissant sur des actions mondiales avec un horizon de 20 ans.",
        "Claire répartit son contrat entre fonds euros, obligations et actions afin de diversifier son patrimoine.",
    ],
    vocabulary=[
        "volatilité",
        "profil de risque",
        "perte en capital",
        "diversification",
        "allocation",
        "horizon d'investissement",
        "rendement",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
    ],
    analogies=[
        "Investir revient à conduire : aller plus vite permet parfois d'arriver plus rapidement, mais augmente aussi le risque d'accident.",
    ],
    misconceptions=[
        "Les placements les plus performants sont toujours les meilleurs.",
        "Le risque est forcément une mauvaise chose.",
        "Les unités de compte font systématiquement perdre de l'argent.",
    ],
    common_mistakes=[
        "Choisir un support uniquement parce qu'il a bien performé récemment.",
        "Sous-estimer son niveau de tolérance au risque.",
        "Investir à court terme sur des supports conçus pour le long terme.",
        "Ne pas diversifier ses investissements.",
    ],
    expert_tips=[
        "Le risque ne se supprime pas : il se pilote grâce à une allocation adaptée et un horizon d'investissement cohérent.",
    ],
    attention_points=[
        "Les performances passées ne préjugent jamais des performances futures.",
        "Une baisse temporaire n'est pas nécessairement synonyme de mauvais investissement.",
        "Le risque doit toujours être analysé au regard des objectifs patrimoniaux du souscripteur.",
    ],
    client_questions=[
        "Puis-je perdre de l'argent ?",
        "Quel support est le moins risqué ?",
        "Comment connaître mon profil de risque ?",
        "Pourquoi prendre du risque ?",
    ],
    client_objections=[
        "Je refuse toute perte en capital.",
        "Les marchés financiers sont trop dangereux.",
    ],
    client_fears=[
        "Perdre mon épargne.",
        "Choisir un investissement inadapté.",
        "Ne pas comprendre les risques encourus.",
    ],
    client_goals=[
        "Investir sereinement.",
        "Trouver le bon équilibre entre sécurité et performance.",
        "Construire une allocation adaptée.",
    ],
    client_intents=[
        "comprendre le risque",
        "choisir un support",
        "sécuriser son patrimoine",
        "investir intelligemment",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_supports_fonds_euros",
        "assurance_vie_supports_unites_de_compte",
        "assurance_vie_supports_allocation",
    ],
    prerequisites=[
        "assurance_vie_supports_unites_de_compte",
    ],
    next_topics=[
        "assurance_vie_supports_allocation",
        "assurance_vie_supports_etf",
    ],
),

Topic(
    id="assurance_vie_supports_allocation",
    title="Comment répartir son épargne entre les différents supports ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="supports",
    description="Comprendre le principe de l'allocation d'actifs dans une assurance-vie et son impact sur le couple rendement/risque.",
    objective="Expliquer que la performance d'une assurance-vie dépend autant de la répartition entre les supports que du choix des supports eux-mêmes.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "allocation",
        "allocation d'actifs",
        "répartition",
        "fonds euros",
        "unités de compte",
        "diversification",
        "profil investisseur",
        "assurance-vie",
        "gestion",
    ],
    key_points=[
        "L'allocation consiste à répartir son épargne entre différents supports d'investissement.",
        "Une bonne allocation cherche à équilibrer rendement potentiel et niveau de risque.",
        "Elle dépend notamment de l'horizon de placement, des objectifs patrimoniaux et de la tolérance au risque.",
        "La diversification permet de limiter le risque lié à un seul type d'actif.",
        "Une allocation doit être revue régulièrement afin de rester cohérente avec la situation du souscripteur.",
    ],
    examples=[
        "Julie répartit son contrat entre 40 % de fonds euros et 60 % d'unités de compte afin de rechercher davantage de performance.",
        "Marc, proche de la retraite, augmente progressivement la part sécurisée de son assurance-vie.",
        "Claire investit sur plusieurs classes d'actifs afin de diversifier son patrimoine.",
    ],
    vocabulary=[
        "allocation d'actifs",
        "diversification",
        "fonds euros",
        "unités de compte",
        "profil de risque",
        "rééquilibrage",
        "horizon d'investissement",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Construire une allocation revient à composer une équipe : chaque support a un rôle différent et c'est leur complémentarité qui fait la solidité de l'ensemble.",
    ],
    misconceptions=[
        "Il existe une allocation idéale valable pour tout le monde.",
        "Plus il y a de supports, meilleure est l'allocation.",
        "Une allocation n'a jamais besoin d'être modifiée.",
    ],
    common_mistakes=[
        "Investir l'intégralité du contrat sur un seul support.",
        "Copier l'allocation d'un autre investisseur sans tenir compte de sa propre situation.",
        "Ne jamais rééquilibrer son contrat malgré l'évolution des marchés.",
        "Construire une allocation uniquement à partir des performances passées.",
    ],
    expert_tips=[
        "L'allocation d'actifs explique souvent davantage la performance d'un contrat que la sélection d'un support en particulier.",
    ],
    attention_points=[
        "Une allocation adaptée aujourd'hui peut devenir inadaptée quelques années plus tard.",
        "La diversification réduit certains risques mais ne garantit jamais une performance positive.",
        "Le profil de risque doit toujours guider la répartition des investissements.",
    ],
    client_questions=[
        "Comment répartir mon assurance-vie ?",
        "Quelle part investir sur le fonds euros ?",
        "Combien mettre en unités de compte ?",
        "Dois-je diversifier mon contrat ?",
    ],
    client_objections=[
        "Je préfère tout mettre sur le support qui rapporte le plus.",
        "La diversification me paraît compliquée.",
    ],
    client_fears=[
        "Faire une mauvaise répartition.",
        "Prendre trop de risques.",
        "Ne pas obtenir de bons résultats.",
    ],
    client_goals=[
        "Construire une allocation équilibrée.",
        "Diversifier son patrimoine.",
        "Optimiser le couple rendement/risque.",
        "Investir sur le long terme.",
    ],
    client_intents=[
        "répartir son assurance-vie",
        "diversifier ses investissements",
        "choisir une allocation",
        "optimiser son portefeuille",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_supports_fonds_euros",
        "assurance_vie_supports_unites_de_compte",
        "assurance_vie_supports_risque",
        "assurance_vie_supports_arbitrage",
    ],
    prerequisites=[
        "assurance_vie_supports_risque",
    ],
    next_topics=[
        "assurance_vie_supports_etf",
        "assurance_vie_supports_scpi",
        "assurance_vie_supports_arbitrage",
    ],
),
Topic(
    id="assurance_vie_supports_scpi",
    title="Peut-on investir en SCPI dans une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="supports",
    description="Comprendre le fonctionnement des SCPI au sein d'un contrat d'assurance-vie ainsi que leurs avantages et leurs limites.",
    objective="Expliquer comment les SCPI peuvent être intégrées dans une assurance-vie et dans quels cas elles constituent un outil de diversification patrimoniale.",
    difficulty="Intermédiaire",
    priority=9,
    version=1,
    keywords=[
        "SCPI",
        "immobilier papier",
        "assurance-vie",
        "immobilier",
        "revenus",
        "diversification",
        "unités de compte",
        "placement immobilier",
    ],
    key_points=[
        "Les SCPI sont accessibles dans certains contrats d'assurance-vie sous forme d'unités de compte.",
        "Elles permettent d'investir indirectement dans un patrimoine immobilier diversifié.",
        "Les SCPI offrent un potentiel de revenus et de valorisation, sans garantir le capital.",
        "Toutes les assurances-vie ne proposent pas les mêmes SCPI.",
        "Les conditions de détention en assurance-vie peuvent différer d'un investissement en direct.",
    ],
    examples=[
        "Julie investit une partie de son assurance-vie dans une SCPI spécialisée en immobilier de santé.",
        "Marc diversifie son contrat entre fonds euros, ETF et SCPI.",
        "Claire souhaite accéder à l'immobilier sans gérer directement des biens locatifs.",
    ],
    vocabulary=[
        "SCPI",
        "immobilier papier",
        "parts",
        "revenus",
        "unités de compte",
        "valorisation",
        "diversification",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
    ],
    analogies=[
        "Investir dans une SCPI revient à devenir copropriétaire d'un vaste parc immobilier sans avoir à gérer soi-même les immeubles.",
    ],
    misconceptions=[
        "Les SCPI garantissent le capital.",
        "Toutes les SCPI sont disponibles dans chaque assurance-vie.",
        "Les SCPI procurent toujours un revenu régulier.",
    ],
    common_mistakes=[
        "Choisir une SCPI uniquement sur la base de son rendement passé.",
        "Sous-estimer l'horizon d'investissement recommandé.",
        "Ignorer les frais propres aux SCPI et au contrat d'assurance-vie.",
    ],
    expert_tips=[
        "Les SCPI constituent souvent une excellente source de diversification, mais elles doivent représenter une part cohérente de l'allocation globale du contrat.",
    ],
    attention_points=[
        "Le capital investi n'est pas garanti.",
        "La liquidité des SCPI peut être inférieure à celle d'autres unités de compte.",
        "Les modalités de valorisation et de distribution varient selon les contrats et les sociétés de gestion.",
    ],
    client_questions=[
        "Puis-je acheter des SCPI dans mon assurance-vie ?",
        "Quels sont les avantages des SCPI ?",
        "Les SCPI sont-elles risquées ?",
        "Quelle différence entre une SCPI en direct et en assurance-vie ?",
    ],
    client_objections=[
        "Je préfère acheter directement un appartement.",
        "Je ne connais pas les SCPI.",
    ],
    client_fears=[
        "Perdre de l'argent.",
        "Ne pas pouvoir récupérer mon investissement.",
        "Investir dans un support trop complexe.",
    ],
    client_goals=[
        "Diversifier son patrimoine.",
        "Investir dans l'immobilier.",
        "Préparer des revenus complémentaires.",
        "Accéder à l'immobilier sans gestion locative.",
    ],
    client_intents=[
        "investir en SCPI",
        "diversifier son assurance-vie",
        "investir dans l'immobilier",
        "préparer des revenus futurs",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_supports_unites_de_compte",
        "assurance_vie_supports_allocation",
        "assurance_vie_supports_etf",
        "assurance_vie_supports_arbitrage",
    ],
    prerequisites=[
        "assurance_vie_supports_unites_de_compte",
        "assurance_vie_supports_allocation",
    ],
    next_topics=[
        "assurance_vie_supports_arbitrage",
        "assurance_vie_supports_erreurs",
    ],
),

Topic(
    id="assurance_vie_supports_scpi",
    title="Peut-on investir en SCPI dans une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="supports",
    description="Comprendre le fonctionnement des SCPI au sein d'un contrat d'assurance-vie ainsi que leurs avantages et leurs limites.",
    objective="Expliquer comment les SCPI peuvent être intégrées dans une assurance-vie et dans quels cas elles constituent un outil de diversification patrimoniale.",
    difficulty="Intermédiaire",
    priority=9,
    version=1,
    keywords=[
        "SCPI",
        "immobilier papier",
        "assurance-vie",
        "immobilier",
        "revenus",
        "diversification",
        "unités de compte",
        "placement immobilier",
    ],
    key_points=[
        "Les SCPI sont accessibles dans certains contrats d'assurance-vie sous forme d'unités de compte.",
        "Elles permettent d'investir indirectement dans un patrimoine immobilier diversifié.",
        "Les SCPI offrent un potentiel de revenus et de valorisation, sans garantir le capital.",
        "Toutes les assurances-vie ne proposent pas les mêmes SCPI.",
        "Les conditions de détention en assurance-vie peuvent différer d'un investissement en direct.",
    ],
    examples=[
        "Julie investit une partie de son assurance-vie dans une SCPI spécialisée en immobilier de santé.",
        "Marc diversifie son contrat entre fonds euros, ETF et SCPI.",
        "Claire souhaite accéder à l'immobilier sans gérer directement des biens locatifs.",
    ],
    vocabulary=[
        "SCPI",
        "immobilier papier",
        "parts",
        "revenus",
        "unités de compte",
        "valorisation",
        "diversification",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
    ],
    analogies=[
        "Investir dans une SCPI revient à devenir copropriétaire d'un vaste parc immobilier sans avoir à gérer soi-même les immeubles.",
    ],
    misconceptions=[
        "Les SCPI garantissent le capital.",
        "Toutes les SCPI sont disponibles dans chaque assurance-vie.",
        "Les SCPI procurent toujours un revenu régulier.",
    ],
    common_mistakes=[
        "Choisir une SCPI uniquement sur la base de son rendement passé.",
        "Sous-estimer l'horizon d'investissement recommandé.",
        "Ignorer les frais propres aux SCPI et au contrat d'assurance-vie.",
    ],
    expert_tips=[
        "Les SCPI constituent souvent une excellente source de diversification, mais elles doivent représenter une part cohérente de l'allocation globale du contrat.",
    ],
    attention_points=[
        "Le capital investi n'est pas garanti.",
        "La liquidité des SCPI peut être inférieure à celle d'autres unités de compte.",
        "Les modalités de valorisation et de distribution varient selon les contrats et les sociétés de gestion.",
    ],
    client_questions=[
        "Puis-je acheter des SCPI dans mon assurance-vie ?",
        "Quels sont les avantages des SCPI ?",
        "Les SCPI sont-elles risquées ?",
        "Quelle différence entre une SCPI en direct et en assurance-vie ?",
    ],
    client_objections=[
        "Je préfère acheter directement un appartement.",
        "Je ne connais pas les SCPI.",
    ],
    client_fears=[
        "Perdre de l'argent.",
        "Ne pas pouvoir récupérer mon investissement.",
        "Investir dans un support trop complexe.",
    ],
    client_goals=[
        "Diversifier son patrimoine.",
        "Investir dans l'immobilier.",
        "Préparer des revenus complémentaires.",
        "Accéder à l'immobilier sans gestion locative.",
    ],
    client_intents=[
        "investir en SCPI",
        "diversifier son assurance-vie",
        "investir dans l'immobilier",
        "préparer des revenus futurs",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_supports_unites_de_compte",
        "assurance_vie_supports_allocation",
        "assurance_vie_supports_etf",
        "assurance_vie_supports_arbitrage",
    ],
    prerequisites=[
        "assurance_vie_supports_unites_de_compte",
        "assurance_vie_supports_allocation",
    ],
    next_topics=[
        "assurance_vie_supports_arbitrage",
        "assurance_vie_supports_erreurs",
    ],
),

Topic(
    id="assurance_vie_supports_erreurs",
    title="Quelles erreurs éviter dans le choix des supports d'une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="supports",
    description="Identifier les principales erreurs commises lors du choix des supports d'investissement afin de construire une assurance-vie cohérente avec ses objectifs patrimoniaux.",
    objective="Sensibiliser le souscripteur aux erreurs les plus fréquentes dans la sélection et la gestion des supports d'investissement.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "erreurs",
        "supports",
        "fonds euros",
        "unités de compte",
        "allocation",
        "ETF",
        "SCPI",
        "assurance-vie",
        "diversification",
    ],
    key_points=[
        "Il n'existe pas de support universel adapté à tous les investisseurs.",
        "Le choix des supports doit toujours être cohérent avec l'horizon d'investissement.",
        "Une diversification insuffisante augmente le risque global du contrat.",
        "Les performances passées ne doivent jamais constituer le seul critère de sélection.",
        "L'allocation mérite d'être revue régulièrement afin de rester adaptée aux objectifs patrimoniaux.",
    ],
    examples=[
        "Paul investit la totalité de son contrat sur un seul fonds actions internationales.",
        "Julie choisit uniquement les supports ayant affiché les meilleures performances l'année précédente.",
        "Marc conserve la même allocation pendant quinze ans malgré l'évolution de sa situation personnelle.",
    ],
    vocabulary=[
        "allocation",
        "diversification",
        "volatilité",
        "profil de risque",
        "fonds euros",
        "unités de compte",
        "ETF",
        "SCPI",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Construire un portefeuille revient à composer une équipe : miser sur un seul joueur augmente le risque de contre-performance.",
    ],
    misconceptions=[
        "Le support le plus performant est toujours le meilleur choix.",
        "Plus un support est complexe, plus il est rentable.",
        "Une bonne allocation n'a jamais besoin d'être modifiée.",
    ],
    common_mistakes=[
        "Concentrer son épargne sur un seul support.",
        "Ignorer son horizon d'investissement.",
        "Confondre rendement passé et rendement futur.",
        "Choisir un support sans comprendre son fonctionnement.",
        "Ne jamais rééquilibrer son allocation.",
    ],
    expert_tips=[
        "La qualité d'une assurance-vie repose davantage sur la cohérence de son allocation que sur la recherche du support 'parfait'.",
    ],
    attention_points=[
        "La diversification réduit certains risques mais ne supprime jamais le risque de perte en capital.",
        "Le choix des supports doit évoluer avec les objectifs patrimoniaux du souscripteur.",
        "Les frais des supports doivent être analysés en complément de leur potentiel de performance.",
    ],
    client_questions=[
        "Quels supports choisir ?",
        "Comment éviter les erreurs ?",
        "Dois-je tout mettre sur le fonds euros ?",
        "Comment diversifier mon assurance-vie ?",
    ],
    client_objections=[
        "Je préfère investir uniquement sur le support qui a le plus monté.",
        "La diversification me paraît inutile.",
    ],
    client_fears=[
        "Choisir les mauvais supports.",
        "Perdre mon capital.",
        "Ne pas obtenir les performances espérées.",
    ],
    client_goals=[
        "Construire une allocation équilibrée.",
        "Limiter les erreurs d'investissement.",
        "Diversifier son patrimoine.",
        "Investir sur le long terme.",
    ],
    client_intents=[
        "choisir ses supports",
        "éviter les erreurs",
        "diversifier son assurance-vie",
        "optimiser son allocation",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_supports_fonds_euros",
        "assurance_vie_supports_unites_de_compte",
        "assurance_vie_supports_risque",
        "assurance_vie_supports_allocation",
        "assurance_vie_supports_etf",
        "assurance_vie_supports_scpi",
        "assurance_vie_supports_arbitrage",
    ],
    prerequisites=[
        "assurance_vie_supports_allocation",
    ],
    next_topics=[
        "assurance_vie_gestion_libre",
        "assurance_vie_gestion_pilotee",
    ],
),
