from v2.models.knowledge_models import Topic

TRANSMISSION_TOPICS: list[Topic] = []

Topic(
    id="assurance_vie_transmission_principe_general",
    title="Pourquoi l'assurance-vie est-elle un outil privilégié de transmission ?",
    pillar="transmettre",
    family="assurance_vie",
    chapter="transmission",
    description="Comprendre pourquoi l'assurance-vie occupe une place centrale dans les stratégies de transmission patrimoniale et en quoi elle se distingue de la succession classique.",
    objective="Expliquer que l'assurance-vie permet, sous certaines conditions, de transmettre un capital à un ou plusieurs bénéficiaires selon un régime juridique et fiscal spécifique.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "transmission",
        "succession",
        "assurance-vie",
        "bénéficiaire",
        "capital décès",
        "patrimoine",
        "hors succession",
        "clause bénéficiaire",
    ],
    key_points=[
        "L'assurance-vie est un outil majeur de transmission patrimoniale.",
        "Au décès de l'assuré, le capital est versé au(x) bénéficiaire(s) désigné(s), sous réserve des règles applicables.",
        "Le capital transmis ne suit pas toujours les règles classiques de la succession.",
        "Le régime juridique et fiscal de l'assurance-vie est spécifique et dépend notamment de la date des versements et de l'âge de l'assuré.",
        "La rédaction de la clause bénéficiaire joue un rôle essentiel dans l'efficacité de la transmission.",
    ],
    examples=[
        "Jean, 72 ans, souhaite transmettre une partie de son patrimoine à ses deux petits-enfants. Plutôt que de leur léguer uniquement des biens dans sa succession, il ouvre une assurance-vie afin de bénéficier du mécanisme propre à cette enveloppe et organise la désignation de ses bénéficiaires.",

        "Claire, 54 ans, souhaite protéger son conjoint tout en transmettant une partie de son patrimoine à ses enfants. Elle utilise la clause bénéficiaire de son assurance-vie pour organiser la répartition du capital selon ses objectifs.",

        "Marc, chef d'entreprise de 61 ans, possède un patrimoine diversifié. Son assurance-vie devient un outil complémentaire de sa stratégie successorale afin de faciliter la transmission d'une partie de son patrimoine financier.",
    ],
    vocabulary=[
        "transmission",
        "succession",
        "bénéficiaire",
        "clause bénéficiaire",
        "capital décès",
        "assuré",
        "souscripteur",
        "dénouement du contrat",
    ],
    legal_sources=[
        "Code des assurances",
        "Code civil",
        "Code général des impôts",
    ],
    analogies=[
        "La succession répartit l'ensemble du patrimoine selon les règles prévues par la loi ou le testament. L'assurance-vie fonctionne comme une enveloppe spécifique permettant de désigner directement les personnes appelées à recevoir le capital dans le respect des règles applicables.",
    ],
    misconceptions=[
        "L'assurance-vie échappe toujours à la succession.",
        "Les héritiers reçoivent automatiquement le capital.",
        "Le conjoint est toujours bénéficiaire du contrat.",
        "La fiscalité est identique pour tous les bénéficiaires.",
    ],
    common_mistakes=[
        "Croire que la clause bénéficiaire est secondaire.",
        "Ne jamais mettre à jour les bénéficiaires après un mariage, un divorce ou une naissance.",
        "Confondre héritier et bénéficiaire.",
        "Penser que les règles successorales classiques s'appliquent automatiquement au contrat.",
    ],
    expert_tips=[
        "L'efficacité d'une assurance-vie en matière de transmission repose moins sur le contrat lui-même que sur la qualité de la clause bénéficiaire et sur la cohérence de son articulation avec l'ensemble du patrimoine.",
    ],
    attention_points=[
        "Les règles applicables diffèrent selon la date des versements et l'âge de l'assuré au moment des primes.",
        "L'assurance-vie ne permet pas d'écarter toutes les règles du droit des successions.",
        "Chaque stratégie de transmission doit être appréciée dans son contexte patrimonial global.",
    ],
    client_questions=[
        "Pourquoi utilise-t-on l'assurance-vie pour transmettre ?",
        "Le capital fait-il partie de la succession ?",
        "Qui reçoit l'argent au décès ?",
        "Pourquoi la clause bénéficiaire est-elle si importante ?",
    ],
    client_objections=[
        "Je pensais que mon testament suffisait.",
        "Je ne comprends pas la différence avec une succession classique.",
        "Je préfère que la loi décide pour mes héritiers.",
    ],
    client_fears=[
        "Que le capital ne soit pas transmis aux bonnes personnes.",
        "Créer un conflit familial.",
        "Mal rédiger la clause bénéficiaire.",
    ],
    client_goals=[
        "Organiser sa transmission.",
        "Protéger ses proches.",
        "Anticiper sa succession.",
        "Transmettre son patrimoine dans de bonnes conditions.",
    ],
    client_intents=[
        "préparer sa transmission",
        "comprendre la succession",
        "désigner un bénéficiaire",
        "transmettre un capital",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_clause_beneficiaire_definition",
        "assurance_vie_transmission_hors_succession",
        "assurance_vie_transmission_article_990_i",
        "assurance_vie_transmission_article_757_b",
    ],
    prerequisites=[
        "assurance_vie_fiscalite_principe_general",
    ],
    next_topics=[
        "assurance_vie_transmission_hors_succession",
        "assurance_vie_clause_beneficiaire_definition",
    ],
),

Topic(
    id="assurance_vie_transmission_hors_succession",
    title="L'assurance-vie est-elle vraiment hors succession ?",
    pillar="transmettre",
    family="assurance_vie",
    chapter="transmission",
    description="Comprendre ce que signifie réellement l'expression 'hors succession' et dans quelles limites elle s'applique à l'assurance-vie.",
    objective="Expliquer que l'assurance-vie bénéficie d'un régime juridique spécifique, mais qu'elle ne se situe pas totalement en dehors du droit des successions.",
    difficulty="Intermédiaire",
    priority=10,
    version=1,
    keywords=[
        "hors succession",
        "succession",
        "assurance-vie",
        "bénéficiaire",
        "capital décès",
        "clause bénéficiaire",
        "réserve héréditaire",
        "primes manifestement exagérées",
    ],
    key_points=[
        "Le capital de l'assurance-vie n'entre généralement pas dans l'actif successoral.",
        "Le bénéficiaire désigné reçoit le capital directement de l'assureur et non dans le cadre du partage de la succession.",
        "L'expression 'hors succession' ne signifie pas que le contrat échappe à toutes les règles du droit des successions.",
        "Certaines situations, notamment en présence de primes manifestement exagérées, peuvent conduire à une remise en cause partielle du mécanisme.",
        "La rédaction de la clause bénéficiaire reste déterminante pour assurer une transmission conforme aux objectifs du souscripteur.",
    ],
    examples=[
        "Jean, veuf de 76 ans, désigne sa nièce comme bénéficiaire de son assurance-vie. Au décès, le capital est versé directement par l'assureur à cette dernière, sans passer par le partage successoral classique.",

        "Marc affirme à ses enfants que son assurance-vie est 'complètement hors succession'. Son conseiller lui explique que cette affirmation mérite d'être nuancée, notamment au regard de certaines règles civiles applicables.",

        "Claire verse une part très importante de son patrimoine sur une assurance-vie peu avant son décès. Ses héritiers s'interrogent sur les conséquences de ces versements au regard du droit des successions.",
    ],
    vocabulary=[
        "hors succession",
        "actif successoral",
        "bénéficiaire",
        "héritier",
        "clause bénéficiaire",
        "primes manifestement exagérées",
        "réserve héréditaire",
        "rapport à succession",
    ],
    legal_sources=[
        "Code des assurances",
        "Code civil",
        "Code général des impôts",
        "Jurisprudence relative aux primes manifestement exagérées",
    ],
    analogies=[
        "L'assurance-vie ressemble à une voie parallèle à la succession : elle suit son propre chemin, mais certaines passerelles permettent au droit des successions d'intervenir dans des situations particulières.",
    ],
    misconceptions=[
        "L'assurance-vie échappe totalement au droit des successions.",
        "Les héritiers récupèrent automatiquement le capital.",
        "Le capital est toujours totalement protégé.",
        "La réserve héréditaire ne peut jamais être concernée.",
    ],
    common_mistakes=[
        "Utiliser l'expression 'hors succession' sans en connaître les limites.",
        "Croire qu'il est possible de contourner toutes les règles successorales grâce à l'assurance-vie.",
        "Négliger la rédaction de la clause bénéficiaire.",
        "Ignorer la notion de primes manifestement exagérées.",
    ],
    expert_tips=[
        "L'assurance-vie constitue un formidable outil de transmission, mais elle ne doit jamais être présentée comme un mécanisme permettant d'écarter systématiquement les règles du droit des successions.",
    ],
    attention_points=[
        "Chaque situation doit être analysée dans son contexte civil et fiscal.",
        "La notion de primes manifestement exagérées relève d'une appréciation au cas par cas.",
        "Le régime de l'assurance-vie résulte d'un équilibre entre le Code des assurances, le Code civil et la jurisprudence.",
    ],
    client_questions=[
        "L'assurance-vie est-elle vraiment hors succession ?",
        "Mes héritiers peuvent-ils contester mon contrat ?",
        "Le capital entre-t-il dans la succession ?",
        "Que signifie exactement 'hors succession' ?",
    ],
    client_objections=[
        "On m'a toujours dit que l'assurance-vie échappait totalement à la succession.",
        "Je pensais pouvoir transmettre librement tout mon patrimoine grâce à une assurance-vie.",
        "Je ne comprends pas pourquoi les héritiers pourraient intervenir.",
    ],
    client_fears=[
        "Que mes volontés ne soient pas respectées.",
        "Qu'un bénéficiaire perde tout ou partie du capital.",
        "Créer un conflit entre les bénéficiaires et les héritiers.",
    ],
    client_goals=[
        "Comprendre les règles de transmission.",
        "Sécuriser la désignation des bénéficiaires.",
        "Préparer une transmission conforme à ses objectifs.",
    ],
    client_intents=[
        "comprendre le hors succession",
        "préparer sa succession",
        "transmettre son patrimoine",
        "sécuriser une assurance-vie",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_transmission_principe_general",
        "assurance_vie_clause_beneficiaire_definition",
        "assurance_vie_transmission_article_990_i",
        "assurance_vie_transmission_article_757_b",
        "assurance_vie_transmission_demembrement",
    ],
    prerequisites=[
        "assurance_vie_transmission_principe_general",
    ],
    next_topics=[
        "assurance_vie_clause_beneficiaire_definition",
        "assurance_vie_transmission_article_990_i",
    ],
),

Topic(
    id="assurance_vie_clause_beneficiaire_definition",
    title="Qu'est-ce que la clause bénéficiaire d'une assurance-vie ?",
    pillar="transmettre",
    family="assurance_vie",
    chapter="transmission",
    description="Comprendre le rôle de la clause bénéficiaire et son importance dans la transmission du capital d'une assurance-vie.",
    objective="Expliquer que la clause bénéficiaire permet de désigner la ou les personnes qui recevront le capital au décès de l'assuré et qu'elle constitue l'élément central de toute stratégie de transmission en assurance-vie.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "clause bénéficiaire",
        "bénéficiaire",
        "assurance-vie",
        "transmission",
        "succession",
        "capital décès",
        "stipulation pour autrui",
        "rédaction",
    ],
    key_points=[
        "La clause bénéficiaire désigne la ou les personnes qui recevront le capital de l'assurance-vie au décès de l'assuré.",
        "Elle peut désigner des personnes physiques ou morales.",
        "Le souscripteur est libre de modifier la clause tant que le bénéficiaire ne l'a pas acceptée dans les conditions prévues par la loi.",
        "Une clause mal rédigée peut entraîner des difficultés d'interprétation ou des conséquences contraires aux volontés du souscripteur.",
        "La clause bénéficiaire constitue le véritable cœur de la stratégie de transmission en assurance-vie.",
    ],
    examples=[
        "Jean, 67 ans, désigne son épouse comme bénéficiaire principale et ses deux enfants à défaut. Cette rédaction permet d'assurer la protection du conjoint tout en prévoyant une solution si celui-ci décède avant lui.",

        "Claire, divorcée avec trois enfants, découvre que la clause bénéficiaire de son contrat mentionne toujours son ancien conjoint. Elle décide de la mettre à jour afin qu'elle corresponde à sa situation familiale actuelle.",

        "Marc souhaite transmettre une partie de son patrimoine à son neveu handicapé. Plutôt que de s'en remettre uniquement aux règles successorales, il adapte sa clause bénéficiaire afin qu'elle reflète précisément ses volontés.",
    ],
    vocabulary=[
        "clause bénéficiaire",
        "bénéficiaire",
        "souscripteur",
        "assuré",
        "acceptation du bénéficiaire",
        "capital décès",
        "stipulation pour autrui",
        "bénéficiaire de premier rang",
        "bénéficiaire de second rang",
    ],
    legal_sources=[
        "Code des assurances",
        "Code civil",
    ],
    analogies=[
        "La clause bénéficiaire est comparable au GPS de votre assurance-vie : elle indique précisément à qui le capital doit être versé. Sans une destination claire, le risque d'erreur augmente considérablement.",
    ],
    misconceptions=[
        "Les héritiers sont automatiquement bénéficiaires.",
        "La clause bénéficiaire ne peut plus être modifiée après la souscription.",
        "Le testament remplace automatiquement la clause bénéficiaire.",
        "La clause standard convient dans toutes les situations.",
    ],
    common_mistakes=[
        "Conserver une clause devenue inadaptée après un mariage, un divorce ou une naissance.",
        "Désigner un bénéficiaire sans prévoir de bénéficiaire de second rang.",
        "Utiliser des formulations imprécises pouvant créer un conflit d'interprétation.",
        "Ne jamais relire la clause bénéficiaire pendant plusieurs décennies.",
    ],
    expert_tips=[
        "Dans une stratégie patrimoniale, la qualité de la clause bénéficiaire est souvent plus importante que le choix du contrat lui-même. Une clause régulièrement mise à jour permet d'assurer que le capital sera transmis conformément aux volontés du souscripteur.",
    ],
    attention_points=[
        "La clause bénéficiaire doit évoluer avec les changements familiaux et patrimoniaux.",
        "Certaines rédactions nécessitent une vigilance particulière lorsqu'elles concernent des familles recomposées ou des situations complexes.",
        "L'acceptation du bénéfiaire peut limiter les possibilités de modification de la clause dans les conditions prévues par la loi.",
    ],
    client_questions=[
        "À quoi sert la clause bénéficiaire ?",
        "Puis-je modifier mon bénéficiaire ?",
        "Qui reçoit l'argent si aucun bénéficiaire n'est désigné ?",
        "Dois-je utiliser la clause standard proposée par l'assureur ?",
    ],
    client_objections=[
        "Je préfère laisser la clause proposée par défaut.",
        "Je modifierai la clause plus tard.",
        "Mes héritiers se débrouilleront entre eux.",
    ],
    client_fears=[
        "Que le capital soit versé à la mauvaise personne.",
        "Créer un conflit familial.",
        "Oublier de mettre à jour la clause bénéficiaire.",
    ],
    client_goals=[
        "Transmettre son patrimoine conformément à ses volontés.",
        "Protéger ses proches.",
        "Sécuriser la transmission de son assurance-vie.",
    ],
    client_intents=[
        "désigner un bénéficiaire",
        "modifier la clause bénéficiaire",
        "préparer sa transmission",
        "protéger ses proches",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_transmission_principe_general",
        "assurance_vie_transmission_hors_succession",
        "assurance_vie_clause_beneficiaire_modification",
        "assurance_vie_transmission_article_990_i",
    ],
    prerequisites=[
        "assurance_vie_transmission_principe_general",
        "assurance_vie_transmission_hors_succession",
    ],
    next_topics=[
        "assurance_vie_clause_beneficiaire_modification",
        "assurance_vie_transmission_article_990_i",
    ],
),

Topic(
    id="assurance_vie_clause_beneficiaire_modification",
    title="Peut-on modifier la clause bénéficiaire d'une assurance-vie ?",
    pillar="transmettre",
    family="assurance_vie",
    chapter="transmission",
    description="Comprendre dans quelles conditions la clause bénéficiaire peut être modifiée et pourquoi il est essentiel de la mettre à jour tout au long de la vie du contrat.",
    objective="Expliquer que la clause bénéficiaire est généralement modifiable par le souscripteur, sous réserve des règles relatives à l'acceptation du bénéfiaire, et qu'elle doit évoluer avec la situation familiale et patrimoniale.",
    difficulty="Intermédiaire",
    priority=10,
    version=1,
    keywords=[
        "modifier la clause bénéficiaire",
        "clause bénéficiaire",
        "acceptation du bénéficiaire",
        "assurance-vie",
        "transmission",
        "avenant",
        "bénéficiaire",
        "succession",
    ],
    key_points=[
        "La clause bénéficiaire peut généralement être modifiée à tout moment par le souscripteur.",
        "L'acceptation du bénéficiaire peut limiter cette possibilité dans les conditions prévues par la loi.",
        "Chaque changement de situation familiale ou patrimoniale justifie de relire la clause bénéficiaire.",
        "La modification peut être réalisée selon les modalités prévues par l'assureur.",
        "Une clause bénéficiaire régulièrement mise à jour limite les risques de contentieux lors du décès.",
    ],
    examples=[
        "Julie, 39 ans, divorce après quinze années de mariage. En relisant son contrat, elle constate que son ex-conjoint est toujours désigné comme bénéficiaire. Elle demande rapidement la modification de sa clause afin qu'elle corresponde à sa nouvelle situation familiale.",

        "Marc, 45 ans, devient père pour la première fois. Il complète sa clause bénéficiaire afin de prévoir la transmission du capital à son enfant si son conjoint venait à décéder avant lui.",

        "Sophie, 67 ans, souhaite transmettre une partie de son patrimoine à ses petits-enfants. Après plusieurs années sans revoir son contrat, elle adapte la rédaction de sa clause bénéficiaire pour refléter ses nouveaux objectifs patrimoniaux.",
    ],
    vocabulary=[
        "avenant",
        "acceptation du bénéficiaire",
        "clause bénéficiaire",
        "souscripteur",
        "assuré",
        "bénéficiaire",
        "modification",
        "transmission",
    ],
    legal_sources=[
        "Code des assurances",
        "Code civil",
    ],
    analogies=[
        "La clause bénéficiaire ressemble au carnet d'adresses de votre assurance-vie : si vous ne le mettez jamais à jour, le capital risque d'être transmis à une personne qui ne correspond plus à vos volontés.",
    ],
    misconceptions=[
        "La clause bénéficiaire ne peut plus être modifiée après la souscription.",
        "Le mariage ou le divorce modifie automatiquement la clause bénéficiaire.",
        "Le testament met automatiquement à jour le bénéficiaire.",
        "Une fois un bénéficiaire désigné, il est impossible de revenir en arrière.",
    ],
    common_mistakes=[
        "Ne jamais relire la clause bénéficiaire.",
        "Oublier de modifier la clause après un divorce, un remariage ou une naissance.",
        "Confondre héritier légal et bénéficiaire du contrat.",
        "Ignorer les conséquences d'une acceptation du bénéficiaire.",
    ],
    expert_tips=[
        "La clause bénéficiaire mérite d'être relue à chaque événement important de la vie : mariage, divorce, naissance, décès, recomposition familiale ou évolution patrimoniale. Quelques minutes de vérification peuvent éviter des années de contentieux.",
    ],
    attention_points=[
        "L'acceptation du bénéficiaire obéit à des règles juridiques spécifiques.",
        "Une rédaction imprécise peut entraîner des difficultés d'interprétation.",
        "La clause bénéficiaire doit être cohérente avec l'ensemble de la stratégie patrimoniale du souscripteur.",
    ],
    client_questions=[
        "Puis-je changer mon bénéficiaire ?",
        "Que se passe-t-il après un divorce ?",
        "Mon testament suffit-il à modifier mon assurance-vie ?",
        "À quelle fréquence faut-il relire la clause bénéficiaire ?",
    ],
    client_objections=[
        "Je modifierai la clause plus tard.",
        "Je pensais que le mariage mettait automatiquement la clause à jour.",
        "Je n'ai jamais eu besoin d'y toucher.",
    ],
    client_fears=[
        "Que le capital soit transmis à une personne que je ne souhaite plus avantager.",
        "Créer un conflit familial.",
        "Ne plus pouvoir modifier mon contrat.",
    ],
    client_goals=[
        "Maintenir une clause bénéficiaire à jour.",
        "Sécuriser la transmission de son patrimoine.",
        "Adapter son contrat aux évolutions de sa vie.",
    ],
    client_intents=[
        "modifier un bénéficiaire",
        "mettre à jour sa clause bénéficiaire",
        "préparer sa succession",
        "adapter son assurance-vie",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_clause_beneficiaire_definition",
        "assurance_vie_transmission_hors_succession",
        "assurance_vie_transmission_article_990_i",
        "assurance_vie_transmission_article_757_b",
    ],
    prerequisites=[
        "assurance_vie_clause_beneficiaire_definition",
    ],
    next_topics=[
        "assurance_vie_transmission_article_990_i",
        "assurance_vie_transmission_article_757_b",
    ],
),

Topic(
    id="assurance_vie_transmission_article_990_i",
    title="Comment fonctionne l'article 990 I du CGI en assurance-vie ?",
    pillar="transmettre",
    family="assurance_vie",
    chapter="transmission",
    description="Comprendre le régime fiscal applicable aux capitaux transmis par une assurance-vie lorsque les primes ont été versées avant les 70 ans de l'assuré.",
    objective="Expliquer le fonctionnement général de l'article 990 I du Code général des impôts, les bénéficiaires concernés et son rôle dans la transmission patrimoniale.",
    difficulty="Intermédiaire",
    priority=10,
    version=1,
    keywords=[
        "990 I",
        "CGI",
        "article 990 I",
        "assurance-vie",
        "transmission",
        "bénéficiaire",
        "avant 70 ans",
        "capital décès",
        "fiscalité successorale",
    ],
    key_points=[
        "L'article 990 I du CGI s'applique, sous certaines conditions, aux capitaux issus des primes versées avant les 70 ans de l'assuré.",
        "Chaque bénéficiaire est apprécié individuellement pour l'application du régime fiscal prévu par cet article.",
        "Le régime fiscal dépend des capitaux transmis à chaque bénéficiaire.",
        "Les règles prévues par l'article 990 I sont distinctes de celles applicables aux versements réalisés après 70 ans.",
        "Ce dispositif constitue l'un des principaux atouts patrimoniaux de l'assurance-vie en matière de transmission.",
    ],
    examples=[
        "Jean, 64 ans, alimente régulièrement son assurance-vie avant son 70ᵉ anniversaire. À son décès, ses deux enfants sont bénéficiaires du contrat. Chacun bénéficie du régime fiscal applicable à sa propre part des capitaux transmis.",

        "Claire ouvre une assurance-vie à 52 ans afin d'organiser la transmission d'une partie de son patrimoine à sa nièce. Avant d'effectuer de nouveaux versements, elle cherche à comprendre les conséquences de l'article 990 I.",

        "Marc, 68 ans, souhaite transmettre son patrimoine à plusieurs bénéficiaires. Avec son conseiller, il vérifie les conséquences patrimoniales des versements réalisés avant ses 70 ans afin d'organiser efficacement la transmission.",
    ],
    vocabulary=[
        "article 990 I",
        "CGI",
        "bénéficiaire",
        "capital décès",
        "assuré",
        "primes",
        "versements",
        "transmission",
    ],
    legal_sources=[
        "Code général des impôts - article 990 I",
        "BOFiP - Assurance-vie",
        "Code des assurances",
    ],
    analogies=[
        "L'article 990 I fonctionne comme une règle spécifique attachée aux versements effectués avant un certain âge : ce n'est pas le contrat qui change, mais le régime fiscal applicable au capital transmis.",
    ],
    misconceptions=[
        "Toutes les assurances-vie relèvent automatiquement de l'article 990 I.",
        "L'article 990 I s'applique quelle que soit la date des versements.",
        "Tous les bénéficiaires sont imposés de la même manière.",
        "Le contrat devient exonéré de toute fiscalité successorale.",
    ],
    common_mistakes=[
        "Confondre l'article 990 I avec l'article 757 B.",
        "Croire que l'âge du bénéficiaire est déterminant.",
        "Confondre l'âge de souscription avec l'âge des versements.",
        "Ignorer que chaque bénéficiaire est apprécié séparément.",
    ],
    expert_tips=[
        "En pratique, l'une des premières questions à se poser est simple : les primes ont-elles été versées avant ou après les 70 ans de l'assuré ? Cette distinction conditionne souvent le régime fiscal applicable.",
    ],
    attention_points=[
        "L'article 990 I ne couvre pas toutes les situations de transmission en assurance-vie.",
        "Les règles applicables doivent être distinguées de celles prévues par l'article 757 B du CGI.",
        "Les seuils et taux relèvent de la législation en vigueur et peuvent évoluer.",
    ],
    client_questions=[
        "Qu'est-ce que l'article 990 I ?",
        "Pourquoi parle-t-on des versements avant 70 ans ?",
        "Qui est concerné par ce régime fiscal ?",
        "Quelle différence avec l'article 757 B ?",
    ],
    client_objections=[
        "Je ne comprends pas la différence entre les deux régimes.",
        "Les règles fiscales me semblent beaucoup trop complexes.",
        "Je pensais que seul l'âge du contrat comptait.",
    ],
    client_fears=[
        "Appliquer le mauvais régime fiscal.",
        "Organiser une transmission inefficace.",
        "Confondre les règles applicables avant et après 70 ans.",
    ],
    client_goals=[
        "Comprendre les règles de transmission.",
        "Préparer efficacement sa succession.",
        "Optimiser la transmission de son patrimoine.",
    ],
    client_intents=[
        "comprendre l'article 990 I",
        "transmettre son assurance-vie",
        "préparer sa succession",
        "optimiser sa transmission",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_transmission_principe_general",
        "assurance_vie_transmission_hors_succession",
        "assurance_vie_clause_beneficiaire_definition",
        "assurance_vie_transmission_article_757_b",
    ],
    prerequisites=[
        "assurance_vie_transmission_principe_general",
        "assurance_vie_clause_beneficiaire_definition",
    ],
    next_topics=[
        "assurance_vie_transmission_article_757_b",
        "assurance_vie_transmission_demembrement",
    ],
),

Topic(
    id="assurance_vie_transmission_article_757_b",
    title="Comment fonctionne l'article 757 B du CGI en assurance-vie ?",
    pillar="transmettre",
    family="assurance_vie",
    chapter="transmission",
    description="Comprendre le régime fiscal applicable aux primes versées après les 70 ans de l'assuré dans le cadre d'une assurance-vie.",
    objective="Expliquer que l'article 757 B du Code général des impôts prévoit un régime spécifique pour les versements réalisés après les 70 ans de l'assuré, distinct de celui applicable aux versements antérieurs.",
    difficulty="Intermédiaire",
    priority=10,
    version=1,
    keywords=[
        "757 B",
        "CGI",
        "article 757 B",
        "assurance-vie",
        "transmission",
        "après 70 ans",
        "primes",
        "succession",
        "fiscalité",
    ],
    key_points=[
        "L'article 757 B du CGI concerne les primes versées après les 70 ans de l'assuré.",
        "Il constitue un régime distinct de celui prévu par l'article 990 I.",
        "L'âge pris en compte est celui de l'assuré au moment des versements, et non celui du décès.",
        "Les règles fiscales portent principalement sur les primes versées selon les conditions prévues par le CGI.",
        "Une même assurance-vie peut relever simultanément des articles 990 I et 757 B lorsque des versements ont été effectués avant et après 70 ans.",
    ],
    examples=[
        "Jean ouvre une assurance-vie à 58 ans et continue à l'alimenter après ses 70 ans. À son décès, les versements effectués avant et après cet âge relèvent de régimes fiscaux différents.",

        "Claire, 74 ans, reçoit un héritage qu'elle souhaite investir en assurance-vie. Avant d'effectuer le versement, elle cherche à comprendre les conséquences de l'article 757 B afin d'intégrer cette décision dans sa stratégie de transmission.",

        "Marc, 82 ans, possède un contrat ouvert depuis plus de vingt ans. Son conseiller distingue soigneusement les versements réalisés avant et après ses 70 ans afin d'anticiper le traitement fiscal applicable aux bénéficiaires.",
    ],
    vocabulary=[
        "article 757 B",
        "CGI",
        "primes",
        "versements",
        "assuré",
        "bénéficiaire",
        "transmission",
        "succession",
    ],
    legal_sources=[
        "Code général des impôts - article 757 B",
        "BOFiP - Assurance-vie",
        "Code des assurances",
    ],
    analogies=[
        "Imaginez deux compartiments dans un même contrat : l'un contient les versements réalisés avant 70 ans, l'autre ceux effectués après 70 ans. Chacun suit ses propres règles fiscales au moment de la transmission.",
    ],
    misconceptions=[
        "Après 70 ans, il ne faut plus verser sur une assurance-vie.",
        "Tous les capitaux transmis relèvent automatiquement de l'article 757 B.",
        "L'âge du bénéficiaire est déterminant.",
        "Le contrat change de régime fiscal lorsqu'on atteint 70 ans.",
    ],
    common_mistakes=[
        "Confondre la date d'ouverture du contrat avec la date des versements.",
        "Croire que les versements après 70 ans perdent tout intérêt patrimonial.",
        "Mélanger les règles des articles 990 I et 757 B.",
        "Penser qu'il faut fermer son contrat à 70 ans.",
    ],
    expert_tips=[
        "La véritable question n'est pas de savoir s'il faut encore alimenter une assurance-vie après 70 ans, mais d'intégrer ces versements dans une réflexion patrimoniale globale. L'assurance-vie peut conserver un intérêt, même après cet âge.",
    ],
    attention_points=[
        "L'article 757 B s'applique selon des règles spécifiques prévues par le CGI.",
        "Les conséquences fiscales doivent être analysées en tenant compte de l'ensemble du patrimoine.",
        "Les montants et modalités applicables peuvent évoluer avec la législation.",
    ],
    client_questions=[
        "Puis-je encore alimenter mon assurance-vie après 70 ans ?",
        "Pourquoi distingue-t-on les versements avant et après 70 ans ?",
        "Mon contrat change-t-il à mes 70 ans ?",
        "Quelle différence avec l'article 990 I ?",
    ],
    client_objections=[
        "On m'a dit qu'une assurance-vie ne servait plus à rien après 70 ans.",
        "Je pensais qu'il fallait arrêter les versements.",
        "Je ne comprends pas la différence entre les deux régimes.",
    ],
    client_fears=[
        "Faire un versement fiscalement inadapté.",
        "Pénaliser mes bénéficiaires.",
        "Prendre une mauvaise décision patrimoniale.",
    ],
    client_goals=[
        "Comprendre les règles applicables après 70 ans.",
        "Préparer efficacement sa transmission.",
        "Organiser son patrimoine sur le long terme.",
    ],
    client_intents=[
        "comprendre l'article 757 B",
        "verser après 70 ans",
        "préparer sa succession",
        "optimiser sa transmission",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_transmission_article_990_i",
        "assurance_vie_transmission_principe_general",
        "assurance_vie_clause_beneficiaire_definition",
        "assurance_vie_transmission_demembrement",
    ],
    prerequisites=[
        "assurance_vie_transmission_article_990_i",
    ],
    next_topics=[
        "assurance_vie_transmission_demembrement",
        "assurance_vie_transmission_erreurs",
    ],
),

Topic(
    id="assurance_vie_transmission_demembrement",
    title="Pourquoi démembrer la clause bénéficiaire d'une assurance-vie ?",
    pillar="transmettre",
    family="assurance_vie",
    chapter="transmission",
    description="Comprendre le fonctionnement du démembrement de la clause bénéficiaire et son intérêt dans une stratégie de transmission patrimoniale.",
    objective="Expliquer que le démembrement de la clause bénéficiaire permet de répartir les droits sur le capital entre un usufruitier et un ou plusieurs nus-propriétaires afin de répondre à des objectifs de protection et de transmission.",
    difficulty="Avancé",
    priority=9,
    version=1,
    keywords=[
        "démembrement",
        "clause bénéficiaire",
        "usufruit",
        "nue-propriété",
        "quasi-usufruit",
        "créance de restitution",
        "assurance-vie",
        "transmission",
    ],
    key_points=[
        "La clause bénéficiaire peut prévoir un démembrement entre usufruitier et nus-propriétaires.",
        "Cette technique est fréquemment utilisée pour protéger un conjoint tout en préservant les droits des enfants.",
        "Dans de nombreuses situations, le conjoint survivant reçoit le capital en quasi-usufruit tandis que les enfants deviennent créanciers d'une créance de restitution.",
        "Le démembrement nécessite une rédaction particulièrement rigoureuse de la clause bénéficiaire.",
        "Cette stratégie doit être adaptée aux objectifs patrimoniaux et à la situation familiale.",
    ],
    examples=[
        "Jean, 69 ans, souhaite protéger son épouse tout en garantissant que le patrimoine reviendra à leurs enfants. Sa clause bénéficiaire prévoit un quasi-usufruit au profit du conjoint survivant et une nue-propriété au profit des enfants.",

        "Claire est remariée et a des enfants issus d'une première union. Elle utilise une clause bénéficiaire démembrée afin d'assurer un niveau de vie à son conjoint tout en préservant les intérêts de ses enfants.",

        "Marc possède un patrimoine financier important. Avec son conseiller, il met en place une clause bénéficiaire démembrée afin d'organiser une transmission progressive conforme à ses objectifs familiaux.",
    ],
    vocabulary=[
        "usufruit",
        "nue-propriété",
        "quasi-usufruit",
        "créance de restitution",
        "clause bénéficiaire démembrée",
        "usufruitier",
        "nu-propriétaire",
        "transmission",
    ],
    legal_sources=[
        "Code civil",
        "Code des assurances",
        "Code général des impôts",
    ],
    analogies=[
        "Le démembrement revient à confier deux missions différentes : une personne peut utiliser librement le capital pendant sa vie, tandis qu'une autre est assurée de récupérer la valeur correspondante ultérieurement.",
    ],
    misconceptions=[
        "Le démembrement est réservé aux très grandes fortunes.",
        "Les enfants perdent définitivement leurs droits.",
        "Le conjoint devient propriétaire définitif des capitaux.",
        "Le démembrement complique inutilement une assurance-vie.",
    ],
    common_mistakes=[
        "Utiliser une clause standard alors qu'une clause démembrée serait plus adaptée.",
        "Oublier de prévoir les modalités de la créance de restitution.",
        "Confondre usufruit classique et quasi-usufruit.",
        "Mettre en place un démembrement sans réflexion patrimoniale globale.",
    ],
    expert_tips=[
        "Le démembrement de la clause bénéficiaire est l'un des outils les plus puissants de l'ingénierie patrimoniale. Bien rédigé, il permet souvent de concilier deux objectifs qui semblent opposés : protéger un proche aujourd'hui tout en préservant les droits des héritiers demain.",
    ],
    attention_points=[
        "Une clause démembrée doit être rédigée avec une grande précision.",
        "Les conséquences civiles et fiscales doivent être analysées conjointement.",
        "La créance de restitution constitue un élément essentiel du mécanisme.",
    ],
    client_questions=[
        "Pourquoi parler d'usufruit dans une assurance-vie ?",
        "Comment protéger mon conjoint sans léser mes enfants ?",
        "Qu'est-ce que le quasi-usufruit ?",
        "Le démembrement est-il adapté à ma situation ?",
    ],
    client_objections=[
        "Cette technique me paraît beaucoup trop complexe.",
        "Je préfère une clause bénéficiaire classique.",
        "Je crains que cela crée des tensions entre mes proches.",
    ],
    client_fears=[
        "Mal protéger mon conjoint.",
        "Créer un conflit entre les enfants et le conjoint survivant.",
        "Mettre en place une clause juridiquement inadaptée.",
    ],
    client_goals=[
        "Protéger son conjoint.",
        "Préserver les droits des enfants.",
        "Optimiser la transmission familiale.",
        "Anticiper les conséquences du décès.",
    ],
    client_intents=[
        "comprendre le démembrement",
        "protéger son conjoint",
        "préparer sa transmission",
        "organiser une clause bénéficiaire",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_clause_beneficiaire_definition",
        "assurance_vie_clause_beneficiaire_modification",
        "assurance_vie_transmission_article_990_i",
        "assurance_vie_transmission_article_757_b",
    ],
    prerequisites=[
        "assurance_vie_clause_beneficiaire_definition",
        "assurance_vie_transmission_article_757_b",
    ],
    next_topics=[
        "assurance_vie_transmission_erreurs",
    ],
),

Topic(
    id="assurance_vie_transmission_erreurs",
    title="Quelles erreurs éviter lors de la transmission d'une assurance-vie ?",
    pillar="transmettre",
    family="assurance_vie",
    chapter="transmission",
    description="Identifier les erreurs les plus fréquentes en matière de transmission afin de sécuriser la rédaction de son assurance-vie et de respecter ses volontés.",
    objective="Sensibiliser les souscripteurs aux erreurs civiles, fiscales et rédactionnelles qui peuvent compromettre l'efficacité d'une transmission par assurance-vie.",
    difficulty="Intermédiaire",
    priority=10,
    version=1,
    keywords=[
        "transmission",
        "erreurs",
        "assurance-vie",
        "clause bénéficiaire",
        "succession",
        "990 I",
        "757 B",
        "démembrement",
        "bénéficiaire",
    ],
    key_points=[
        "Une clause bénéficiaire non mise à jour peut conduire à transmettre le capital à une personne qui ne correspond plus aux volontés du souscripteur.",
        "Les règles civiles et fiscales de la transmission doivent être analysées conjointement.",
        "Les versements avant et après 70 ans répondent à des régimes fiscaux différents.",
        "La rédaction de la clause bénéficiaire est souvent plus importante que le choix du contrat lui-même.",
        "Une stratégie de transmission doit évoluer avec les changements familiaux et patrimoniaux.",
    ],
    examples=[
        "Jean, 71 ans, divorce mais oublie de modifier la clause bénéficiaire de son assurance-vie. À son décès, son ex-épouse reste bénéficiaire du contrat alors que son intention était désormais de transmettre à ses enfants.",

        "Claire, remariée avec une famille recomposée, conserve la clause standard proposée lors de la souscription vingt ans plus tôt. Cette rédaction imprécise provoque des interrogations entre son conjoint survivant et ses enfants au moment du dénouement du contrat.",

        "Marc, chef d'entreprise, pense que son testament suffit à organiser toute sa transmission. Il découvre que l'assurance-vie obéit à des règles propres et que la clause bénéficiaire mérite une attention particulière.",
    ],
    vocabulary=[
        "clause bénéficiaire",
        "bénéficiaire",
        "hors succession",
        "990 I",
        "757 B",
        "quasi-usufruit",
        "créance de restitution",
        "primes manifestement exagérées",
    ],
    legal_sources=[
        "Code des assurances",
        "Code civil",
        "Code général des impôts",
        "BOFiP - Assurance-vie",
    ],
    analogies=[
        "Préparer une transmission sans relire sa clause bénéficiaire revient à programmer un GPS il y a vingt ans et espérer qu'il vous conduise toujours au bon endroit aujourd'hui.",
    ],
    misconceptions=[
        "L'assurance-vie est totalement hors succession.",
        "La clause bénéficiaire n'a pas besoin d'être mise à jour.",
        "Le testament remplace automatiquement la clause bénéficiaire.",
        "Après 70 ans, une assurance-vie ne présente plus aucun intérêt.",
        "Tous les bénéficiaires sont imposés de la même manière.",
    ],
    common_mistakes=[
        "Ne jamais relire sa clause bénéficiaire.",
        "Confondre héritier et bénéficiaire.",
        "Ignorer les conséquences des versements avant et après 70 ans.",
        "Utiliser une clause standard dans une famille recomposée.",
        "Oublier de prévoir un bénéficiaire de second rang.",
        "Croire que la fiscalité suffit à construire une bonne stratégie de transmission.",
    ],
    expert_tips=[
        "Une transmission réussie repose rarement sur un seul contrat. Elle résulte d'un ensemble cohérent : régime matrimonial, testament, donations, assurance-vie et clause bénéficiaire doivent être pensés comme les pièces d'un même puzzle patrimonial.",
    ],
    attention_points=[
        "Relisez votre clause bénéficiaire après chaque événement familial majeur.",
        "La qualité de la rédaction est souvent déterminante en cas de décès.",
        "Les situations de familles recomposées nécessitent une vigilance particulière.",
        "Une stratégie efficace est avant tout une stratégie régulièrement actualisée.",
    ],
    client_questions=[
        "Quelles sont les erreurs les plus fréquentes ?",
        "À quelle fréquence faut-il relire sa clause bénéficiaire ?",
        "Le testament suffit-il ?",
        "Comment éviter un conflit entre mes proches ?",
    ],
    client_objections=[
        "Ma clause a toujours été comme ça.",
        "Je n'ai pas un patrimoine suffisamment important pour m'en préoccuper.",
        "Mes enfants s'entendront entre eux.",
    ],
    client_fears=[
        "Que mes volontés ne soient pas respectées.",
        "Créer un conflit familial.",
        "Transmettre mon patrimoine aux mauvaises personnes.",
        "Laisser une situation juridiquement complexe à mes proches.",
    ],
    client_goals=[
        "Sécuriser la transmission de son patrimoine.",
        "Protéger ses proches.",
        "Limiter les conflits familiaux.",
        "Mettre en cohérence l'ensemble de sa stratégie patrimoniale.",
    ],
    client_intents=[
        "éviter les erreurs de transmission",
        "sécuriser une assurance-vie",
        "mettre à jour une clause bénéficiaire",
        "préparer sa succession",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_transmission_principe_general",
        "assurance_vie_transmission_hors_succession",
        "assurance_vie_clause_beneficiaire_definition",
        "assurance_vie_clause_beneficiaire_modification",
        "assurance_vie_transmission_article_990_i",
        "assurance_vie_transmission_article_757_b",
        "assurance_vie_transmission_demembrement",
    ],
    prerequisites=[
        "assurance_vie_clause_beneficiaire_definition",
        "assurance_vie_transmission_article_757_b",
        "assurance_vie_transmission_demembrement",
    ],
    next_topics=[],
),

