from v2.models.knowledge_models import Topic

VERSEMENTS_TOPICS: list[Topic] = []

Topic(
    id="assurance_vie_versements_pourquoi_verser",
    title="Pourquoi effectuer des versements sur une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="versements",
    description="Comprendre le rôle des versements dans la construction progressive d'une assurance-vie.",
    objective="Expliquer que les versements permettent d'alimenter le contrat, de construire une épargne et d'adapter progressivement sa stratégie patrimoniale.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "versements",
        "alimenter assurance-vie",
        "épargne",
        "investissement progressif",
        "capital",
        "versements libres",
        "versements programmés",
        "patrimoine",
    ],
    key_points=[
        "Les versements permettent d'alimenter le contrat d'assurance-vie.",
        "Ils peuvent être ponctuels ou réguliers selon la stratégie choisie.",
        "Chaque versement peut être investi sur différents supports.",
        "Les versements participent à la construction progressive d'un capital.",
        "Le rythme des versements doit rester cohérent avec la capacité d'épargne du souscripteur.",
    ],
    examples=[
        "Julie verse 150 € par mois sur son assurance-vie pour préparer un projet à long terme.",
        "Marc effectue un versement ponctuel après avoir reçu une prime professionnelle.",
        "Claire combine un premier versement important avec des versements programmés mensuels.",
    ],
    vocabulary=[
        "versement",
        "versement libre",
        "versement programmé",
        "capital",
        "supports",
        "capacité d'épargne",
        "allocation",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Les versements sont le carburant du contrat : sans eux, l'enveloppe existe, mais elle ne se développe pas.",
    ],
    misconceptions=[
        "Il faut verser beaucoup pour que l'assurance-vie soit utile.",
        "Un contrat ouvert sans gros versement ne sert à rien.",
        "Les versements sont obligatoires une fois le contrat ouvert.",
    ],
    common_mistakes=[
        "Verser sans avoir défini d'objectif patrimonial.",
        "Investir un montant trop élevé au détriment de son épargne de précaution.",
        "Ne jamais réexaminer le rythme des versements.",
    ],
    expert_tips=[
        "Une stratégie de versements réguliers peut aider à lisser les points d'entrée sur les marchés financiers.",
    ],
    attention_points=[
        "Les versements doivent rester compatibles avec la situation financière du souscripteur.",
        "Chaque versement peut modifier l'allocation du contrat et le niveau de risque global.",
    ],
    client_questions=[
        "Pourquoi continuer à verser sur mon assurance-vie ?",
        "Dois-je verser régulièrement ou ponctuellement ?",
        "Puis-je adapter mes versements dans le temps ?",
        "Que devient l'argent versé sur le contrat ?",
    ],
    client_objections=[
        "Je préfère garder mon argent disponible.",
        "Je ne sais pas combien verser.",
        "J'ai peur d'investir au mauvais moment.",
    ],
    client_fears=[
        "Verser trop d'argent.",
        "Perdre en disponibilité.",
        "Faire un mauvais choix d'investissement.",
    ],
    client_goals=[
        "Constituer une épargne progressive.",
        "Préparer un projet futur.",
        "Investir régulièrement.",
        "Diversifier son patrimoine.",
    ],
    client_intents=[
        "alimenter une assurance-vie",
        "épargner régulièrement",
        "investir progressivement",
        "préparer un projet",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "carrousel",
        "article",
    ],
    related_topics=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_ouverture_premier_versement",
        "assurance_vie_versements_libres",
        "assurance_vie_versements_programmes",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
    ],
    next_topics=[
        "assurance_vie_versements_libres",
        "assurance_vie_versements_programmes",
    ],
    
),

Topic(
    id="assurance_vie_versements_libres",
    title="Qu'est-ce qu'un versement libre en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="versements",
    description="Comprendre le fonctionnement des versements libres et les situations dans lesquelles ils peuvent être utilisés.",
    objective="Expliquer qu'un versement libre permet d'alimenter une assurance-vie de manière ponctuelle, sans obligation de régularité.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "versement libre",
        "versement ponctuel",
        "alimenter assurance-vie",
        "investissement",
        "épargne",
        "capital",
        "assurance-vie",
    ],
    key_points=[
        "Un versement libre est un apport ponctuel effectué sur une assurance-vie.",
        "Le souscripteur choisit librement la date et le montant du versement.",
        "Les versements libres peuvent être réalisés à tout moment, sous réserve des conditions du contrat.",
        "Chaque versement peut être réparti entre différents supports d'investissement.",
        "Les versements libres complètent ou remplacent les versements programmés selon les besoins du souscripteur.",
    ],
    examples=[
        "Paul investit une partie de son intéressement dans son assurance-vie grâce à un versement libre.",
        "Claire réalise un versement ponctuel après la vente de son véhicule.",
        "Marc profite d'une rentrée d'argent exceptionnelle pour renforcer son épargne.",
    ],
    vocabulary=[
        "versement libre",
        "versement ponctuel",
        "allocation",
        "fonds euros",
        "unités de compte",
        "arbitrage",
        "capital",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Le versement libre ressemble à un dépôt ponctuel sur un compte d'épargne : vous choisissez quand et combien investir.",
    ],
    misconceptions=[
        "Les versements libres doivent être réalisés à intervalles réguliers.",
        "Il existe une obligation de montant minimum identique pour tous les contrats.",
        "Un versement libre modifie automatiquement les investissements déjà réalisés.",
    ],
    common_mistakes=[
        "Investir une somme dont on pourrait avoir besoin à court terme.",
        "Effectuer un versement sans vérifier sa répartition entre les supports.",
        "Confondre versement libre et arbitrage.",
    ],
    expert_tips=[
        "Les versements libres sont particulièrement adaptés aux rentrées d'argent exceptionnelles, comme une prime, un bonus ou un héritage.",
    ],
    attention_points=[
        "Les montants minimums peuvent varier selon les contrats.",
        "Chaque nouveau versement doit être cohérent avec l'allocation globale du contrat.",
        "Le versement libre ne remet pas en cause l'ancienneté fiscale de l'assurance-vie.",
    ],
    client_questions=[
        "Puis-je verser quand je le souhaite ?",
        "Existe-t-il un montant minimum ?",
        "Dois-je prévenir mon assureur avant chaque versement ?",
        "Puis-je réaliser plusieurs versements libres dans l'année ?",
    ],
    client_objections=[
        "Je préfère investir uniquement lorsque j'ai une rentrée d'argent importante.",
        "Je ne veux pas être engagé à verser tous les mois.",
    ],
    client_fears=[
        "Faire un versement au mauvais moment.",
        "Investir une somme trop importante.",
        "Ne plus pouvoir récupérer mon argent.",
    ],
    client_goals=[
        "Investir ponctuellement.",
        "Profiter d'une rentrée d'argent.",
        "Renforcer progressivement son contrat.",
        "Garder une grande liberté dans son épargne.",
    ],
    client_intents=[
        "faire un versement libre",
        "alimenter son assurance-vie",
        "investir ponctuellement",
        "placer une rentrée d'argent",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "carrousel",
        "article",
    ],
    related_topics=[
        "assurance_vie_versements_pourquoi_verser",
        "assurance_vie_versements_programmes",
        "assurance_vie_versements_modifier",
    ],
    prerequisites=[
        "assurance_vie_versements_pourquoi_verser",
    ],
    next_topics=[
        "assurance_vie_versements_programmes",
        "assurance_vie_versements_modifier",
    ],
),

Topic(
    id="assurance_vie_versements_programmes",
    title="Qu'est-ce qu'un versement programmé en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="versements",
    description="Comprendre le fonctionnement des versements programmés et leur intérêt dans une stratégie d'investissement de long terme.",
    objective="Expliquer qu'un versement programmé permet d'investir automatiquement à intervalles réguliers afin de constituer progressivement un capital.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "versement programmé",
        "investissement automatique",
        "épargne mensuelle",
        "assurance-vie",
        "épargne régulière",
        "DCA",
        "capitalisation",
    ],
    key_points=[
        "Le versement programmé consiste à investir automatiquement un montant défini selon une fréquence choisie.",
        "La périodicité peut être mensuelle, trimestrielle, semestrielle ou annuelle selon le contrat.",
        "Cette solution favorise une discipline d'épargne sans intervention régulière du souscripteur.",
        "Les versements programmés permettent de lisser les points d'entrée sur les marchés financiers.",
        "Le montant et la fréquence des versements restent généralement modifiables.",
    ],
    examples=[
        "Julie investit automatiquement 150 € chaque mois sur son assurance-vie.",
        "Marc programme un versement trimestriel après chaque prime d'activité.",
        "Claire met en place un investissement mensuel afin de préparer sa retraite sur le long terme.",
    ],
    vocabulary=[
        "versement programmé",
        "fréquence",
        "prélèvement automatique",
        "capitalisation",
        "allocation",
        "fonds euros",
        "unités de compte",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Les versements programmés fonctionnent comme un abonnement : l'épargne se constitue automatiquement sans avoir à y penser chaque mois.",
    ],
    misconceptions=[
        "Les versements programmés sont obligatoires.",
        "Le montant choisi est définitif.",
        "Ils empêchent de réaliser des versements libres.",
    ],
    common_mistakes=[
        "Programmer un montant supérieur à sa capacité d'épargne.",
        "Oublier de revoir régulièrement le montant des versements.",
        "Croire que les versements programmés remplacent toute réflexion sur l'allocation du contrat.",
    ],
    expert_tips=[
        "Les versements programmés constituent souvent une excellente méthode pour investir progressivement tout en limitant l'impact émotionnel des variations des marchés.",
    ],
    attention_points=[
        "Le montant doit rester compatible avec le budget du souscripteur.",
        "La répartition des versements entre les supports mérite d'être revue périodiquement.",
        "Les modalités de modification ou de suspension dépendent des conditions du contrat.",
    ],
    client_questions=[
        "Comment fonctionnent les versements programmés ?",
        "Puis-je choisir le montant ?",
        "Puis-je modifier ou arrêter les prélèvements ?",
        "Est-ce obligatoire de verser tous les mois ?",
    ],
    client_objections=[
        "Je préfère garder la main sur chacun de mes investissements.",
        "J'ai peur de ne plus pouvoir suivre les prélèvements.",
    ],
    client_fears=[
        "Oublier un prélèvement.",
        "Investir automatiquement au mauvais moment.",
        "Ne plus pouvoir modifier le montant.",
    ],
    client_goals=[
        "Épargner régulièrement.",
        "Constituer un patrimoine progressivement.",
        "Automatiser son effort d'épargne.",
        "Investir sur le long terme.",
    ],
    client_intents=[
        "mettre en place des versements programmés",
        "épargner automatiquement",
        "investir régulièrement",
        "préparer l'avenir",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "carrousel",
        "article",
    ],
    related_topics=[
        "assurance_vie_versements_pourquoi_verser",
        "assurance_vie_versements_libres",
        "assurance_vie_versements_modifier",
        "assurance_vie_versements_arreter",
    ],
    prerequisites=[
        "assurance_vie_versements_pourquoi_verser",
    ],
    next_topics=[
        "assurance_vie_versements_modifier",
        "assurance_vie_versements_arreter",
    ],
),

Topic(
    id="assurance_vie_versements_modifier",
    title="Peut-on modifier ses versements en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="versements",
    description="Comprendre dans quelles conditions il est possible de modifier le montant, la fréquence ou la répartition de ses versements sur une assurance-vie.",
    objective="Expliquer que les versements d'une assurance-vie sont généralement flexibles et peuvent évoluer en fonction de la situation financière et des objectifs patrimoniaux du souscripteur.",
    difficulty="Débutant",
    priority=8,
    version=1,
    keywords=[
        "modifier versements",
        "changer montant",
        "modifier prélèvement",
        "versements programmés",
        "assurance-vie",
        "épargne",
        "allocation",
    ],
    key_points=[
        "Le montant des versements programmés peut généralement être augmenté ou diminué.",
        "La fréquence des versements est souvent modifiable selon les conditions du contrat.",
        "Il est possible d'adapter son effort d'épargne à l'évolution de sa situation personnelle.",
        "Les nouveaux versements peuvent être investis différemment des versements précédents.",
        "Les modalités de modification dépendent du contrat et de l'assureur.",
    ],
    examples=[
        "Julie augmente ses versements mensuels après une augmentation de salaire.",
        "Marc réduit temporairement ses prélèvements afin de financer un projet immobilier.",
        "Claire modifie l'allocation de ses nouveaux versements en privilégiant davantage les unités de compte.",
    ],
    vocabulary=[
        "versement programmé",
        "fréquence",
        "allocation",
        "supports d'investissement",
        "arbitrage",
        "avenant",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Modifier ses versements revient à ajuster le rythme d'un entraînement sportif : l'objectif reste le même, mais l'intensité évolue selon la situation.",
    ],
    misconceptions=[
        "Le montant choisi lors de la souscription est définitif.",
        "Il est impossible de modifier un versement programmé.",
        "Toute modification entraîne l'ouverture d'un nouveau contrat.",
    ],
    common_mistakes=[
        "Oublier d'adapter ses versements après un changement de revenus.",
        "Modifier ses versements sans revoir son allocation d'investissement.",
        "Confondre modification des versements et arbitrage entre supports.",
    ],
    expert_tips=[
        "Revoir le montant de ses versements une fois par an permet souvent de maintenir une stratégie patrimoniale cohérente avec sa situation financière.",
    ],
    attention_points=[
        "Les délais de prise en compte des modifications varient selon les assureurs.",
        "Certaines modifications peuvent nécessiter une demande écrite ou un avenant au contrat.",
        "Les changements de versements n'ont pas d'incidence sur l'ancienneté fiscale du contrat.",
    ],
    client_questions=[
        "Puis-je modifier mes versements ?",
        "Puis-je augmenter ou diminuer le montant ?",
        "Puis-je changer la fréquence des prélèvements ?",
        "Les modifications sont-elles gratuites ?",
    ],
    client_objections=[
        "Je ne veux pas être engagé sur un montant fixe.",
        "Ma situation financière évolue régulièrement.",
    ],
    client_fears=[
        "Ne plus pouvoir adapter mon contrat.",
        "Faire une erreur en modifiant mes versements.",
        "Perdre les avantages de mon assurance-vie.",
    ],
    client_goals=[
        "Adapter son épargne à ses revenus.",
        "Conserver de la flexibilité.",
        "Faire évoluer sa stratégie patrimoniale.",
    ],
    client_intents=[
        "modifier ses versements",
        "adapter son épargne",
        "augmenter ses versements",
        "diminuer ses versements",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "carrousel",
        "article",
    ],
    related_topics=[
        "assurance_vie_versements_programmes",
        "assurance_vie_versements_arreter",
        "assurance_vie_versements_libres",
    ],
    prerequisites=[
        "assurance_vie_versements_programmes",
    ],
    next_topics=[
        "assurance_vie_versements_arreter",
        "assurance_vie_versements_plafond",
    ],
),

Topic(
    id="assurance_vie_versements_arreter",
    title="Peut-on arrêter ses versements sur une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="versements",
    description="Comprendre s'il est possible d'interrompre les versements sur une assurance-vie et quelles en sont les conséquences.",
    objective="Expliquer que les versements programmés peuvent généralement être suspendus ou arrêtés sans entraîner la clôture du contrat.",
    difficulty="Débutant",
    priority=8,
    version=1,
    keywords=[
        "arrêter versements",
        "suspendre versements",
        "versements programmés",
        "assurance-vie",
        "interrompre épargne",
        "prélèvements",
        "contrat",
    ],
    key_points=[
        "Les versements programmés peuvent généralement être suspendus ou arrêtés à tout moment.",
        "L'arrêt des versements n'entraîne pas la clôture de l'assurance-vie.",
        "Le capital déjà investi reste placé sur le contrat.",
        "Il est souvent possible de reprendre les versements ultérieurement.",
        "Les modalités de suspension ou de reprise dépendent des conditions prévues par le contrat.",
    ],
    examples=[
        "Julie suspend temporairement ses versements pendant la réalisation de travaux dans sa résidence principale.",
        "Marc arrête ses prélèvements mensuels après un changement de situation professionnelle puis les reprend quelques mois plus tard.",
        "Claire conserve son assurance-vie ouverte sans effectuer de nouveaux versements pendant plusieurs années.",
    ],
    vocabulary=[
        "suspension",
        "versements programmés",
        "contrat",
        "capital",
        "prélèvement automatique",
        "reprise des versements",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Arrêter ses versements revient à mettre son épargne en pause : le contrat continue d'exister, mais il n'est plus alimenté.",
    ],
    misconceptions=[
        "Arrêter les versements entraîne automatiquement la fermeture du contrat.",
        "Il est impossible de reprendre les versements après une suspension.",
        "Le capital déjà investi disparaît lorsque les versements sont arrêtés.",
    ],
    common_mistakes=[
        "Clôturer son contrat alors qu'une simple suspension des versements aurait suffi.",
        "Croire qu'il faut maintenir des versements pour conserver l'ancienneté fiscale.",
        "Ne pas vérifier les modalités prévues par le contrat avant de suspendre les prélèvements.",
    ],
    expert_tips=[
        "En cas de difficulté financière temporaire, suspendre les versements est souvent préférable à un rachat précipité du contrat.",
    ],
    attention_points=[
        "Les modalités de suspension et de reprise diffèrent selon les assureurs.",
        "L'arrêt des versements ne remet généralement pas en cause l'ancienneté fiscale du contrat.",
        "Un contrat non alimenté continue néanmoins à supporter les éventuels frais de gestion prévus.",
    ],
    client_questions=[
        "Puis-je arrêter mes versements ?",
        "Mon contrat sera-t-il fermé ?",
        "Puis-je reprendre mes versements plus tard ?",
        "L'ancienneté fiscale est-elle conservée ?",
    ],
    client_objections=[
        "Je ne suis plus certain de pouvoir continuer à épargner.",
        "Je préfère arrêter plutôt que de verser moins.",
    ],
    client_fears=[
        "Perdre les avantages de mon contrat.",
        "Être obligé de continuer à verser.",
        "Voir mon assurance-vie clôturée automatiquement.",
    ],
    client_goals=[
        "Conserver son assurance-vie.",
        "Adapter son effort d'épargne.",
        "Préserver sa flexibilité financière.",
    ],
    client_intents=[
        "arrêter les versements",
        "suspendre les prélèvements",
        "reprendre les versements",
        "adapter son épargne",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "article",
        "carrousel",
    ],
    related_topics=[
        "assurance_vie_versements_programmes",
        "assurance_vie_versements_modifier",
        "assurance_vie_versements_plafond",
    ],
    prerequisites=[
        "assurance_vie_versements_programmes",
    ],
    next_topics=[
        "assurance_vie_versements_plafond",
        "assurance_vie_versements_apres_70_ans",
    ],
),

Topic(
    id="assurance_vie_versements_plafond",
    title="Existe-t-il un plafond de versement sur une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="versements",
    description="Comprendre si les versements sur une assurance-vie sont limités et quelles sont les principales règles applicables.",
    objective="Expliquer qu'il n'existe généralement pas de plafond légal de versement sur une assurance-vie, tout en présentant les limites pratiques, réglementaires et fiscales pouvant s'appliquer.",
    difficulty="Débutant",
    priority=8,
    version=1,
    keywords=[
        "plafond assurance-vie",
        "limite versement",
        "montant maximum",
        "versements",
        "assurance-vie",
        "70 ans",
        "fiscalité",
        "capital",
    ],
    key_points=[
        "Il n'existe pas de plafond légal de versement sur une assurance-vie.",
        "Chaque assureur peut toutefois prévoir des montants minimums ou maximums dans ses conditions contractuelles.",
        "Des versements importants peuvent entraîner des vérifications au titre de la lutte contre le blanchiment et le financement du terrorisme.",
        "Le montant versé peut avoir des conséquences fiscales, notamment en matière de transmission.",
        "L'absence de plafond ne signifie pas qu'il est toujours pertinent de concentrer tout son patrimoine sur une assurance-vie.",
    ],
    examples=[
        "Julie verse 20 000 € après la vente d'un bien immobilier sans rencontrer de limite légale.",
        "Marc réalise un versement de 300 000 € et l'assureur lui demande des justificatifs sur l'origine des fonds.",
        "Claire répartit son patrimoine entre assurance-vie, PEA et immobilier afin de diversifier ses placements.",
    ],
    vocabulary=[
        "plafond",
        "versement",
        "origine des fonds",
        "LCB-FT",
        "transmission",
        "capital",
        "allocation patrimoniale",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
    ],
    analogies=[
        "L'assurance-vie ressemble à un coffre sans limite de capacité, mais chaque dépôt important peut nécessiter de justifier l'origine de ce que l'on y place.",
    ],
    misconceptions=[
        "Une assurance-vie est limitée à un montant maximum.",
        "Les versements sont bloqués après un certain seuil.",
        "Il est impossible d'investir plusieurs centaines de milliers d'euros sur un même contrat.",
    ],
    common_mistakes=[
        "Croire qu'il existe un plafond comparable à celui du Livret A.",
        "Concentrer tout son patrimoine sur une seule enveloppe d'investissement.",
        "Ne pas anticiper les demandes de justificatifs pour des versements importants.",
    ],
    expert_tips=[
        "Lorsqu'un versement important est envisagé, préparer les justificatifs de l'origine des fonds permet souvent de fluidifier les démarches avec l'assureur.",
    ],
    attention_points=[
        "Les contrôles réglementaires augmentent avec le montant des versements.",
        "Les conséquences fiscales doivent être appréciées en tenant compte des objectifs patrimoniaux du souscripteur.",
        "Diversifier son patrimoine reste généralement préférable à une concentration excessive sur une seule enveloppe.",
    ],
    client_questions=[
        "Existe-t-il un montant maximum sur une assurance-vie ?",
        "Puis-je verser 100 000 € ?",
        "Puis-je investir 500 000 € sur un seul contrat ?",
        "Pourquoi l'assureur demande-t-il des justificatifs ?",
    ],
    client_objections=[
        "Je pensais que les versements étaient plafonnés.",
        "Je crains que mon versement soit refusé.",
    ],
    client_fears=[
        "Dépasser une limite réglementaire.",
        "Voir mon versement bloqué.",
        "Être contrôlé par l'assureur.",
    ],
    client_goals=[
        "Investir un capital important.",
        "Comprendre les limites applicables.",
        "Optimiser la gestion de son patrimoine.",
    ],
    client_intents=[
        "faire un gros versement",
        "connaître le plafond",
        "investir un capital",
        "alimenter son assurance-vie",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "carrousel",
        "article",
    ],
    related_topics=[
        "assurance_vie_versements_modifier",
        "assurance_vie_versements_arreter",
        "assurance_vie_versements_apres_70_ans",
    ],
    prerequisites=[
        "assurance_vie_versements_pourquoi_verser",
    ],
    next_topics=[
        "assurance_vie_versements_apres_70_ans",
        "assurance_vie_versements_erreurs",
    ],
),

Topic(
    id="assurance_vie_versements_apres_70_ans",
    title="Peut-on continuer à effectuer des versements après 70 ans ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="versements",
    description="Comprendre les conséquences patrimoniales et fiscales des versements réalisés après 70 ans sur une assurance-vie.",
    objective="Expliquer que les versements restent possibles après 70 ans, mais que leur régime fiscal en matière de transmission diffère de celui des versements effectués avant cet âge.",
    difficulty="Intermédiaire",
    priority=10,
    version=1,
    keywords=[
        "70 ans",
        "versements après 70 ans",
        "transmission",
        "assurance-vie",
        "fiscalité",
        "succession",
        "article 757 B",
        "abattement",
    ],
    key_points=[
        "Il est possible d'effectuer des versements sur une assurance-vie après 70 ans.",
        "Les versements réalisés après 70 ans relèvent d'un régime successoral spécifique.",
        "Les produits générés par ces versements bénéficient d'un traitement distinct des primes versées.",
        "Le choix de poursuivre les versements après 70 ans dépend des objectifs patrimoniaux du souscripteur.",
        "L'âge de 70 ans n'interdit donc pas de continuer à alimenter son contrat.",
    ],
    examples=[
        "Jean, âgé de 72 ans, continue d'effectuer des versements sur son assurance-vie afin d'investir une partie de son épargne disponible.",
        "Marie reçoit un héritage à 75 ans et choisit d'en investir une partie sur son contrat d'assurance-vie après avoir étudié les conséquences successorales.",
        "Un retraité poursuit ses versements mensuels afin de conserver une stratégie d'investissement progressive.",
    ],
    vocabulary=[
        "primes",
        "article 757 B",
        "succession",
        "abattement",
        "capital décès",
        "transmission",
        "bénéficiaire",
    ],
    legal_sources=[
        "CGI art. 757 B",
        "CGI art. 990 I",
        "Code des assurances",
    ],
    analogies=[
        "Après 70 ans, l'assurance-vie continue de fonctionner comme avant, mais certaines règles de transmission changent de 'couloir fiscal'.",
    ],
    misconceptions=[
        "Il est interdit de verser après 70 ans.",
        "Une assurance-vie ne sert plus à rien après 70 ans.",
        "Tous les avantages fiscaux disparaissent après 70 ans.",
    ],
    common_mistakes=[
        "Croire que le contrat devient inutilisable après 70 ans.",
        "Confondre les règles applicables avant et après 70 ans.",
        "Décider d'arrêter les versements uniquement en raison de l'âge sans analyser sa situation patrimoniale.",
    ],
    expert_tips=[
        "La question n'est pas de savoir s'il est possible de verser après 70 ans, mais si ces versements restent cohérents avec les objectifs patrimoniaux et successoraux du souscripteur.",
    ],
    attention_points=[
        "Le régime fiscal applicable dépend notamment de la date des versements.",
        "Les objectifs de transmission doivent être analysés avant d'effectuer des versements importants après 70 ans.",
        "La fiscalité des rachats reste distincte de la fiscalité applicable en cas de décès.",
    ],
    client_questions=[
        "Puis-je encore alimenter mon assurance-vie après 70 ans ?",
        "Est-ce encore intéressant de verser après 70 ans ?",
        "Que change réellement l'âge de 70 ans ?",
        "Les avantages fiscaux disparaissent-ils ?",
    ],
    client_objections=[
        "On m'a dit qu'il ne fallait plus verser après 70 ans.",
        "J'ai peur de perdre les avantages fiscaux.",
    ],
    client_fears=[
        "Faire un versement fiscalement défavorable.",
        "Pénaliser mes héritiers.",
        "Prendre une mauvaise décision patrimoniale.",
    ],
    client_goals=[
        "Continuer à investir.",
        "Préparer la transmission de son patrimoine.",
        "Comprendre les règles fiscales applicables.",
    ],
    client_intents=[
        "verser après 70 ans",
        "préparer sa succession",
        "optimiser la transmission",
        "continuer à investir",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "article",
        "linkedin_post",
    ],
    related_topics=[
        "assurance_vie_versements_plafond",
        "assurance_vie_transmission_fiscalite",
        "assurance_vie_transmission_article_757b",
    ],
    prerequisites=[
        "assurance_vie_versements_plafond",
    ],
    next_topics=[
        "assurance_vie_versements_erreurs",
        "assurance_vie_transmission_fiscalite",
    ],
),

Topic(
    id="assurance_vie_versements_erreurs",
    title="Quelles erreurs éviter lors des versements sur une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="versements",
    description="Identifier les principales erreurs commises lors des versements afin de construire une stratégie d'épargne cohérente et durable.",
    objective="Sensibiliser le souscripteur aux erreurs les plus fréquentes afin d'optimiser l'utilisation de son assurance-vie tout au long de sa vie patrimoniale.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "erreurs assurance-vie",
        "versements",
        "épargne",
        "investissement",
        "allocation",
        "fiscalité",
        "patrimoine",
        "versements programmés",
    ],
    key_points=[
        "Il est préférable d'investir progressivement plutôt que de chercher à anticiper parfaitement les marchés.",
        "Les versements doivent rester compatibles avec la situation financière du souscripteur.",
        "L'assurance-vie ne doit pas remplacer l'épargne de précaution.",
        "Chaque versement mérite une réflexion sur sa répartition entre les supports d'investissement.",
        "Les objectifs patrimoniaux doivent être régulièrement réévalués afin d'adapter les futurs versements.",
    ],
    examples=[
        "Thomas investit l'ensemble de son épargne disponible sur son assurance-vie puis manque de liquidités pour faire face à une dépense imprévue.",
        "Julie conserve les mêmes versements pendant plusieurs années alors que ses revenus ont fortement augmenté.",
        "Marc réalise un versement important sans revoir la répartition entre fonds euros et unités de compte.",
    ],
    vocabulary=[
        "allocation",
        "diversification",
        "versement",
        "fonds euros",
        "unités de compte",
        "épargne de précaution",
        "horizon d'investissement",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Construire une assurance-vie revient à entretenir un jardin : ce sont des gestes réguliers et cohérents qui produisent les meilleurs résultats, pas les actions impulsives.",
    ],
    misconceptions=[
        "Il faut investir tout son capital dès que les marchés baissent.",
        "Une assurance-vie remplace totalement une épargne disponible.",
        "Le montant des versements est plus important que leur régularité.",
    ],
    common_mistakes=[
        "Investir son épargne de précaution sur l'assurance-vie.",
        "Chercher à anticiper les fluctuations des marchés avant chaque versement.",
        "Ne jamais revoir son allocation d'investissement.",
        "Conserver des versements inadaptés après un changement de situation personnelle.",
        "Concentrer tous les versements sur un seul support d'investissement.",
    ],
    expert_tips=[
        "Une stratégie d'investissement régulière, adaptée aux objectifs patrimoniaux et revue périodiquement, est souvent plus efficace qu'une succession de décisions prises sous l'effet des émotions.",
    ],
    attention_points=[
        "La capacité d'épargne peut évoluer au cours de la vie et justifier une adaptation des versements.",
        "Les marchés financiers connaissent des fluctuations normales qui ne doivent pas conduire à modifier systématiquement sa stratégie.",
        "La diversification reste un principe essentiel de gestion patrimoniale.",
    ],
    client_questions=[
        "Quelles erreurs faut-il éviter ?",
        "Dois-je investir tout mon capital d'un seul coup ?",
        "Puis-je utiliser toute mon épargne pour alimenter mon assurance-vie ?",
        "Faut-il modifier mes versements lorsque les marchés baissent ?",
    ],
    client_objections=[
        "J'attends le bon moment pour investir.",
        "Je préfère tout investir immédiatement.",
    ],
    client_fears=[
        "Investir au mauvais moment.",
        "Faire une erreur irréversible.",
        "Perdre une partie de mon capital.",
    ],
    client_goals=[
        "Construire une épargne durable.",
        "Éviter les erreurs classiques.",
        "Investir avec méthode.",
        "Faire évoluer son patrimoine sereinement.",
    ],
    client_intents=[
        "éviter les erreurs",
        "mieux investir",
        "alimenter son assurance-vie",
        "optimiser son épargne",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_versements_pourquoi_verser",
        "assurance_vie_versements_libres",
        "assurance_vie_versements_programmes",
        "assurance_vie_versements_modifier",
        "assurance_vie_versements_arreter",
        "assurance_vie_versements_plafond",
        "assurance_vie_versements_apres_70_ans",
    ],
    prerequisites=[
        "assurance_vie_versements_pourquoi_verser",
    ],
    next_topics=[
        "assurance_vie_supports_fonds_euros",
        "assurance_vie_supports_unites_de_compte",
    ],
),

