SUBJECT_BANK = {
    "Fiscalité du patrimoine": {
        "Impôt sur le revenu": [
            "barème progressif",
            "quotient familial",
            "revenus fonciers",
            "revenus mobiliers",
            "déficit foncier",
            "crédits d'impôt",
            "réductions d'impôt",
        ],
        "Fiscalité de l'épargne": [
            "flat tax",
            "prélèvements sociaux",
            "PEA",
            "assurance-vie",
            "compte-titres",
            "livrets réglementés",
            "capitalisation",
        ],
        "IFI": [
            "assiette taxable IFI",
            "résidence principale et IFI",
            "dettes déductibles IFI",
            "biens professionnels",
            "SCI et IFI",
            "démembrement et IFI",
        ],
        "Plus-values": [
            "plus-value immobilière",
            "plus-value mobilière",
            "abattement pour durée de détention",
            "résidence principale",
            "cession de titres",
            "cession d'entreprise",
        ],
    },

    "Transmission": {
        "Successions": [
            "réserve héréditaire",
            "quotité disponible",
            "ordre des héritiers",
            "droits de succession",
            "indivision successorale",
            "acceptation de succession",
            "renonciation à succession",
        ],
        "Donations": [
            "donation simple",
            "donation-partage",
            "présent d'usage",
            "don manuel",
            "pacte adjoint",
            "rapport civil",
            "réduction des libéralités",
        ],
        "Démembrement": [
            "usufruit",
            "nue-propriété",
            "quasi-usufruit",
            "donation avec réserve d'usufruit",
            "cession de nue-propriété",
            "convention de quasi-usufruit",
        ],
        "Assurance-vie transmission": [
            "clause bénéficiaire",
            "bénéficiaire acceptant",
            "versements avant 70 ans",
            "versements après 70 ans",
            "assurance-vie hors succession",
            "clause démembrée",
        ],
    },

    "Immobilier patrimonial": {
        "Investissement locatif": [
            "location nue",
            "location meublée",
            "LMNP",
            "LMP",
            "déficit foncier",
            "amortissement LMNP",
            "régime réel",
            "micro-foncier",
        ],
        "SCI": [
            "SCI familiale",
            "SCI à l'IR",
            "SCI à l'IS",
            "cession de parts de SCI",
            "compte courant d'associé",
            "démembrement de parts sociales",
            "transmission via SCI",
        ],
        "SCPI": [
            "SCPI de rendement",
            "SCPI fiscales",
            "SCPI en assurance-vie",
            "liquidité des parts",
            "fiscalité des revenus de SCPI",
            "SCPI et IFI",
        ],
    },

    "Chef d'entreprise": {
        "Structuration": [
            "holding patrimoniale",
            "holding animatrice",
            "apport-cession",
            "pacte Dutreil",
            "régime mère-fille",
            "intégration fiscale",
        ],
        "Cession": [
            "cession de titres",
            "plus-value de cession",
            "earn-out",
            "garantie d'actif et de passif",
            "réinvestissement post-cession",
            "management package",
        ],
        "Protection du dirigeant": [
            "rémunération du dirigeant",
            "dividendes",
            "statut TNS",
            "mandataire social",
            "prévoyance du dirigeant",
            "retraite du dirigeant",
        ],
    },

    "Produits financiers": {
        "Assurance-vie": [
            "fonds euros",
            "unités de compte",
            "arbitrage",
            "rachat partiel",
            "rachat total",
            "avance",
            "clause bénéficiaire",
            "fiscalité des rachats",
        ],
        "Retraite": [
            "PER individuel",
            "PER collectif",
            "sortie en capital",
            "sortie en rente",
            "déblocage anticipé",
            "déduction fiscale",
            "fiscalité à la sortie",
        ],
        "Private equity": [
            "FCPR",
            "FCPI",
            "FIP",
            "fonds evergreen",
            "illiquidité",
            "courbe en J",
            "risque de perte en capital",
        ],
        "Produits structurés": [
            "autocall",
            "barrière de protection",
            "coupon conditionnel",
            "sous-jacent",
            "risque de marché",
            "risque émetteur",
        ],
    },

    "Conformité et conseil": {
        "Approche client": [
            "profil de risque",
            "horizon de placement",
            "objectif patrimonial",
            "capacité de perte",
            "adéquation du conseil",
            "lettre de mission",
        ],
        "Réglementation": [
            "MIF 2",
            "DDA",
            "LCB-FT",
            "devoir de conseil",
            "conflits d'intérêts",
            "document d'entrée en relation",
        ],
    },
}
