from v2.models.knowledge_models import Topic

FISCALITE_TOPICS: list[Topic] = []

Topic(
    id="assurance_vie_fiscalite_principe_general",
    title="Comment fonctionne la fiscalité de l'assurance-vie ?",
    pillar="optimiser",
    family="assurance_vie",
    chapter="fiscalite",
    description="Comprendre les grands principes de la fiscalité de l'assurance-vie et les événements qui déclenchent réellement une imposition.",
    objective="Expliquer que l'assurance-vie bénéficie d'une fiscalité spécifique fondée sur le principe de l'imposition différée : tant qu'aucun rachat n'est effectué, les gains ne sont généralement pas imposés.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "fiscalité assurance-vie",
        "imposition",
        "rachat",
        "plus-value",
        "capitalisation",
        "prélèvements sociaux",
        "PFU",
        "8 ans",
        "optimisation fiscale",
    ],
    key_points=[
        "Les gains générés par une assurance-vie ne sont généralement pas imposés tant qu'aucun rachat n'est réalisé.",
        "La fiscalité intervient principalement lors d'un rachat total ou partiel.",
        "Seule la part correspondant aux gains est susceptible d'être imposée.",
        "Le régime fiscal dépend notamment de la date des versements, de l'ancienneté du contrat et du mode d'imposition choisi.",
        "La fiscalité en cas de décès obéit à des règles spécifiques qui relèvent de la transmission patrimoniale.",
    ],
    examples=[
        "Julie, 35 ans, possède une assurance-vie depuis six ans. Son contrat progresse régulièrement mais elle ne réalise aucun retrait. Malgré les plus-values accumulées, elle n'est généralement pas imposée tant qu'elle laisse son épargne investie.",

        "Marc, 49 ans, souhaite financer les études de sa fille. Il effectue un rachat partiel sur son contrat. Il découvre que seule la fraction correspondant aux gains est prise en compte pour la fiscalité.",

        "Sophie, 62 ans, hésite entre clôturer son assurance-vie et effectuer un simple rachat partiel. Après avoir compris les règles fiscales, elle adapte sa stratégie afin de conserver les avantages liés à son contrat.",
    ],
    vocabulary=[
        "rachat",
        "rachat partiel",
        "rachat total",
        "plus-value",
        "capitalisation",
        "PFU",
        "barème progressif",
        "prélèvements sociaux",
        "ancienneté fiscale",
    ],
    legal_sources=[
        "Code général des impôts",
        "BOFiP - Assurance-vie",
        "Code des assurances",
    ],
    analogies=[
        "L'assurance-vie fonctionne comme un arbre fruitier : tant que vous laissez les fruits sur l'arbre, il n'y a généralement pas d'imposition. C'est lorsque vous les récoltez, par un rachat, que les règles fiscales entrent en jeu.",
    ],
    misconceptions=[
        "Les intérêts sont imposés chaque année.",
        "Toute somme retirée est imposable.",
        "Une assurance-vie est exonérée de toute fiscalité.",
        "La fiscalité est identique quel que soit l'âge du contrat.",
    ],
    common_mistakes=[
        "Croire que la totalité d'un rachat est imposable.",
        "Clôturer son contrat alors qu'un simple rachat partiel aurait pu suffire.",
        "Confondre fiscalité des rachats et fiscalité en cas de décès.",
        "Prendre une décision uniquement pour des raisons fiscales sans tenir compte des objectifs patrimoniaux.",
    ],
    expert_tips=[
        "L'assurance-vie est avant tout une enveloppe de capitalisation. Sa fiscalité prend tout son sens lorsqu'elle est utilisée dans une stratégie de long terme plutôt que comme un simple placement de court terme.",
    ],
    attention_points=[
        "La fiscalité dépend de plusieurs paramètres : ancienneté du contrat, date des versements, montant des gains et option fiscale retenue.",
        "Les prélèvements sociaux et l'impôt sur le revenu répondent à des mécanismes distincts.",
        "La fiscalité applicable en cas de décès relève de règles spécifiques qui seront étudiées dans le chapitre Transmission.",
    ],
    client_questions=[
        "Quand suis-je imposé sur mon assurance-vie ?",
        "Dois-je déclarer les intérêts chaque année ?",
        "Pourquoi parle-t-on toujours des huit ans ?",
        "Toute somme retirée est-elle imposable ?",
    ],
    client_objections=[
        "Je pensais que l'assurance-vie était totalement défiscalisée.",
        "J'ai peur qu'un retrait déclenche une forte imposition.",
        "La fiscalité me paraît trop complexe.",
    ],
    client_fears=[
        "Payer trop d'impôts.",
        "Faire un mauvais choix fiscal.",
        "Perdre les avantages de mon contrat.",
    ],
    client_goals=[
        "Comprendre la fiscalité.",
        "Optimiser ses futurs retraits.",
        "Préserver les avantages de son contrat.",
        "Préparer ses projets sans mauvaise surprise fiscale.",
    ],
    client_intents=[
        "comprendre la fiscalité de l'assurance-vie",
        "savoir quand on est imposé",
        "optimiser un rachat",
        "préparer un retrait",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_plus_value",
        "assurance_vie_fiscalite_8_ans",
        "assurance_vie_fiscalite_prelevements_sociaux",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_versements_pourquoi_verser",
    ],
    next_topics=[
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_plus_value",
    ],
),

Topic(
    id="assurance_vie_fiscalite_rachat",
    title="Quelle est la fiscalité lors d'un rachat sur une assurance-vie ?",
    pillar="optimiser",
    family="assurance_vie",
    chapter="fiscalite",
    description="Comprendre comment est imposé un rachat partiel ou total sur une assurance-vie et identifier les éléments qui influencent cette fiscalité.",
    objective="Expliquer que la fiscalité d'un rachat ne porte pas sur le capital investi, mais uniquement sur la quote-part des gains comprise dans le retrait.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "rachat",
        "rachat partiel",
        "rachat total",
        "fiscalité",
        "assurance-vie",
        "plus-value",
        "PFU",
        "barème progressif",
        "impôt",
    ],
    key_points=[
        "Un rachat correspond à un retrait d'argent effectué sur un contrat d'assurance-vie.",
        "Le rachat peut être partiel ou total.",
        "Seule la part correspondant aux gains est susceptible d'être imposée.",
        "Le capital initialement versé n'est généralement pas soumis à l'impôt lors du rachat.",
        "La fiscalité dépend notamment de l'ancienneté du contrat, de la date des versements et de l'option fiscale retenue.",
    ],
    examples=[
        "Julie, 42 ans, retire 20 000 € de son assurance-vie pour financer des travaux. Sur cette somme, seuls 3 000 € correspondent à des gains. C'est uniquement cette fraction qui est susceptible d'être imposée.",

        "Marc, 57 ans, effectue un rachat partiel afin d'aider son fils à acheter sa résidence principale. Il conserve le reste de son contrat, qui continue de bénéficier de son ancienneté fiscale.",

        "Sophie, 66 ans, hésite entre un rachat total et plusieurs rachats partiels étalés dans le temps. Elle découvre que cette décision peut avoir des conséquences fiscales différentes selon sa situation.",
    ],
    vocabulary=[
        "rachat",
        "rachat partiel",
        "rachat total",
        "capital",
        "plus-value",
        "assiette imposable",
        "PFU",
        "barème progressif",
    ],
    legal_sources=[
        "Code général des impôts",
        "BOFiP - Assurance-vie",
        "Code des assurances",
    ],
    analogies=[
        "Imaginez un gâteau composé de pâte (le capital) et de chocolat (les gains). Lors d'un rachat, vous retirez une part des deux. Seule la partie 'chocolat' est concernée par la fiscalité.",
    ],
    misconceptions=[
        "Tout retrait est imposé.",
        "Le capital investi est taxé lors du rachat.",
        "Un rachat entraîne automatiquement la fermeture du contrat.",
        "Il faut attendre huit ans pour pouvoir effectuer un retrait.",
    ],
    common_mistakes=[
        "Croire que la totalité du retrait est imposable.",
        "Confondre rachat partiel et clôture du contrat.",
        "Effectuer un rachat sans mesurer ses conséquences fiscales.",
        "Clôturer un contrat ancien alors qu'un simple rachat partiel aurait pu répondre au besoin.",
    ],
    expert_tips=[
        "Le rachat partiel est souvent un outil de gestion patrimoniale plus souple que le rachat total. Il permet de conserver l'ancienneté fiscale du contrat tout en répondant à un besoin ponctuel de liquidités.",
    ],
    attention_points=[
        "La fiscalité varie selon l'ancienneté du contrat et la date des versements.",
        "Les prélèvements sociaux s'ajoutent, le cas échéant, à l'imposition des gains.",
        "Chaque rachat doit être analysé dans le contexte patrimonial global du souscripteur.",
    ],
    client_questions=[
        "Puis-je retirer de l'argent quand je veux ?",
        "Serai-je imposé sur tout ce que je retire ?",
        "Quelle différence entre un rachat partiel et un rachat total ?",
        "Mon contrat est-il fermé après un retrait ?",
    ],
    client_objections=[
        "Je préfère ne rien retirer par peur des impôts.",
        "J'ai entendu dire qu'un retrait faisait perdre tous les avantages de l'assurance-vie.",
        "La fiscalité des rachats me semble incompréhensible.",
    ],
    client_fears=[
        "Payer trop d'impôts.",
        "Faire disparaître les avantages de mon contrat.",
        "Retirer mon argent au mauvais moment.",
    ],
    client_goals=[
        "Financer un projet.",
        "Retirer une partie de son épargne.",
        "Optimiser la fiscalité de ses retraits.",
        "Conserver les avantages de son assurance-vie.",
    ],
    client_intents=[
        "faire un rachat",
        "retirer de l'argent",
        "comprendre la fiscalité d'un retrait",
        "optimiser un rachat partiel",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fiscalite_principe_general",
        "assurance_vie_fiscalite_plus_value",
        "assurance_vie_fiscalite_8_ans",
        "assurance_vie_fiscalite_abattement",
    ],
    prerequisites=[
        "assurance_vie_fiscalite_principe_general",
    ],
    next_topics=[
        "assurance_vie_fiscalite_plus_value",
        "assurance_vie_fiscalite_8_ans",
    ],
),

Topic(
    id="assurance_vie_fiscalite_plus_value",
    title="Est-on imposé sur tout l'argent retiré d'une assurance-vie ?",
    pillar="optimiser",
    family="assurance_vie",
    chapter="fiscalite",
    description="Comprendre pourquoi la fiscalité d'un rachat porte uniquement sur les gains et non sur l'intégralité des sommes retirées.",
    objective="Expliquer le mécanisme de répartition entre capital et plus-value lors d'un rachat afin de corriger l'une des idées reçues les plus fréquentes sur l'assurance-vie.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "plus-value",
        "rachat",
        "capital",
        "gains",
        "assurance-vie",
        "fiscalité",
        "imposition",
        "quote-part",
    ],
    key_points=[
        "Lors d'un rachat, l'argent retiré est composé d'une part de capital et d'une part de gains.",
        "Le capital correspondant aux versements n'est généralement pas imposé.",
        "Seule la quote-part des gains est susceptible d'être soumise à l'impôt et aux prélèvements sociaux.",
        "Cette répartition est calculée automatiquement selon une formule légale.",
        "Comprendre ce mécanisme permet d'anticiper plus efficacement la fiscalité d'un retrait.",
    ],
    examples=[
        "Julie a versé 80 000 € sur son assurance-vie. Son contrat vaut désormais 100 000 €. Elle effectue un rachat de 20 000 €. Ce retrait comprend une part de capital et une part de gains : seule cette dernière est potentiellement imposable.",

        "Marc souhaite financer les études de sa fille grâce à un rachat partiel. Pensant être imposé sur l'intégralité des 30 000 € retirés, il découvre que seule une faible fraction correspondant aux gains entre dans le calcul de l'impôt.",

        "Sophie réalise plusieurs rachats au fil des années afin de compléter ses revenus. Chaque retrait comprend automatiquement une quote-part de capital et une quote-part de plus-value calculées par l'assureur.",
    ],
    vocabulary=[
        "plus-value",
        "capital",
        "gains",
        "quote-part",
        "rachat",
        "assiette imposable",
        "versements",
        "valorisation",
    ],
    legal_sources=[
        "Code général des impôts",
        "BOFiP - Assurance-vie",
        "Code des assurances",
    ],
    analogies=[
        "Imaginez une bouteille contenant de l'eau (le capital) et du sirop (les gains). À chaque verre servi, vous récupérez automatiquement un mélange des deux. Seule la partie correspondant au sirop est concernée par la fiscalité.",
    ],
    misconceptions=[
        "Je paie des impôts sur tout ce que je retire.",
        "Le capital investi est fiscalisé lors d'un rachat.",
        "Il faut retirer uniquement les gains.",
        "Je peux choisir de retirer uniquement mon capital.",
    ],
    common_mistakes=[
        "Confondre montant retiré et montant imposable.",
        "Reporter un projet par crainte d'une fiscalité surestimée.",
        "Calculer soi-même une imposition sans tenir compte de la quote-part réelle des gains.",
        "Croire qu'un rachat partiel fait perdre l'ancienneté fiscale du contrat.",
    ],
    expert_tips=[
        "La compréhension de la quote-part de gains est indispensable pour optimiser les rachats et éviter de prendre des décisions fondées sur une mauvaise perception de la fiscalité.",
    ],
    attention_points=[
        "La quote-part imposable dépend de la valeur du contrat au moment du rachat.",
        "L'assureur calcule automatiquement la répartition entre capital et gains.",
        "La fiscalité applicable dépend ensuite de l'ancienneté du contrat et du régime d'imposition choisi.",
    ],
    client_questions=[
        "Suis-je imposé sur tout ce que je retire ?",
        "Comment est calculée la plus-value imposable ?",
        "Puis-je retirer uniquement mon capital ?",
        "Pourquoi mon assureur parle-t-il d'une quote-part de gains ?",
    ],
    client_objections=[
        "Je pensais que retirer 20 000 € signifiait être imposé sur 20 000 €.",
        "Je préfère attendre pour éviter les impôts.",
        "Le calcul me paraît trop compliqué.",
    ],
    client_fears=[
        "Payer beaucoup plus d'impôts que prévu.",
        "Faire un retrait fiscalement défavorable.",
        "Ne pas comprendre le calcul réalisé par l'assureur.",
    ],
    client_goals=[
        "Comprendre la fiscalité réelle d'un retrait.",
        "Optimiser ses rachats.",
        "Financer un projet sans mauvaise surprise fiscale.",
    ],
    client_intents=[
        "calculer la fiscalité d'un rachat",
        "comprendre la plus-value imposable",
        "retirer de l'argent",
        "optimiser un retrait",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fiscalite_principe_general",
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_8_ans",
        "assurance_vie_fiscalite_abattement",
    ],
    prerequisites=[
        "assurance_vie_fiscalite_rachat",
    ],
    next_topics=[
        "assurance_vie_fiscalite_8_ans",
        "assurance_vie_fiscalite_abattement",
    ],
),

Topic(
    id="assurance_vie_fiscalite_8_ans",
    title="Pourquoi parle-t-on toujours des 8 ans en assurance-vie ?",
    pillar="optimiser",
    family="assurance_vie",
    chapter="fiscalite",
    description="Comprendre pourquoi le seuil des 8 ans est une étape importante dans la fiscalité de l'assurance-vie et quelles en sont les conséquences concrètes.",
    objective="Expliquer que les 8 ans ne rendent pas les retraits exonérés d'impôt mais permettent, sous certaines conditions, de bénéficier d'un régime fiscal plus favorable.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "8 ans",
        "ancienneté fiscale",
        "assurance-vie",
        "abattement",
        "rachat",
        "fiscalité",
        "PFU",
        "plus-value",
    ],
    key_points=[
        "L'ancienneté fiscale d'un contrat d'assurance-vie est un élément déterminant de sa fiscalité.",
        "Le cap des 8 ans ouvre l'accès à un régime fiscal généralement plus favorable lors des rachats.",
        "Un contrat de plus de 8 ans n'est pas exonéré d'impôt : seules certaines règles deviennent plus avantageuses.",
        "L'ancienneté continue à courir tant que le contrat n'est pas clôturé.",
        "Conserver un contrat ancien peut constituer un véritable avantage patrimonial.",
    ],
    examples=[
        "Julie, 45 ans, possède une assurance-vie ouverte depuis neuf ans. Elle souhaite financer des travaux. Avant d'effectuer son rachat, elle découvre que son contrat bénéficie désormais d'un régime fiscal plus favorable que s'il avait été ouvert récemment.",

        "Marc, 38 ans, envisage de clôturer son contrat de sept ans pour en ouvrir un nouveau plus performant. Après analyse, il comprend qu'il est souvent préférable de conserver l'ancien contrat afin de préserver son ancienneté fiscale.",

        "Sophie, 61 ans, possède plusieurs contrats d'assurance-vie. Lorsqu'elle réalise un retrait, elle privilégie celui qui a dépassé les huit ans afin d'optimiser sa fiscalité.",
    ],
    vocabulary=[
        "ancienneté fiscale",
        "8 ans",
        "rachat",
        "abattement",
        "plus-value",
        "PFU",
        "capitalisation",
    ],
    legal_sources=[
        "Code général des impôts",
        "BOFiP - Assurance-vie",
        "Code des assurances",
    ],
    analogies=[
        "L'assurance-vie ressemble à un bon vin : avec le temps, certaines caractéristiques deviennent plus intéressantes. Les 8 ans ne changent pas le contrat, mais ils améliorent son traitement fiscal.",
    ],
    misconceptions=[
        "Après 8 ans, il n'y a plus d'impôt.",
        "Il est interdit de retirer de l'argent avant 8 ans.",
        "Les huit ans bloquent le contrat.",
        "Tous les avantages apparaissent automatiquement après 8 ans.",
    ],
    common_mistakes=[
        "Attendre huit ans avant d'effectuer un retrait par peur d'être lourdement imposé.",
        "Clôturer un contrat ancien sans mesurer la perte de son ancienneté fiscale.",
        "Croire que le simple passage des huit ans supprime toute fiscalité.",
        "Ouvrir un nouveau contrat alors qu'il aurait été possible de conserver l'ancien.",
    ],
    expert_tips=[
        "L'ancienneté fiscale est un actif patrimonial à part entière. Avant de clôturer un contrat, il est souvent pertinent d'évaluer la valeur de cette ancienneté par rapport aux avantages du nouveau contrat envisagé.",
    ],
    attention_points=[
        "Les huit ans constituent un seuil fiscal, mais ne garantissent aucune exonération totale.",
        "Les règles diffèrent selon la date des versements et le régime fiscal applicable.",
        "L'ancienneté fiscale est conservée tant que le contrat reste ouvert.",
    ],
    client_questions=[
        "Pourquoi tout le monde parle des huit ans ?",
        "Puis-je retirer de l'argent avant huit ans ?",
        "Suis-je exonéré d'impôt après huit ans ?",
        "Dois-je conserver mon ancien contrat ?",
    ],
    client_objections=[
        "Je pensais que mon argent était bloqué pendant huit ans.",
        "Je préfère fermer mon ancien contrat pour repartir sur un nouveau.",
        "Les huit ans me semblent compliqués à comprendre.",
    ],
    client_fears=[
        "Perdre les avantages fiscaux.",
        "Fermer un contrat trop tôt.",
        "Prendre une mauvaise décision patrimoniale.",
    ],
    client_goals=[
        "Comprendre l'intérêt des huit ans.",
        "Optimiser la fiscalité de ses retraits.",
        "Préserver l'ancienneté de son contrat.",
    ],
    client_intents=[
        "comprendre les 8 ans",
        "optimiser un rachat",
        "conserver son contrat",
        "préparer un retrait",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fiscalite_principe_general",
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_plus_value",
        "assurance_vie_fiscalite_abattement",
        "assurance_vie_fiscalite_pfu",
    ],
    prerequisites=[
        "assurance_vie_fiscalite_principe_general",
        "assurance_vie_fiscalite_rachat",
    ],
    next_topics=[
        "assurance_vie_fiscalite_abattement",
        "assurance_vie_fiscalite_prelevements_sociaux",
    ],
),

Topic(
    id="assurance_vie_fiscalite_abattement",
    title="Comment fonctionne l'abattement après 8 ans en assurance-vie ?",
    pillar="optimiser",
    family="assurance_vie",
    chapter="fiscalite",
    description="Comprendre le fonctionnement de l'abattement annuel applicable aux gains lors des rachats effectués sur une assurance-vie de plus de huit ans.",
    objective="Expliquer que l'abattement annuel s'applique uniquement à la part des gains comprise dans les rachats et qu'il constitue l'un des principaux avantages fiscaux de l'assurance-vie.",
    difficulty="Intermédiaire",
    priority=10,
    version=1,
    keywords=[
        "abattement",
        "8 ans",
        "rachat",
        "plus-value",
        "assurance-vie",
        "fiscalité",
        "gains",
        "optimisation",
    ],
    key_points=[
        "Après huit ans, les gains compris dans les rachats peuvent bénéficier d'un abattement annuel sous certaines conditions.",
        "L'abattement ne s'applique jamais au capital investi, mais uniquement à la part correspondant aux gains.",
        "L'abattement est renouvelé chaque année.",
        "Lorsque les gains retirés dépassent l'abattement disponible, seule la fraction excédentaire est susceptible d'être imposée.",
        "Cet avantage fiscal peut être intégré dans une stratégie de rachats progressifs sur plusieurs années.",
    ],
    examples=[
        "Julie, 63 ans, possède une assurance-vie ouverte depuis douze ans. Chaque année, elle effectue un rachat partiel dont les gains restent inférieurs au montant de l'abattement applicable. Cette stratégie lui permet de compléter ses revenus tout en optimisant sa fiscalité.",

        "Marc, 68 ans, souhaite financer plusieurs projets. Plutôt que d'effectuer un rachat important en une seule fois, il envisage d'étaler ses retraits sur plusieurs années afin de tirer parti de l'abattement annuel.",

        "Sophie, 59 ans, découvre que l'abattement porte uniquement sur la part des gains comprise dans son retrait. Elle réalise alors que le montant réellement imposable est bien inférieur à ce qu'elle imaginait.",
    ],
    vocabulary=[
        "abattement",
        "gains",
        "plus-value",
        "rachat",
        "ancienneté fiscale",
        "assiette imposable",
        "capital",
        "quote-part",
    ],
    legal_sources=[
        "Code général des impôts",
        "BOFiP - Assurance-vie",
    ],
    analogies=[
        "L'abattement fonctionne comme un coupon de réduction renouvelé chaque année : tant que les gains retirés restent dans cette limite, ils bénéficient d'un traitement fiscal plus favorable.",
    ],
    misconceptions=[
        "L'abattement s'applique à tout le retrait.",
        "Après huit ans, tous les retraits deviennent exonérés d'impôt.",
        "L'abattement ne peut être utilisé qu'une seule fois.",
        "Le capital bénéficie également de l'abattement.",
    ],
    common_mistakes=[
        "Croire que l'abattement porte sur le montant total du rachat.",
        "Effectuer un retrait important sans tenir compte du renouvellement annuel de l'abattement.",
        "Confondre abattement fiscal et exonération totale.",
        "Ignorer que seuls les gains sont concernés.",
    ],
    expert_tips=[
        "L'abattement annuel est souvent un excellent outil de pilotage des retraits. Dans de nombreuses situations, des rachats progressifs permettent d'optimiser durablement la fiscalité d'une assurance-vie.",
    ],
    attention_points=[
        "Le montant de l'abattement est fixé par la réglementation et peut évoluer.",
        "Il s'applique uniquement aux contrats ayant atteint l'ancienneté requise.",
        "L'abattement concerne exclusivement les gains compris dans les rachats.",
    ],
    client_questions=[
        "À quoi sert l'abattement ?",
        "L'abattement s'applique-t-il sur tout mon retrait ?",
        "Puis-je utiliser cet avantage tous les ans ?",
        "Comment optimiser mes retraits grâce à l'abattement ?",
    ],
    client_objections=[
        "Je pensais que tout devenait exonéré après huit ans.",
        "Le mécanisme me paraît compliqué.",
        "Je ne comprends pas comment calculer les gains concernés.",
    ],
    client_fears=[
        "Ne pas profiter de l'avantage fiscal.",
        "Retirer trop d'argent la même année.",
        "Payer plus d'impôts que nécessaire.",
    ],
    client_goals=[
        "Optimiser la fiscalité de ses retraits.",
        "Compléter ses revenus.",
        "Préserver les avantages fiscaux de son contrat.",
        "Planifier ses rachats dans le temps.",
    ],
    client_intents=[
        "comprendre l'abattement",
        "optimiser un rachat",
        "réduire l'imposition",
        "préparer des retraits",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fiscalite_8_ans",
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_plus_value",
        "assurance_vie_fiscalite_pfu",
    ],
    prerequisites=[
        "assurance_vie_fiscalite_8_ans",
    ],
    next_topics=[
        "assurance_vie_fiscalite_prelevements_sociaux",
        "assurance_vie_fiscalite_pfu",
    ],
),

Topic(
    id="assurance_vie_fiscalite_prelevements_sociaux",
    title="Que sont les prélèvements sociaux en assurance-vie ?",
    pillar="optimiser",
    family="assurance_vie",
    chapter="fiscalite",
    description="Comprendre le fonctionnement des prélèvements sociaux applicables aux gains d'une assurance-vie et leur articulation avec l'impôt sur le revenu.",
    objective="Expliquer que les prélèvements sociaux constituent une imposition distincte de l'impôt sur le revenu et qu'ils s'appliquent aux gains selon des règles spécifiques.",
    difficulty="Intermédiaire",
    priority=9,
    version=1,
    keywords=[
        "prélèvements sociaux",
        "CSG",
        "CRDS",
        "assurance-vie",
        "gains",
        "rachat",
        "fiscalité",
        "impôt",
    ],
    key_points=[
        "Les prélèvements sociaux sont distincts de l'impôt sur le revenu.",
        "Ils s'appliquent uniquement à la part des gains et non au capital investi.",
        "Selon les supports détenus, leur mode de perception peut différer.",
        "Ils peuvent être dus même lorsqu'aucun impôt sur le revenu n'est finalement payé.",
        "Comprendre cette distinction permet d'anticiper plus précisément le coût fiscal d'un rachat.",
    ],
    examples=[
        "Julie, 64 ans, effectue un rachat sur son assurance-vie. Grâce à l'abattement applicable, elle n'est finalement pas imposée à l'impôt sur le revenu. En revanche, les prélèvements sociaux restent dus sur la part des gains concernée.",

        "Marc, 47 ans, pensait que l'absence d'impôt signifiait l'absence totale de fiscalité. Il découvre que les prélèvements sociaux constituent un mécanisme distinct qui peut continuer à s'appliquer.",

        "Sophie, 59 ans, compare deux stratégies de retrait. Elle comprend que le coût global dépend non seulement de l'impôt sur le revenu, mais également des prélèvements sociaux applicables aux gains retirés.",
    ],
    vocabulary=[
        "prélèvements sociaux",
        "CSG",
        "CRDS",
        "gains",
        "capital",
        "rachat",
        "assiette fiscale",
        "impôt sur le revenu",
    ],
    legal_sources=[
        "Code de la sécurité sociale",
        "Code général des impôts",
        "BOFiP - Assurance-vie",
    ],
    analogies=[
        "Imaginez deux caisses différentes au moment de payer : l'une correspond à l'impôt sur le revenu, l'autre aux prélèvements sociaux. Même si la première est vide grâce à un avantage fiscal, la seconde peut encore être due.",
    ],
    misconceptions=[
        "Les prélèvements sociaux sont le même impôt que le PFU.",
        "Si je ne paie pas d'impôt sur le revenu, je ne paie rien.",
        "Les prélèvements sociaux s'appliquent au capital retiré.",
        "Ils concernent uniquement les gros patrimoines.",
    ],
    common_mistakes=[
        "Confondre prélèvements sociaux et impôt sur le revenu.",
        "Calculer la fiscalité sans tenir compte des prélèvements sociaux.",
        "Croire que l'abattement après huit ans supprime toute fiscalité.",
        "Sous-estimer le coût fiscal global d'un rachat.",
    ],
    expert_tips=[
        "Dans une stratégie patrimoniale, il est essentiel d'analyser séparément l'impôt sur le revenu et les prélèvements sociaux. Cette distinction permet d'estimer beaucoup plus précisément le coût réel d'un retrait.",
    ],
    attention_points=[
        "Les règles de perception peuvent varier selon les supports détenus dans le contrat.",
        "Le taux des prélèvements sociaux relève de la législation en vigueur et peut évoluer.",
        "Ils doivent être intégrés dans toute simulation de rachat.",
    ],
    client_questions=[
        "Que sont les prélèvements sociaux ?",
        "Sont-ils différents de l'impôt sur le revenu ?",
        "Pourquoi dois-je encore payer alors que je bénéficie d'un abattement ?",
        "Les prélèvements sociaux s'appliquent-ils au capital ?",
    ],
    client_objections=[
        "Je pensais que l'abattement supprimait toute fiscalité.",
        "Je ne comprends pas la différence entre impôt et prélèvements sociaux.",
        "Cela me paraît beaucoup trop complexe.",
    ],
    client_fears=[
        "Découvrir une fiscalité plus importante que prévu.",
        "Mal anticiper le coût d'un retrait.",
        "Confondre les différents mécanismes fiscaux.",
    ],
    client_goals=[
        "Comprendre le coût réel d'un rachat.",
        "Anticiper sa fiscalité.",
        "Éviter les mauvaises surprises.",
    ],
    client_intents=[
        "comprendre les prélèvements sociaux",
        "calculer la fiscalité",
        "préparer un rachat",
        "optimiser un retrait",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fiscalite_principe_general",
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_plus_value",
        "assurance_vie_fiscalite_abattement",
        "assurance_vie_fiscalite_pfu",
    ],
    prerequisites=[
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_plus_value",
    ],
    next_topics=[
        "assurance_vie_fiscalite_pfu",
        "assurance_vie_fiscalite_erreurs",
    ],
),

Topic(
    id="assurance_vie_fiscalite_pfu",
    title="Flat Tax ou barème progressif : comment choisir ?",
    pillar="optimiser",
    family="assurance_vie",
    chapter="fiscalite",
    description="Comprendre les deux principaux modes d'imposition des gains d'une assurance-vie afin d'identifier celui qui peut être le plus adapté à sa situation fiscale.",
    objective="Expliquer que les gains peuvent, selon les situations prévues par la réglementation, être soumis soit au prélèvement forfaitaire, soit au barème progressif de l'impôt sur le revenu, et que ce choix mérite une analyse globale.",
    difficulty="Intermédiaire",
    priority=9,
    version=1,
    keywords=[
        "PFU",
        "Flat Tax",
        "barème progressif",
        "impôt sur le revenu",
        "assurance-vie",
        "rachat",
        "fiscalité",
        "optimisation",
    ],
    key_points=[
        "Les gains d'un rachat peuvent relever de différents régimes fiscaux selon la situation du contrat et les options ouvertes au contribuable.",
        "Le prélèvement forfaitaire unique (PFU), souvent appelé Flat Tax, applique un taux forfaitaire selon les règles en vigueur.",
        "Le barème progressif consiste à intégrer les gains imposables dans les revenus soumis à l'impôt sur le revenu.",
        "Le choix entre ces deux régimes dépend notamment de la situation fiscale globale du souscripteur.",
        "Une comparaison préalable permet d'éviter une imposition plus élevée que nécessaire.",
    ],
    examples=[
        "Julie, 32 ans, débute sa carrière et se situe dans une faible tranche marginale d'imposition. Avant son rachat, elle compare les deux régimes afin d'identifier celui qui lui est le plus favorable.",

        "Marc, 54 ans, perçoit des revenus élevés. Avant de retirer une partie de son assurance-vie, il analyse les conséquences d'une taxation au PFU par rapport au barème progressif afin d'optimiser son imposition.",

        "Sophie, 67 ans, réalise plusieurs rachats pour compléter ses revenus à la retraite. Chaque année, elle vérifie le régime fiscal le plus adapté à sa situation plutôt que d'appliquer systématiquement le même choix.",
    ],
    vocabulary=[
        "PFU",
        "Flat Tax",
        "barème progressif",
        "tranche marginale d'imposition",
        "impôt sur le revenu",
        "rachat",
        "gains",
        "option fiscale",
    ],
    legal_sources=[
        "Code général des impôts",
        "BOFiP - Assurance-vie",
    ],
    analogies=[
        "Choisir entre le PFU et le barème progressif revient à choisir entre deux itinéraires pour atteindre la même destination : selon votre situation, l'un peut être plus avantageux que l'autre.",
    ],
    misconceptions=[
        "Le PFU est toujours la meilleure solution.",
        "Le barème progressif est réservé aux faibles revenus.",
        "Le choix est identique pour tous les contribuables.",
        "Il est inutile de comparer les deux régimes.",
    ],
    common_mistakes=[
        "Choisir automatiquement le PFU sans réaliser de simulation.",
        "Oublier que la situation fiscale globale influence le résultat.",
        "Confondre PFU et prélèvements sociaux.",
        "Prendre une décision uniquement sur la base d'un taux affiché.",
    ],
    expert_tips=[
        "Le choix entre le PFU et le barème progressif ne doit jamais être automatique. Une simulation intégrant l'ensemble des revenus du foyer permet souvent d'identifier la solution la plus pertinente.",
    ],
    attention_points=[
        "Les règles applicables dépendent notamment de la réglementation en vigueur et des caractéristiques du contrat.",
        "Le PFU et les prélèvements sociaux sont deux mécanismes distincts.",
        "Une approche patrimoniale globale est préférable à une analyse limitée au seul contrat d'assurance-vie.",
    ],
    client_questions=[
        "Qu'est-ce que la Flat Tax ?",
        "Dois-je choisir le PFU ou le barème progressif ?",
        "Comment savoir quel régime est le plus avantageux ?",
        "Puis-je changer de régime fiscal ?",
    ],
    client_objections=[
        "Je ne comprends pas la différence entre les deux.",
        "Je pensais que tout le monde payait la Flat Tax.",
        "Le calcul me paraît trop compliqué.",
    ],
    client_fears=[
        "Choisir le mauvais régime fiscal.",
        "Payer davantage d'impôt que nécessaire.",
        "Ne pas comprendre les conséquences de mon choix.",
    ],
    client_goals=[
        "Optimiser la fiscalité de ses retraits.",
        "Comprendre les différents régimes d'imposition.",
        "Prendre une décision éclairée.",
    ],
    client_intents=[
        "comprendre le PFU",
        "choisir entre PFU et barème",
        "optimiser la fiscalité",
        "préparer un rachat",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fiscalite_principe_general",
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_plus_value",
        "assurance_vie_fiscalite_abattement",
        "assurance_vie_fiscalite_prelevements_sociaux",
    ],
    prerequisites=[
        "assurance_vie_fiscalite_prelevements_sociaux",
    ],
    next_topics=[
        "assurance_vie_fiscalite_erreurs",
    ],
),

Topic(
    id="assurance_vie_fiscalite_erreurs",
    title="Quelles erreurs fiscales éviter avec une assurance-vie ?",
    pillar="optimiser",
    family="assurance_vie",
    chapter="fiscalite",
    description="Identifier les erreurs fiscales les plus fréquentes afin d'utiliser l'assurance-vie dans une stratégie patrimoniale cohérente.",
    objective="Aider les épargnants à éviter les idées reçues et les décisions qui peuvent entraîner une fiscalité inutilement défavorable.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "erreurs",
        "fiscalité",
        "assurance-vie",
        "rachat",
        "PFU",
        "8 ans",
        "abattement",
        "plus-value",
        "prélèvements sociaux",
    ],
    key_points=[
        "La fiscalité ne doit jamais être le seul critère de décision patrimoniale.",
        "Un rachat n'entraîne pas automatiquement une forte imposition.",
        "Les huit ans constituent un avantage fiscal, mais ne doivent pas bloquer un projet pertinent.",
        "Le coût fiscal réel dépend de nombreux paramètres et mérite une analyse globale.",
        "Une bonne compréhension des mécanismes fiscaux permet souvent d'éviter des erreurs coûteuses.",
    ],
    examples=[
        "Julie, 41 ans, refuse de financer un projet immobilier par crainte d'une fiscalité qu'elle imagine très lourde. Après simulation, elle découvre que seule une faible partie de son retrait est effectivement imposable.",

        "Marc, 59 ans, clôture son assurance-vie de neuf ans pour ouvrir un contrat plus récent, sans mesurer qu'il perd ainsi l'ancienneté fiscale acquise depuis plusieurs années.",

        "Sophie, 66 ans, pense que les huit ans rendent tous les retraits totalement exonérés d'impôt. En préparant son rachat, elle découvre que plusieurs règles fiscales continuent de s'appliquer.",
    ],
    vocabulary=[
        "ancienneté fiscale",
        "rachat",
        "plus-value",
        "abattement",
        "PFU",
        "barème progressif",
        "prélèvements sociaux",
        "optimisation",
    ],
    legal_sources=[
        "Code général des impôts",
        "BOFiP - Assurance-vie",
        "Code des assurances",
    ],
    analogies=[
        "Se focaliser uniquement sur la fiscalité revient à choisir une maison uniquement en fonction de la taxe foncière : c'est un élément important, mais il ne suffit pas à prendre une bonne décision.",
    ],
    misconceptions=[
        "Il ne faut jamais effectuer de rachat avant huit ans.",
        "Toute somme retirée est imposée.",
        "Après huit ans, l'assurance-vie devient totalement exonérée.",
        "Le PFU est toujours la meilleure solution.",
        "La fiscalité est le seul critère à prendre en compte.",
    ],
    common_mistakes=[
        "Reporter un projet uniquement pour des raisons fiscales.",
        "Clôturer un ancien contrat sans analyser les conséquences.",
        "Confondre capital retiré et gains imposables.",
        "Confondre impôt sur le revenu et prélèvements sociaux.",
        "Choisir un régime fiscal sans effectuer de simulation.",
    ],
    expert_tips=[
        "L'objectif d'une bonne stratégie patrimoniale n'est pas de ne jamais payer d'impôt, mais de prendre les bonnes décisions au bon moment en comprenant leurs conséquences fiscales.",
    ],
    attention_points=[
        "La réglementation fiscale évolue régulièrement.",
        "Chaque situation patrimoniale est différente.",
        "Une simulation est souvent préférable à une décision fondée sur une idée reçue.",
    ],
    client_questions=[
        "Quelles sont les erreurs les plus fréquentes ?",
        "Dois-je attendre huit ans avant un retrait ?",
        "Comment éviter une mauvaise décision fiscale ?",
        "Comment optimiser mes retraits ?",
    ],
    client_objections=[
        "Je préfère ne rien toucher pour éviter les impôts.",
        "La fiscalité est trop compliquée.",
        "J'ai peur de faire une erreur irréversible.",
    ],
    client_fears=[
        "Payer trop d'impôts.",
        "Perdre un avantage fiscal.",
        "Prendre une mauvaise décision patrimoniale.",
    ],
    client_goals=[
        "Comprendre les règles fiscales.",
        "Éviter les erreurs classiques.",
        "Optimiser ses retraits.",
        "Construire une stratégie patrimoniale cohérente.",
    ],
    client_intents=[
        "éviter les erreurs fiscales",
        "optimiser son assurance-vie",
        "préparer un rachat",
        "comprendre la fiscalité",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_fiscalite_principe_general",
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_plus_value",
        "assurance_vie_fiscalite_8_ans",
        "assurance_vie_fiscalite_abattement",
        "assurance_vie_fiscalite_prelevements_sociaux",
        "assurance_vie_fiscalite_pfu",
    ],
    prerequisites=[
        "assurance_vie_fiscalite_principe_general",
        "assurance_vie_fiscalite_rachat",
        "assurance_vie_fiscalite_pfu",
    ],
    next_topics=[
        "assurance_vie_transmission_principe_general",
        "assurance_vie_clause_beneficiaire_definition",
    ],
),

