from v2.models.knowledge_models import Topic

GESTION_TOPICS: list[Topic] = []

Topic(
    id="assurance_vie_gestion_libre",
    title="Qu'est-ce que la gestion libre en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="gestion",
    description="Comprendre le fonctionnement de la gestion libre et les responsabilités qu'elle implique pour le souscripteur.",
    objective="Expliquer que la gestion libre permet au souscripteur de sélectionner lui-même les supports d'investissement de son assurance-vie et de faire évoluer son allocation selon ses objectifs patrimoniaux.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "gestion libre",
        "assurance-vie",
        "allocation",
        "supports",
        "fonds euros",
        "unités de compte",
        "gestion autonome",
        "arbitrage",
        "investissement",
    ],
    key_points=[
        "La gestion libre permet au souscripteur de choisir lui-même les supports de son contrat.",
        "Le souscripteur décide de la répartition entre fonds euros et unités de compte.",
        "Il peut modifier son allocation grâce aux arbitrages proposés par le contrat.",
        "La gestion libre offre une grande autonomie mais implique un suivi régulier.",
        "Elle convient aux épargnants souhaitant conserver la maîtrise de leurs décisions d'investissement.",
    ],
    examples=[
        "Julie, 34 ans, prépare sa retraite avec un horizon de placement de plus de 25 ans. À l'aise avec les marchés financiers, elle choisit la gestion libre afin de construire elle-même une allocation composée de fonds euros et d'ETF mondiaux. Chaque année, elle rééquilibre son contrat en fonction de ses objectifs.",

        "Marc, 52 ans, suit régulièrement l'actualité économique. Il apprécie de sélectionner lui-même ses supports d'investissement et réalise ponctuellement des arbitrages lorsque sa situation familiale ou patrimoniale évolue.",

        "Claire, 40 ans, débute en investissement mais souhaite apprendre progressivement. Elle commence avec une allocation simple en gestion libre, composée majoritairement d'un fonds euros et de quelques unités de compte diversifiées, qu'elle adapte au fil de son expérience.",
    ],
    vocabulary=[
        "gestion libre",
        "allocation",
        "arbitrage",
        "fonds euros",
        "unités de compte",
        "profil investisseur",
        "diversification",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "La gestion libre revient à conduire sa propre voiture : vous choisissez votre itinéraire, votre vitesse et les ajustements en cours de route.",
    ],
    misconceptions=[
        "La gestion libre est réservée aux experts de la finance.",
        "Choisir la gestion libre signifie forcément prendre beaucoup de risques.",
        "Une fois les supports choisis, il n'est plus possible de les modifier.",
    ],
    common_mistakes=[
        "Ne jamais revoir son allocation.",
        "Multiplier les arbitrages sous l'effet des émotions.",
        "Choisir des supports sans comprendre leur fonctionnement.",
        "Copier la stratégie d'un autre investisseur sans tenir compte de ses propres objectifs.",
    ],
    expert_tips=[
        "La gestion libre est particulièrement pertinente pour les investisseurs souhaitant conserver le contrôle de leur stratégie patrimoniale tout en acceptant d'y consacrer un minimum de temps chaque année.",
    ],
    attention_points=[
        "Une gestion libre nécessite un suivi régulier du contrat.",
        "Les arbitrages doivent être motivés par une évolution des objectifs patrimoniaux, et non par les fluctuations quotidiennes des marchés.",
        "La diversification reste essentielle, même en gestion libre.",
    ],
    client_questions=[
        "Qu'est-ce que la gestion libre ?",
        "Puis-je choisir moi-même mes investissements ?",
        "À quelle fréquence dois-je suivre mon contrat ?",
        "La gestion libre est-elle adaptée aux débutants ?",
    ],
    client_objections=[
        "Je ne suis pas spécialiste des marchés financiers.",
        "Je manque de temps pour gérer mes placements.",
        "J'ai peur de faire les mauvais choix.",
    ],
    client_fears=[
        "Perdre de l'argent à cause d'une mauvaise décision.",
        "Ne pas savoir quand modifier mon allocation.",
        "Faire moins bien qu'une gestion professionnelle.",
    ],
    client_goals=[
        "Conserver le contrôle de ses investissements.",
        "Construire une allocation personnalisée.",
        "Faire évoluer son contrat selon ses objectifs.",
    ],
    client_intents=[
        "comprendre la gestion libre",
        "gérer soi-même son assurance-vie",
        "choisir ses supports",
        "investir en autonomie",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_supports_allocation",
        "assurance_vie_supports_arbitrage",
        "assurance_vie_gestion_pilotee",
        "assurance_vie_gestion_profil_investisseur",
    ],
    prerequisites=[
        "assurance_vie_supports_allocation",
        "assurance_vie_supports_arbitrage",
    ],
    next_topics=[
        "assurance_vie_gestion_pilotee",
        "assurance_vie_gestion_sous_mandat",
    ],
),

Topic(
    id="assurance_vie_gestion_pilotee",
    title="Qu'est-ce que la gestion pilotée en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="gestion",
    description="Comprendre le fonctionnement de la gestion pilotée et les situations dans lesquelles elle peut constituer une solution adaptée.",
    objective="Expliquer que la gestion pilotée consiste à déléguer les décisions d'investissement à des professionnels selon un profil de risque défini par le souscripteur.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "gestion pilotée",
        "gestion déléguée",
        "profil investisseur",
        "allocation",
        "assurance-vie",
        "gestion sous mandat",
        "arbitrage",
        "investissement",
    ],
    key_points=[
        "La gestion pilotée consiste à déléguer les choix d'investissement à une société de gestion ou à un professionnel mandaté.",
        "Le souscripteur choisit généralement un profil de risque (prudent, équilibré, dynamique...) plutôt que les supports eux-mêmes.",
        "Les arbitrages sont réalisés automatiquement en fonction de la stratégie définie.",
        "La gestion pilotée permet de bénéficier d'un suivi professionnel sans intervenir au quotidien.",
        "Elle ne garantit ni la performance ni le capital investi.",
    ],
    examples=[
        "Julie, 31 ans, souhaite préparer sa retraite mais ne dispose ni du temps ni des connaissances nécessaires pour suivre les marchés financiers. Elle opte pour une gestion pilotée avec un profil dynamique afin de déléguer entièrement les décisions d'investissement.",

        "Marc, 58 ans, approche de la retraite et privilégie la stabilité de son patrimoine. Il choisit un profil prudent afin que les arbitrages soient réalisés automatiquement en cohérence avec son horizon de placement.",

        "Claire, 45 ans, investit régulièrement sur son assurance-vie mais préfère consacrer son temps à son activité professionnelle. Elle confie la gestion de son contrat à une équipe de gestion tout en suivant une fois par an les résultats obtenus.",
    ],
    vocabulary=[
        "gestion pilotée",
        "mandat",
        "profil de risque",
        "allocation",
        "arbitrage",
        "gestionnaire",
        "rééquilibrage",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
    ],
    analogies=[
        "La gestion pilotée revient à prendre un taxi : vous choisissez la destination, mais c'est un professionnel qui conduit et adapte l'itinéraire si nécessaire.",
    ],
    misconceptions=[
        "La gestion pilotée garantit une meilleure performance.",
        "La gestion pilotée supprime totalement le risque.",
        "Une fois le profil choisi, il est impossible de le modifier.",
    ],
    common_mistakes=[
        "Choisir un profil de risque qui ne correspond pas à son horizon d'investissement.",
        "Comparer uniquement les performances de court terme.",
        "Croire que la délégation dispense de suivre son contrat.",
        "Confondre gestion pilotée et absence totale de risque.",
    ],
    expert_tips=[
        "La qualité d'une gestion pilotée dépend davantage de la cohérence entre le profil choisi et les objectifs patrimoniaux que de la performance d'une seule année.",
    ],
    attention_points=[
        "Le profil de risque doit être réévalué lorsque la situation personnelle évolue.",
        "Les frais de gestion pilotée peuvent être supérieurs à ceux d'une gestion libre.",
        "La délégation de gestion ne supprime jamais le risque de perte en capital.",
    ],
    client_questions=[
        "Qu'est-ce que la gestion pilotée ?",
        "Qui prend les décisions d'investissement ?",
        "Puis-je changer de profil ?",
        "La gestion pilotée est-elle faite pour moi ?",
    ],
    client_objections=[
        "Je préfère garder le contrôle de mes investissements.",
        "Je crains de payer des frais supplémentaires.",
        "Je ne connais pas les personnes qui géreront mon contrat.",
    ],
    client_fears=[
        "Obtenir de mauvaises performances.",
        "Ne plus maîtriser mes investissements.",
        "Choisir un profil inadapté.",
    ],
    client_goals=[
        "Déléguer la gestion de son assurance-vie.",
        "Profiter d'un suivi professionnel.",
        "Investir sans suivre quotidiennement les marchés.",
    ],
    client_intents=[
        "comprendre la gestion pilotée",
        "déléguer ses investissements",
        "choisir un profil de risque",
        "faire gérer son assurance-vie",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_gestion_libre",
        "assurance_vie_gestion_sous_mandat",
        "assurance_vie_gestion_profil_investisseur",
        "assurance_vie_supports_allocation",
    ],
    prerequisites=[
        "assurance_vie_gestion_libre",
    ],
    next_topics=[
        "assurance_vie_gestion_sous_mandat",
        "assurance_vie_gestion_profil_investisseur",
    ],
),

Topic(
    id="assurance_vie_gestion_sous_mandat",
    title="Qu'est-ce que la gestion sous mandat en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="gestion",
    description="Comprendre le fonctionnement de la gestion sous mandat et les situations dans lesquelles elle peut répondre aux besoins d'un investisseur.",
    objective="Expliquer que la gestion sous mandat permet de déléguer les décisions d'investissement à un professionnel dans le cadre d'un mandat défini selon les objectifs, l'horizon de placement et le profil de risque du souscripteur.",
    difficulty="Intermédiaire",
    priority=9,
    version=1,
    keywords=[
        "gestion sous mandat",
        "mandat de gestion",
        "gestion déléguée",
        "assurance-vie",
        "allocation",
        "profil investisseur",
        "gestionnaire",
        "investissement",
    ],
    key_points=[
        "La gestion sous mandat repose sur une délégation formalisée des décisions d'investissement.",
        "Le gestionnaire agit dans les limites définies par le mandat signé avec le souscripteur.",
        "Les décisions tiennent compte des objectifs patrimoniaux, de l'horizon d'investissement et du profil de risque.",
        "Le souscripteur conserve la propriété de son contrat tout en déléguant les arbitrages.",
        "La qualité de la gestion doit être appréciée sur le long terme et non sur quelques mois de performance.",
    ],
    examples=[
        "Pierre, 61 ans, vient de céder son entreprise. Souhaitant consacrer son temps à sa famille plutôt qu'au suivi des marchés financiers, il confie la gestion de son assurance-vie à une société de gestion dans le cadre d'un mandat adapté à son objectif de préservation du capital.",

        "Sophie, 46 ans, dispose d'un patrimoine financier important réparti sur plusieurs enveloppes. Elle choisit une gestion sous mandat afin de bénéficier d'une stratégie cohérente avec ses objectifs patrimoniaux et son horizon de placement de vingt ans.",

        "David, 55 ans, souhaite déléguer entièrement les arbitrages de son contrat tout en conservant un profil équilibré. Son mandat est réévalué régulièrement afin de rester cohérent avec l'évolution de sa situation familiale et professionnelle.",
    ],
    vocabulary=[
        "mandat",
        "gestionnaire",
        "allocation",
        "arbitrage",
        "profil de risque",
        "délégation",
        "stratégie patrimoniale",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
    ],
    analogies=[
        "La gestion sous mandat ressemble à la délégation de la gestion d'un patrimoine immobilier à un administrateur : vous restez propriétaire, mais un professionnel prend les décisions de gestion selon des règles définies à l'avance.",
    ],
    misconceptions=[
        "La gestion sous mandat garantit des performances supérieures.",
        "Le gestionnaire peut investir sans aucune limite.",
        "Le souscripteur perd totalement le contrôle de son contrat.",
    ],
    common_mistakes=[
        "Choisir un mandat sans définir clairement ses objectifs patrimoniaux.",
        "Comparer uniquement les performances de court terme.",
        "Ne jamais revoir le mandat malgré l'évolution de sa situation.",
        "Confondre délégation de gestion et absence totale de risque.",
    ],
    expert_tips=[
        "La valeur d'une gestion sous mandat repose avant tout sur la qualité du mandat initial et sur son adéquation avec les objectifs patrimoniaux du client.",
    ],
    attention_points=[
        "Les frais sont généralement plus élevés qu'en gestion libre.",
        "Le mandat doit être revu régulièrement afin de rester cohérent avec la situation du souscripteur.",
        "La délégation de gestion ne supprime jamais le risque de perte en capital.",
    ],
    client_questions=[
        "Quelle différence avec la gestion pilotée ?",
        "Qui prend les décisions d'investissement ?",
        "Puis-je modifier mon mandat ?",
        "La gestion sous mandat est-elle réservée aux patrimoines importants ?",
    ],
    client_objections=[
        "Je préfère conserver le contrôle de mes investissements.",
        "Les frais me semblent élevés.",
        "Je ne connais pas le gestionnaire qui prendra les décisions.",
    ],
    client_fears=[
        "Confier mon patrimoine à un tiers.",
        "Obtenir de mauvaises performances.",
        "Ne plus comprendre les décisions prises.",
    ],
    client_goals=[
        "Déléguer la gestion de son contrat.",
        "Bénéficier d'une expertise professionnelle.",
        "Construire une stratégie patrimoniale de long terme.",
    ],
    client_intents=[
        "comprendre la gestion sous mandat",
        "déléguer ses investissements",
        "faire gérer son assurance-vie",
        "comparer les modes de gestion",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_gestion_libre",
        "assurance_vie_gestion_pilotee",
        "assurance_vie_gestion_profil_investisseur",
        "assurance_vie_supports_allocation",
    ],
    prerequisites=[
        "assurance_vie_gestion_pilotee",
    ],
    next_topics=[
        "assurance_vie_gestion_profil_investisseur",
        "assurance_vie_gestion_reequilibrage",
    ],
),

Topic(
    id="assurance_vie_gestion_profil_investisseur",
    title="Comment déterminer son profil investisseur en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="gestion",
    description="Comprendre l'importance du profil investisseur dans le choix des supports et du mode de gestion d'une assurance-vie.",
    objective="Expliquer comment le profil investisseur est déterminé et pourquoi il constitue le point de départ de toute stratégie patrimoniale cohérente.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "profil investisseur",
        "profil de risque",
        "tolérance au risque",
        "horizon de placement",
        "allocation",
        "gestion pilotée",
        "gestion libre",
        "assurance-vie",
    ],
    key_points=[
        "Le profil investisseur permet d'évaluer la capacité et la volonté d'un épargnant à accepter le risque.",
        "Il prend en compte les objectifs patrimoniaux, l'horizon de placement, la situation financière et les connaissances du souscripteur.",
        "Le profil investisseur oriente le choix des supports et du mode de gestion.",
        "Il peut évoluer au cours de la vie en fonction des changements personnels ou professionnels.",
        "Le profil investisseur doit être régulièrement réévalué afin de maintenir une stratégie adaptée.",
    ],
    examples=[
        "Julie, 29 ans, débute sa vie professionnelle et souhaite préparer sa retraite dans plus de trente ans. Son horizon de placement long lui permet d'accepter davantage de volatilité et d'adopter un profil dynamique.",

        "Marc, 60 ans, prévoit de compléter ses revenus dans cinq ans. Son objectif est désormais de préserver son capital : son profil évolue progressivement vers une approche plus prudente.",

        "Sophie, 43 ans, possède déjà un patrimoine immobilier important. Son assurance-vie constitue un outil de diversification financière, ce qui influence son profil investisseur et la répartition de son contrat.",
    ],
    vocabulary=[
        "profil investisseur",
        "tolérance au risque",
        "horizon de placement",
        "allocation",
        "volatilité",
        "diversification",
        "objectif patrimonial",
    ],
    legal_sources=[
        "Code monétaire et financier",
        "Directive MIF 2",
        "Code des assurances",
    ],
    analogies=[
        "Déterminer son profil investisseur revient à choisir une pointure de chaussures : ce qui convient à une personne peut être totalement inadapté à une autre.",
    ],
    misconceptions=[
        "Les jeunes investisseurs doivent toujours être dynamiques.",
        "Le même profil convient à tous les investisseurs.",
        "Le profil investisseur reste identique toute la vie.",
    ],
    common_mistakes=[
        "Surestimer sa tolérance au risque.",
        "Construire une allocation uniquement à partir des performances passées.",
        "Copier la stratégie d'un proche sans tenir compte de sa propre situation.",
        "Ne jamais réévaluer son profil malgré un changement de situation personnelle.",
    ],
    expert_tips=[
        "Le meilleur portefeuille n'est pas celui qui offre la performance la plus élevée, mais celui que l'investisseur sera capable de conserver sur le long terme sans prendre de décisions émotionnelles.",
    ],
    attention_points=[
        "Le profil investisseur n'est pas figé et mérite d'être réexaminé régulièrement.",
        "L'horizon de placement est souvent plus déterminant que l'âge du souscripteur.",
        "Le niveau de risque doit rester compatible avec la situation patrimoniale globale.",
    ],
    client_questions=[
        "Comment connaître mon profil investisseur ?",
        "Qui détermine mon profil ?",
        "Puis-je changer de profil ?",
        "Pourquoi dois-je remplir un questionnaire ?",
    ],
    client_objections=[
        "Je ne sais pas quel profil choisir.",
        "J'ai peur que mon profil soit mal évalué.",
        "Je préfère copier la stratégie d'autres investisseurs.",
    ],
    client_fears=[
        "Choisir un profil trop risqué.",
        "Ne pas atteindre mes objectifs.",
        "Perdre une partie de mon capital.",
    ],
    client_goals=[
        "Construire une stratégie adaptée.",
        "Investir en cohérence avec ses objectifs.",
        "Trouver un équilibre entre performance et sécurité.",
    ],
    client_intents=[
        "déterminer son profil investisseur",
        "connaître son niveau de risque",
        "choisir une allocation",
        "préparer ses investissements",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_gestion_libre",
        "assurance_vie_gestion_pilotee",
        "assurance_vie_gestion_sous_mandat",
        "assurance_vie_gestion_reequilibrage",
    ],
    prerequisites=[
        "assurance_vie_gestion_libre",
        "assurance_vie_gestion_pilotee",
    ],
    next_topics=[
        "assurance_vie_gestion_reequilibrage",
        "assurance_vie_gestion_horizon_placement",
    ],
),

Topic(
    id="assurance_vie_gestion_reequilibrage",
    title="Faut-il rééquilibrer régulièrement son assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="gestion",
    description="Comprendre pourquoi le rééquilibrage est une étape essentielle dans la gestion d'une assurance-vie et comment il permet de maintenir une allocation cohérente avec ses objectifs patrimoniaux.",
    objective="Expliquer que le rééquilibrage consiste à ajuster périodiquement la répartition des investissements afin de conserver un niveau de risque conforme aux objectifs initiaux du souscripteur.",
    difficulty="Intermédiaire",
    priority=9,
    version=1,
    keywords=[
        "rééquilibrage",
        "allocation",
        "arbitrage",
        "gestion",
        "assurance-vie",
        "profil investisseur",
        "diversification",
        "risque",
    ],
    key_points=[
        "Le rééquilibrage consiste à ramener l'allocation du contrat vers sa répartition cible.",
        "Les performances des marchés modifient naturellement le poids des différents supports au fil du temps.",
        "Rééquilibrer permet de conserver un niveau de risque cohérent avec son profil investisseur.",
        "Le rééquilibrage peut être réalisé manuellement ou automatiquement selon les contrats.",
        "Il ne s'agit pas de rechercher la meilleure performance, mais de respecter une stratégie patrimoniale de long terme.",
    ],
    examples=[
        "Julie, 36 ans, avait réparti son contrat à 60 % en unités de compte et 40 % en fonds euros. Trois ans plus tard, la forte hausse des marchés porte les unités de compte à 75 %. Elle procède à un rééquilibrage afin de revenir à son allocation initiale.",

        "Marc, 58 ans, approche de la retraite. Chaque année, il réduit progressivement son exposition aux marchés financiers au profit du fonds euros afin de sécuriser son capital.",

        "Sophie, 44 ans, utilise une option de rééquilibrage automatique proposée par son contrat. Son allocation reste ainsi alignée avec son profil sans intervention régulière de sa part.",
    ],
    vocabulary=[
        "rééquilibrage",
        "allocation cible",
        "arbitrage",
        "profil investisseur",
        "volatilité",
        "diversification",
        "allocation d'actifs",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Le rééquilibrage ressemble au réglage du parallélisme d'une voiture : même si tout semble fonctionner, de petits écarts apparaissent avec le temps et doivent être corrigés pour conserver la bonne trajectoire.",
    ],
    misconceptions=[
        "Un contrat performant ne doit jamais être modifié.",
        "Rééquilibrer revient à vendre systématiquement les meilleurs supports.",
        "Le rééquilibrage sert uniquement lorsque les marchés baissent.",
    ],
    common_mistakes=[
        "Ne jamais revoir son allocation.",
        "Rééquilibrer sous l'effet de la peur plutôt que selon une stratégie définie.",
        "Modifier son allocation après chaque mouvement des marchés.",
        "Confondre rééquilibrage et recherche de performance à court terme.",
    ],
    expert_tips=[
        "Un bon rééquilibrage est planifié à l'avance. Il repose sur une méthode et non sur les émotions ou les prévisions de marché.",
    ],
    attention_points=[
        "La fréquence de rééquilibrage dépend du profil de risque et de l'évolution des marchés.",
        "Des arbitrages peuvent générer des frais selon les contrats.",
        "Le rééquilibrage doit rester cohérent avec les objectifs patrimoniaux du souscripteur.",
    ],
    client_questions=[
        "Dois-je modifier mon assurance-vie chaque année ?",
        "Quand faut-il rééquilibrer son contrat ?",
        "Le rééquilibrage est-il automatique ?",
        "Comment savoir si mon allocation est toujours adaptée ?",
    ],
    client_objections=[
        "Je préfère laisser mon contrat évoluer tout seul.",
        "J'ai peur de vendre au mauvais moment.",
        "Je ne sais jamais quand intervenir.",
    ],
    client_fears=[
        "Perdre mes gains.",
        "Faire un mauvais arbitrage.",
        "Modifier une allocation qui fonctionnait bien.",
    ],
    client_goals=[
        "Maintenir une allocation cohérente.",
        "Respecter son profil investisseur.",
        "Piloter son risque dans la durée.",
    ],
    client_intents=[
        "rééquilibrer son assurance-vie",
        "modifier son allocation",
        "réduire son risque",
        "gérer son contrat",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_gestion_profil_investisseur",
        "assurance_vie_gestion_libre",
        "assurance_vie_supports_allocation",
        "assurance_vie_supports_arbitrage",
    ],
    prerequisites=[
        "assurance_vie_gestion_profil_investisseur",
    ],
    next_topics=[
        "assurance_vie_gestion_horizon_placement",
        "assurance_vie_gestion_suivi_contrat",
    ],
),

Topic(
    id="assurance_vie_gestion_horizon_placement",
    title="Pourquoi l'horizon de placement est-il essentiel en assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="gestion",
    description="Comprendre pourquoi la durée d'investissement constitue l'un des principaux critères dans le choix des supports et de la stratégie de gestion d'une assurance-vie.",
    objective="Expliquer que l'horizon de placement influence directement le niveau de risque acceptable, l'allocation d'actifs et les décisions de gestion tout au long de la vie du contrat.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "horizon de placement",
        "durée",
        "investissement",
        "allocation",
        "profil investisseur",
        "assurance-vie",
        "gestion",
        "long terme",
    ],
    key_points=[
        "L'horizon de placement correspond à la durée pendant laquelle l'épargnant prévoit de laisser son capital investi.",
        "Plus l'horizon est long, plus il est généralement possible d'accepter une part importante d'unités de compte.",
        "À l'approche d'un projet ou de la retraite, il est souvent pertinent de réduire progressivement le niveau de risque.",
        "L'horizon de placement influence directement l'allocation d'actifs et le mode de gestion.",
        "Il doit être réévalué à chaque changement important de situation patrimoniale ou personnelle.",
    ],
    examples=[
        "Julie, 28 ans, souhaite préparer sa retraite dans plus de trente-cinq ans. Son horizon de placement très long lui permet d'accepter une forte exposition aux marchés actions malgré leurs fluctuations temporaires.",

        "Marc, 55 ans, prévoit de financer les études supérieures de son fils dans cinq ans. Il adapte progressivement son assurance-vie afin de sécuriser une partie de son capital avant cette échéance.",

        "Sophie, 63 ans, vient de partir à la retraite. Son objectif n'est plus de rechercher la performance maximale, mais de préserver son patrimoine tout en conservant un potentiel de rendement adapté à son nouveau mode de vie.",
    ],
    vocabulary=[
        "horizon de placement",
        "allocation",
        "volatilité",
        "profil investisseur",
        "gestion",
        "capital",
        "risque",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
    ],
    analogies=[
        "Choisir ses investissements sans connaître son horizon de placement revient à réserver un moyen de transport sans savoir si le voyage dure une heure ou plusieurs semaines.",
    ],
    misconceptions=[
        "L'âge est le seul critère qui détermine les investissements.",
        "Les placements risqués sont toujours à éviter.",
        "Une allocation performante est identique quel que soit l'horizon de placement.",
    ],
    common_mistakes=[
        "Investir sur des supports très volatils pour financer un projet à court terme.",
        "Conserver une allocation trop dynamique à l'approche d'un besoin de liquidités.",
        "Ne jamais adapter son contrat lorsque son horizon de placement évolue.",
        "Confondre horizon de placement et durée fiscale du contrat.",
    ],
    expert_tips=[
        "L'horizon de placement constitue souvent le critère le plus déterminant dans la construction d'une allocation patrimoniale. Il est généralement plus pertinent que l'âge seul du souscripteur.",
    ],
    attention_points=[
        "Chaque projet patrimonial possède son propre horizon de placement.",
        "Une évolution familiale, professionnelle ou patrimoniale peut justifier une révision de la stratégie d'investissement.",
        "L'ancienneté fiscale du contrat ne doit pas être confondue avec l'horizon d'investissement.",
    ],
    client_questions=[
        "Pourquoi parle-t-on toujours d'horizon de placement ?",
        "Puis-je investir en actions si j'ai 60 ans ?",
        "Dois-je modifier mon contrat avant un projet important ?",
        "Quel horizon faut-il pour investir en unités de compte ?",
    ],
    client_objections=[
        "Je préfère attendre le bon moment avant d'investir.",
        "Je suis trop âgé pour investir sur les marchés.",
        "Je ne connais pas encore mes futurs projets.",
    ],
    client_fears=[
        "Avoir besoin de mon argent pendant une baisse des marchés.",
        "Choisir une stratégie inadaptée.",
        "Prendre trop de risques à l'approche d'un projet.",
    ],
    client_goals=[
        "Adapter son contrat à ses projets de vie.",
        "Construire une stratégie de long terme.",
        "Limiter le risque lorsque l'échéance approche.",
    ],
    client_intents=[
        "déterminer son horizon de placement",
        "adapter son assurance-vie",
        "préparer un projet",
        "investir sur le long terme",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_gestion_profil_investisseur",
        "assurance_vie_gestion_reequilibrage",
        "assurance_vie_supports_allocation",
        "assurance_vie_supports_risque",
    ],
    prerequisites=[
        "assurance_vie_gestion_profil_investisseur",
    ],
    next_topics=[
        "assurance_vie_gestion_suivi_contrat",
        "assurance_vie_gestion_erreurs",
    ],
),

Topic(
    id="assurance_vie_gestion_suivi_contrat",
    title="À quelle fréquence faut-il suivre son assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="gestion",
    description="Comprendre pourquoi une assurance-vie doit être suivie régulièrement sans pour autant réagir aux fluctuations quotidiennes des marchés financiers.",
    objective="Expliquer qu'un suivi périodique permet de maintenir une stratégie patrimoniale cohérente avec les objectifs, le profil de risque et l'évolution de la situation personnelle du souscripteur.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "suivi assurance-vie",
        "gestion",
        "allocation",
        "arbitrage",
        "rééquilibrage",
        "profil investisseur",
        "performance",
        "patrimoine",
    ],
    key_points=[
        "Une assurance-vie n'est pas un placement que l'on ouvre puis que l'on oublie définitivement.",
        "Un suivi annuel est généralement suffisant pour la plupart des épargnants.",
        "Les évolutions personnelles (mariage, naissance, retraite, succession, vente d'entreprise...) peuvent justifier une révision du contrat.",
        "Le suivi ne consiste pas à modifier son allocation après chaque variation des marchés.",
        "L'objectif est de vérifier que le contrat reste cohérent avec les objectifs patrimoniaux du souscripteur.",
    ],
    examples=[
        "Julie, 37 ans, réalise un point annuel avec son conseiller. Après la naissance de son deuxième enfant, elle augmente progressivement son effort d'épargne afin de préparer leurs études supérieures.",

        "Marc, 59 ans, approche de la retraite. Lors de son rendez-vous annuel, il adapte progressivement son allocation afin de réduire son exposition aux marchés financiers.",

        "Sophie, 46 ans, ne consulte son contrat qu'une fois par an. Elle évite ainsi de prendre des décisions émotionnelles lors des périodes de forte volatilité tout en s'assurant que sa stratégie reste adaptée.",
    ],
    vocabulary=[
        "suivi patrimonial",
        "allocation",
        "arbitrage",
        "rééquilibrage",
        "performance",
        "profil investisseur",
        "volatilité",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Suivre son assurance-vie revient à effectuer la révision annuelle de sa voiture : il n'est pas nécessaire d'aller au garage chaque semaine, mais un contrôle régulier permet d'éviter de nombreux problèmes.",
    ],
    misconceptions=[
        "Il faut consulter son contrat tous les jours.",
        "Une assurance-vie performante ne doit jamais être revue.",
        "Chaque baisse des marchés nécessite un arbitrage immédiat.",
    ],
    common_mistakes=[
        "Suivre son contrat quotidiennement.",
        "Ne jamais consulter son assurance-vie pendant plusieurs années.",
        "Prendre des décisions sous l'effet de la peur ou de l'euphorie.",
        "Oublier d'adapter le contrat après un changement de situation familiale ou professionnelle.",
    ],
    expert_tips=[
        "Pour la majorité des investisseurs, un rendez-vous patrimonial annuel est largement suffisant pour vérifier que le contrat reste cohérent avec les objectifs poursuivis.",
    ],
    attention_points=[
        "Les événements de vie justifient souvent davantage une révision du contrat que les fluctuations des marchés.",
        "Le suivi doit porter sur les objectifs patrimoniaux avant de porter sur les performances.",
        "La performance d'une seule année ne permet pas d'évaluer la qualité d'une stratégie d'investissement.",
    ],
    client_questions=[
        "À quelle fréquence dois-je consulter mon assurance-vie ?",
        "Dois-je modifier mon contrat lorsque les marchés baissent ?",
        "Quand faut-il revoir mon allocation ?",
        "Dois-je prendre rendez-vous chaque année ?",
    ],
    client_objections=[
        "Je n'ai pas le temps de suivre mes investissements.",
        "Je préfère ne plus regarder mon contrat.",
        "Les marchés me stressent.",
    ],
    client_fears=[
        "Prendre une mauvaise décision.",
        "Passer à côté d'une opportunité.",
        "Ne pas réagir suffisamment vite.",
    ],
    client_goals=[
        "Conserver une stratégie cohérente.",
        "Adapter son contrat aux évolutions de sa vie.",
        "Investir sereinement sur le long terme.",
    ],
    client_intents=[
        "suivre son assurance-vie",
        "faire un bilan patrimonial",
        "adapter son contrat",
        "vérifier ses investissements",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_gestion_reequilibrage",
        "assurance_vie_gestion_horizon_placement",
        "assurance_vie_gestion_erreurs",
        "assurance_vie_supports_arbitrage",
    ],
    prerequisites=[
        "assurance_vie_gestion_reequilibrage",
    ],
    next_topics=[
        "assurance_vie_gestion_erreurs",
    ],
),

Topic(
    id="assurance_vie_gestion_erreurs",
    title="Quelles erreurs éviter dans la gestion de son assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="gestion",
    description="Identifier les erreurs les plus fréquentes dans la gestion d'une assurance-vie afin de construire une stratégie patrimoniale durable et cohérente.",
    objective="Sensibiliser les épargnants aux mauvaises pratiques qui peuvent nuire à la performance, à la cohérence ou à la sérénité de leur investissement.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "erreurs assurance-vie",
        "gestion",
        "allocation",
        "arbitrage",
        "profil investisseur",
        "gestion libre",
        "gestion pilotée",
        "performance",
    ],
    key_points=[
        "Une assurance-vie doit être gérée selon une stratégie de long terme et non en fonction des émotions.",
        "Les décisions d'investissement doivent toujours être cohérentes avec les objectifs patrimoniaux.",
        "Les arbitrages trop fréquents peuvent nuire à la stratégie globale.",
        "Le contrat mérite un suivi régulier, sans surveillance quotidienne.",
        "Le mode de gestion choisi doit rester adapté au profil et aux connaissances de l'investisseur.",
    ],
    examples=[
        "Thomas, 39 ans, consulte son contrat plusieurs fois par jour. À chaque baisse des marchés, il modifie son allocation. En quelques années, il multiplie les arbitrages émotionnels et obtient une performance inférieure à celle de sa stratégie initiale.",

        "Isabelle, 57 ans, a choisi une gestion libre mais ne consulte plus son contrat pendant dix ans. À l'approche de la retraite, elle découvre que son allocation est restée très exposée aux marchés financiers malgré un horizon devenu beaucoup plus court.",

        "David, 46 ans, sélectionne une gestion pilotée mais change de profil tous les six mois en fonction des performances récentes. Il finit par poursuivre les performances passées au lieu de suivre une véritable stratégie patrimoniale.",
    ],
    vocabulary=[
        "allocation",
        "arbitrage",
        "profil investisseur",
        "gestion libre",
        "gestion pilotée",
        "rééquilibrage",
        "volatilité",
        "horizon de placement",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
    ],
    analogies=[
        "Gérer son assurance-vie uniquement selon les émotions revient à changer de destination à chaque panneau sur l'autoroute : on avance beaucoup, mais rarement dans la bonne direction.",
    ],
    misconceptions=[
        "Il faut modifier son contrat dès que les marchés baissent.",
        "Une bonne assurance-vie n'a jamais besoin d'être revue.",
        "Les meilleures performances de l'année passée seront forcément les meilleures demain.",
    ],
    common_mistakes=[
        "Suivre son contrat quotidiennement.",
        "Arbitrer sous l'effet des émotions.",
        "Choisir une gestion libre sans disposer du temps ou des connaissances nécessaires.",
        "Ne jamais revoir son profil investisseur.",
        "Poursuivre les performances passées plutôt que de respecter sa stratégie.",
        "Confondre investissement long terme et spéculation.",
    ],
    expert_tips=[
        "Les investisseurs les plus performants ne sont pas ceux qui prennent le plus de décisions, mais ceux qui appliquent une stratégie cohérente avec discipline sur le long terme.",
    ],
    attention_points=[
        "Les événements de vie justifient souvent davantage une révision du contrat que les mouvements de marché.",
        "Une allocation pertinente aujourd'hui peut devenir inadaptée quelques années plus tard.",
        "La performance doit toujours être analysée au regard du niveau de risque accepté.",
    ],
    client_questions=[
        "Quelles sont les erreurs les plus fréquentes ?",
        "Dois-je modifier mon contrat lorsque les marchés baissent ?",
        "Comment éviter les décisions émotionnelles ?",
        "Comment savoir si ma gestion est toujours adaptée ?",
    ],
    client_objections=[
        "J'ai peur de ne pas réagir assez vite.",
        "Je préfère attendre le bon moment pour investir.",
        "Je ne sais jamais quand modifier mon contrat.",
    ],
    client_fears=[
        "Perdre une partie de mon patrimoine.",
        "Faire les mauvais arbitrages.",
        "Prendre une décision irréversible.",
    ],
    client_goals=[
        "Investir avec sérénité.",
        "Construire une stratégie durable.",
        "Éviter les erreurs classiques des investisseurs.",
        "Conserver une allocation cohérente.",
    ],
    client_intents=[
        "éviter les erreurs",
        "mieux gérer son assurance-vie",
        "investir sereinement",
        "améliorer sa stratégie patrimoniale",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_gestion_libre",
        "assurance_vie_gestion_pilotee",
        "assurance_vie_gestion_sous_mandat",
        "assurance_vie_gestion_profil_investisseur",
        "assurance_vie_gestion_reequilibrage",
        "assurance_vie_gestion_horizon_placement",
        "assurance_vie_gestion_suivi_contrat",
    ],
    prerequisites=[
        "assurance_vie_gestion_profil_investisseur",
        "assurance_vie_gestion_reequilibrage",
    ],
    next_topics=[
        "assurance_vie_fiscalite_principe_general",
        "assurance_vie_fiscalite_rachats",
    ],
),


