from v2.models.knowledge_models import Topic

OUVERTURE_TOPICS = [

Topic(
    id="assurance_vie_ouverture_pourquoi_ouvrir",
    title="Pourquoi ouvrir une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="ouverture",
    description="Comprendre dans quels cas l'ouverture d'une assurance-vie peut répondre à un objectif patrimonial.",
    objective="Expliquer les principales raisons d'ouvrir une assurance-vie et montrer qu'elle constitue une enveloppe patrimoniale polyvalente, sans être adaptée à toutes les situations.",
    difficulty="Débutant",
    priority=10,
    version=1,
    keywords=[
        "ouvrir assurance-vie",
        "intérêt assurance-vie",
        "épargne",
        "investissement",
        "transmission",
        "fiscalité",
        "patrimoine",
        "préparer retraite",
        "diversification",
    ],
    key_points=[
        "L'assurance-vie est une enveloppe patrimoniale permettant d'épargner, d'investir et de transmettre un capital.",
        "Un même contrat peut répondre à plusieurs objectifs patrimoniaux au cours de la vie.",
        "Son intérêt dépend avant tout des objectifs du souscripteur.",
        "Ouvrir un contrat tôt permet de commencer à acquérir son ancienneté fiscale.",
        "L'assurance-vie complète les autres solutions d'épargne mais ne les remplace pas systématiquement.",
    ],
    examples=[
        "Un jeune actif ouvre une assurance-vie afin de constituer progressivement un patrimoine.",
        "Un couple ouvre un contrat pour préparer la transmission future d'une partie de son patrimoine.",
        "Un investisseur diversifie son épargne entre fonds euros et unités de compte grâce à son assurance-vie.",
    ],
    vocabulary=[
        "contrat",
        "souscripteur",
        "assuré",
        "bénéficiaire",
        "fonds euros",
        "unités de compte",
        "rachat",
        "clause bénéficiaire",
        "ancienneté fiscale",
    ],
    legal_sources=[
        "Code des assurances",
        "CGI art. 125-0 A",
    ],
    analogies=[
        "L'assurance-vie est comparable à une boîte à outils patrimoniale : c'est l'usage que l'on en fait qui lui donne sa valeur.",
    ],
    misconceptions=[
        "L'assurance-vie sert uniquement à transmettre un patrimoine.",
        "L'assurance-vie est réservée aux personnes âgées.",
        "Il faut être riche pour ouvrir une assurance-vie.",
    ],
    common_mistakes=[
        "Ouvrir un contrat sans objectif patrimonial clair.",
        "Choisir un contrat uniquement pour son avantage fiscal.",
        "Croire que l'assurance-vie est toujours la meilleure solution d'investissement.",
    ],
    expert_tips=[
        "Il est souvent préférable d'ouvrir un contrat suffisamment tôt afin de bénéficier de son ancienneté fiscale lorsque les besoins apparaîtront.",
    ],
    attention_points=[
        "Le choix du contrat est aussi important que la décision d'ouvrir une assurance-vie.",
        "Les frais, les supports d'investissement et la qualité de l'assureur doivent être étudiés avant toute souscription.",
    ],
    client_questions=[
        "Pourquoi ouvrir une assurance-vie ?",
        "À quoi sert une assurance-vie ?",
        "Est-ce utile si je suis jeune ?",
        "Est-ce intéressant même avec un petit patrimoine ?",
    ],
    client_objections=[
        "Je préfère garder mon argent sur mon Livret A.",
        "Je ne vois pas l'intérêt d'ouvrir un contrat maintenant.",
        "Je n'ai pas suffisamment d'argent.",
    ],
    client_fears=[
        "Bloquer mon argent.",
        "Faire un mauvais choix.",
        "Perdre mon capital.",
    ],
    client_goals=[
        "Constituer une épargne.",
        "Préparer la retraite.",
        "Financer un projet.",
        "Transmettre un patrimoine.",
        "Diversifier ses placements.",
    ],
    client_intents=[
        "épargner",
        "investir",
        "transmettre",
        "préparer un projet",
        "optimiser sa fiscalité",
    ],
    recommended_formats=[
        "instagram_reel",
        "linkedin_post",
        "article",
        "faq",
    ],
    related_topics=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_fondamentaux_fonctionnement",
        "assurance_vie_fondamentaux_huit_ans",
        "assurance_vie_ouverture_meilleur_moment",
        "assurance_vie_ouverture_sans_gros_capital",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
    ],
    next_topics=[
        "assurance_vie_ouverture_meilleur_moment",
        "assurance_vie_ouverture_sans_gros_capital",
        "assurance_vie_ouverture_conditions",
    ],
),

Topic(
    id="assurance_vie_ouverture_meilleur_moment",
    title="Quel est le meilleur moment pour ouvrir une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="ouverture",
    description="Comprendre pourquoi il est souvent préférable d'ouvrir une assurance-vie le plus tôt possible, même sans projet immédiat.",
    objective="Expliquer l'intérêt de l'ancienneté fiscale du contrat et montrer qu'il n'existe pas de 'moment parfait' pour ouvrir une assurance-vie.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "meilleur moment",
        "prendre date",
        "ancienneté fiscale",
        "8 ans",
        "ouvrir tôt",
        "assurance-vie",
        "horizon de placement",
        "épargne long terme",
    ],
    key_points=[
        "L'ancienneté fiscale d'une assurance-vie commence à courir dès l'ouverture du contrat.",
        "Il n'est pas nécessaire d'attendre d'avoir un patrimoine important pour ouvrir une assurance-vie.",
        "Un contrat peut être ouvert avec un versement initial limité selon les conditions de l'assureur.",
        "Ouvrir tôt offre davantage de flexibilité pour les projets futurs.",
        "Le meilleur moment dépend des objectifs patrimoniaux du souscripteur, mais il est rarement avantageux d'attendre sans raison.",
    ],
    examples=[
        "Julie ouvre une assurance-vie à 30 ans avec 500 € afin de commencer à acquérir de l'ancienneté fiscale.",
        "Marc attend la veille de son départ à la retraite pour ouvrir son contrat et ne bénéficie pas immédiatement de tous les avantages liés à son ancienneté.",
        "Élodie ouvre un contrat dès son premier emploi et l'alimente progressivement au fil des années.",
    ],
    vocabulary=[
        "ancienneté fiscale",
        "prendre date",
        "versement initial",
        "rachat",
        "horizon d'investissement",
        "plus-value",
        "souscripteur",
    ],
    legal_sources=[
        "CGI art. 125-0 A",
    ],
    analogies=[
        "Ouvrir une assurance-vie revient à lancer un chronomètre : plus il démarre tôt, plus il pourra être utile lorsque vous en aurez besoin.",
    ],
    misconceptions=[
        "Il faut attendre d'avoir beaucoup d'argent avant d'ouvrir une assurance-vie.",
        "Une assurance-vie n'est utile qu'à partir de 50 ans.",
        "Le montant investi influence l'ancienneté fiscale du contrat.",
    ],
    common_mistakes=[
        "Reporter l'ouverture du contrat sans raison particulière.",
        "Croire qu'il faut investir une somme importante dès le départ.",
        "Attendre un projet avant de prendre date fiscalement.",
    ],
    expert_tips=[
        "Lorsqu'une assurance-vie fait partie des solutions envisagées, ouvrir le contrat tôt est souvent plus important que le montant du premier versement.",
    ],
    attention_points=[
        "Prendre date ne dispense pas de choisir un contrat de qualité.",
        "L'ancienneté fiscale ne doit jamais être le seul critère de choix d'une assurance-vie.",
    ],
    client_questions=[
        "Quel est le meilleur âge pour ouvrir une assurance-vie ?",
        "Est-ce trop tôt pour moi ?",
        "Pourquoi dit-on qu'il faut prendre date ?",
        "Puis-je ouvrir un contrat même si je n'ai pas encore de projet ?",
    ],
    client_objections=[
        "Je suis encore trop jeune.",
        "Je préfère attendre d'avoir plus d'argent.",
        "Je n'ai pas encore de projet précis.",
    ],
    client_fears=[
        "Ouvrir un contrat qui ne me servira pas.",
        "Faire un mauvais choix trop tôt.",
        "Être bloqué par un contrat ouvert trop jeune.",
    ],
    client_goals=[
        "Préparer l'avenir.",
        "Acquérir de l'ancienneté fiscale.",
        "Construire progressivement une épargne.",
        "Gagner en souplesse patrimoniale.",
    ],
    client_intents=[
        "ouvrir une assurance-vie",
        "prendre date",
        "préparer un projet",
        "anticiper",
    ],
    recommended_formats=[
        "instagram_reel",
        "linkedin_post",
        "article",
        "faq",
    ],
    related_topics=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_ouverture_pourquoi_ouvrir",
        "assurance_vie_ouverture_sans_gros_capital",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
    ],
    next_topics=[
        "assurance_vie_ouverture_sans_gros_capital",
        "assurance_vie_ouverture_conditions",
    ],
),

Topic(
    id="assurance_vie_ouverture_sans_gros_capital",
    title="Faut-il beaucoup d'argent pour ouvrir une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="ouverture",
    description="Comprendre qu'une assurance-vie est accessible sans disposer d'un patrimoine important et qu'il est possible de commencer avec un investissement modeste.",
    objective="Déconstruire l'idée selon laquelle l'assurance-vie serait réservée aux personnes fortunées et expliquer qu'une stratégie d'épargne progressive est souvent pertinente.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "petit capital",
        "versement initial",
        "épargne progressive",
        "accessibilité",
        "ouvrir assurance-vie",
        "versements programmés",
        "petit budget",
        "débuter",
    ],
    key_points=[
        "L'assurance-vie est accessible avec des montants variables selon les contrats.",
        "Il n'est pas nécessaire d'investir une somme importante dès l'ouverture.",
        "Les versements programmés permettent de constituer progressivement un capital.",
        "L'important est la régularité de l'épargne davantage que le montant du premier versement.",
        "Le contrat doit être adapté à la capacité d'épargne et aux objectifs patrimoniaux du souscripteur.",
    ],
    examples=[
        "Lucas ouvre une assurance-vie avec un premier versement de 300 € puis met en place des versements mensuels de 50 €.",
        "Sarah préfère commencer avec une somme modeste afin de découvrir le fonctionnement de son contrat avant d'investir davantage.",
        "Un jeune actif construit progressivement son patrimoine grâce à des versements réguliers pendant plusieurs années.",
    ],
    vocabulary=[
        "versement initial",
        "versements programmés",
        "versements libres",
        "capacité d'épargne",
        "effort d'épargne",
        "capital",
        "souscripteur",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Construire une assurance-vie ressemble à remplir progressivement une tirelire : ce sont la régularité et le temps qui produisent le résultat, pas uniquement le premier dépôt.",
    ],
    misconceptions=[
        "Il faut être riche pour ouvrir une assurance-vie.",
        "Un petit contrat ne sert à rien.",
        "Il faut investir une grosse somme dès le départ.",
    ],
    common_mistakes=[
        "Attendre plusieurs années avant d'ouvrir un contrat dans l'espoir d'investir davantage.",
        "Penser que le montant du premier versement détermine l'intérêt futur du contrat.",
        "Choisir un contrat uniquement parce qu'il accepte un faible versement minimum.",
    ],
    expert_tips=[
        "Il est souvent préférable d'ouvrir un contrat adapté puis de l'alimenter progressivement plutôt que d'attendre de disposer d'un capital important.",
    ],
    attention_points=[
        "Les montants minimums de souscription varient selon les assureurs et les distributeurs.",
        "Le niveau des frais reste un critère plus important que le montant minimum d'ouverture.",
    ],
    client_questions=[
        "Puis-je ouvrir une assurance-vie avec seulement quelques centaines d'euros ?",
        "Quel est le montant minimum pour ouvrir un contrat ?",
        "Puis-je verser un peu chaque mois ?",
        "Est-ce intéressant si je n'ai pas un gros patrimoine ?",
    ],
    client_objections=[
        "Je n'ai pas suffisamment d'épargne.",
        "Je préfère attendre d'avoir un capital plus important.",
        "L'assurance-vie est faite pour les personnes aisées.",
    ],
    client_fears=[
        "Ne pas investir suffisamment pour que le contrat soit utile.",
        "Être obligé de verser régulièrement des montants élevés.",
        "Souscrire un contrat inadapté à mon budget.",
    ],
    client_goals=[
        "Commencer à épargner.",
        "Construire progressivement un patrimoine.",
        "Prendre date fiscalement.",
        "Mettre en place une épargne régulière.",
    ],
    client_intents=[
        "commencer à investir",
        "épargner progressivement",
        "ouvrir une assurance-vie",
        "préparer l'avenir",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "linkedin_post",
        "article",
    ],
    related_topics=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_ouverture_pourquoi_ouvrir",
        "assurance_vie_ouverture_meilleur_moment",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
    ],
    next_topics=[
        "assurance_vie_ouverture_conditions",
        "assurance_vie_ouverture_comment_ouvrir",
    ],
),

Topic(
    id="assurance_vie_ouverture_conditions",
    title="Qui peut ouvrir une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="ouverture",
    description="Comprendre les conditions générales permettant d'ouvrir un contrat d'assurance-vie ainsi que les principales situations particulières.",
    objective="Expliquer que la souscription d'une assurance-vie dépend principalement de la capacité juridique du souscripteur et des conditions fixées par l'assureur.",
    difficulty="Débutant",
    priority=8,
    version=1,
    keywords=[
        "qui peut ouvrir",
        "souscripteur",
        "capacité juridique",
        "majeur",
        "mineur",
        "majeur protégé",
        "non-résident",
        "conditions d'ouverture",
    ],
    key_points=[
        "Toute personne juridiquement capable peut, en principe, ouvrir une assurance-vie.",
        "Les mineurs peuvent également être titulaires d'un contrat sous certaines conditions.",
        "Les majeurs protégés sont soumis à des règles particulières selon leur régime de protection.",
        "Les non-résidents peuvent parfois souscrire un contrat, sous réserve des conditions de l'assureur et de la réglementation applicable.",
        "Chaque assureur conserve une liberté dans sa politique d'acceptation des souscriptions.",
    ],
    examples=[
        "Paul, 32 ans, ouvre une assurance-vie pour commencer à investir à long terme.",
        "Des parents ouvrent une assurance-vie au nom de leur enfant mineur afin de constituer progressivement une épargne.",
        "Un expatrié vérifie auprès de l'assureur si sa résidence fiscale permet la souscription d'un contrat français.",
    ],
    vocabulary=[
        "souscripteur",
        "assuré",
        "bénéficiaire",
        "capacité juridique",
        "majeur protégé",
        "résidence fiscale",
        "souscription",
    ],
    legal_sources=[
        "Code civil",
        "Code des assurances",
    ],
    analogies=[
        "Souscrire une assurance-vie revient à signer un contrat : il faut donc avoir la capacité juridique nécessaire pour s'engager.",
    ],
    misconceptions=[
        "Seuls les adultes peuvent détenir une assurance-vie.",
        "Tous les non-résidents peuvent ouvrir n'importe quel contrat français.",
        "Les assureurs sont obligés d'accepter toute demande de souscription.",
    ],
    common_mistakes=[
        "Confondre souscripteur, assuré et bénéficiaire.",
        "Penser que la résidence fiscale est sans conséquence.",
        "Ignorer les règles spécifiques applicables aux mineurs ou aux majeurs protégés.",
    ],
    expert_tips=[
        "Avant toute ouverture, il est utile de vérifier que la situation civile, fiscale et réglementaire du client est compatible avec les conditions du contrat.",
    ],
    attention_points=[
        "Les modalités d'ouverture peuvent varier selon les assureurs.",
        "La résidence fiscale et la conformité réglementaire doivent être vérifiées avant toute souscription.",
    ],
    client_questions=[
        "Qui peut ouvrir une assurance-vie ?",
        "Puis-je ouvrir un contrat à mon nom ?",
        "Existe-t-il un âge minimum ?",
        "Ma situation personnelle peut-elle empêcher l'ouverture d'un contrat ?",
    ],
    client_objections=[
        "Je ne suis pas certain d'avoir le droit d'ouvrir une assurance-vie.",
        "Ma situation est particulière.",
    ],
    client_fears=[
        "Voir ma demande refusée.",
        "Souscrire un contrat qui ne serait pas valable.",
        "Ne pas respecter les règles applicables à ma situation.",
    ],
    client_goals=[
        "Vérifier son éligibilité.",
        "Comprendre les conditions d'ouverture.",
        "Sécuriser sa souscription.",
    ],
    client_intents=[
        "ouvrir une assurance-vie",
        "vérifier les conditions",
        "préparer une souscription",
        "comprendre les règles",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "article",
        "linkedin_post",
    ],
    related_topics=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_ouverture_pourquoi_ouvrir",
        "assurance_vie_ouverture_comment_ouvrir",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
    ],
    next_topics=[
        "assurance_vie_ouverture_mineur",
        "assurance_vie_ouverture_non_resident",
        "assurance_vie_ouverture_comment_ouvrir",
    ],
),

Topic(
    id="assurance_vie_ouverture_sans_gros_capital",
    title="Faut-il beaucoup d'argent pour ouvrir une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="ouverture",
    description="Comprendre qu'une assurance-vie est accessible sans disposer d'un patrimoine important et qu'il est possible de commencer avec un investissement modeste.",
    objective="Déconstruire l'idée selon laquelle l'assurance-vie serait réservée aux personnes fortunées et expliquer qu'une stratégie d'épargne progressive est souvent pertinente.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "petit capital",
        "versement initial",
        "épargne progressive",
        "accessibilité",
        "ouvrir assurance-vie",
        "versements programmés",
        "petit budget",
        "débuter",
    ],
    key_points=[
        "L'assurance-vie est accessible avec des montants variables selon les contrats.",
        "Il n'est pas nécessaire d'investir une somme importante dès l'ouverture.",
        "Les versements programmés permettent de constituer progressivement un capital.",
        "L'important est la régularité de l'épargne davantage que le montant du premier versement.",
        "Le contrat doit être adapté à la capacité d'épargne et aux objectifs patrimoniaux du souscripteur.",
    ],
    examples=[
        "Lucas ouvre une assurance-vie avec un premier versement de 300 € puis met en place des versements mensuels de 50 €.",
        "Sarah préfère commencer avec une somme modeste afin de découvrir le fonctionnement de son contrat avant d'investir davantage.",
        "Un jeune actif construit progressivement son patrimoine grâce à des versements réguliers pendant plusieurs années.",
    ],
    vocabulary=[
        "versement initial",
        "versements programmés",
        "versements libres",
        "capacité d'épargne",
        "effort d'épargne",
        "capital",
        "souscripteur",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Construire une assurance-vie ressemble à remplir progressivement une tirelire : ce sont la régularité et le temps qui produisent le résultat, pas uniquement le premier dépôt.",
    ],
    misconceptions=[
        "Il faut être riche pour ouvrir une assurance-vie.",
        "Un petit contrat ne sert à rien.",
        "Il faut investir une grosse somme dès le départ.",
    ],
    common_mistakes=[
        "Attendre plusieurs années avant d'ouvrir un contrat dans l'espoir d'investir davantage.",
        "Penser que le montant du premier versement détermine l'intérêt futur du contrat.",
        "Choisir un contrat uniquement parce qu'il accepte un faible versement minimum.",
    ],
    expert_tips=[
        "Il est souvent préférable d'ouvrir un contrat adapté puis de l'alimenter progressivement plutôt que d'attendre de disposer d'un capital important.",
    ],
    attention_points=[
        "Les montants minimums de souscription varient selon les assureurs et les distributeurs.",
        "Le niveau des frais reste un critère plus important que le montant minimum d'ouverture.",
    ],
    client_questions=[
        "Puis-je ouvrir une assurance-vie avec seulement quelques centaines d'euros ?",
        "Quel est le montant minimum pour ouvrir un contrat ?",
        "Puis-je verser un peu chaque mois ?",
        "Est-ce intéressant si je n'ai pas un gros patrimoine ?",
    ],
    client_objections=[
        "Je n'ai pas suffisamment d'épargne.",
        "Je préfère attendre d'avoir un capital plus important.",
        "L'assurance-vie est faite pour les personnes aisées.",
    ],
    client_fears=[
        "Ne pas investir suffisamment pour que le contrat soit utile.",
        "Être obligé de verser régulièrement des montants élevés.",
        "Souscrire un contrat inadapté à mon budget.",
    ],
    client_goals=[
        "Commencer à épargner.",
        "Construire progressivement un patrimoine.",
        "Prendre date fiscalement.",
        "Mettre en place une épargne régulière.",
    ],
    client_intents=[
        "commencer à investir",
        "épargner progressivement",
        "ouvrir une assurance-vie",
        "préparer l'avenir",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "linkedin_post",
        "article",
    ],
    related_topics=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_ouverture_pourquoi_ouvrir",
        "assurance_vie_ouverture_meilleur_moment",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
    ],
    next_topics=[
        "assurance_vie_ouverture_conditions",
        "assurance_vie_ouverture_comment_ouvrir",
    ],
),

Topic(
    id="assurance_vie_ouverture_non_resident",
    title="Un non-résident peut-il ouvrir une assurance-vie française ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="ouverture",
    description="Comprendre dans quelles conditions une personne non-résidente peut ouvrir ou conserver une assurance-vie française.",
    objective="Expliquer que la résidence fiscale n'interdit pas systématiquement la souscription d'une assurance-vie, mais qu'elle peut avoir des conséquences juridiques, fiscales et opérationnelles selon le pays de résidence et la politique de l'assureur.",
    difficulty="Intermédiaire",
    priority=7,
    version=1,
    keywords=[
        "non-résident",
        "expatrié",
        "résidence fiscale",
        "assurance-vie française",
        "souscription",
        "contrat",
        "fiscalité internationale",
        "expatriation",
    ],
    key_points=[
        "Un non-résident peut, dans certains cas, ouvrir ou conserver une assurance-vie française.",
        "Chaque assureur fixe sa propre politique de commercialisation selon les pays de résidence.",
        "La résidence fiscale du souscripteur influence la fiscalité applicable aux rachats.",
        "Les règles internationales et les conventions fiscales peuvent modifier le traitement du contrat.",
        "Avant toute souscription, il est indispensable de vérifier les conditions de l'assureur et les conséquences fiscales dans le pays de résidence.",
    ],
    examples=[
        "Un Français expatrié au Portugal souhaite ouvrir une assurance-vie française : l'assureur vérifie d'abord s'il commercialise ses contrats dans ce pays.",
        "Une personne installée à Singapour conserve son assurance-vie ouverte avant son départ mais voit la fiscalité évoluer selon sa résidence fiscale.",
        "Un expatrié compare les solutions disponibles dans son pays de résidence avant d'investir.",
    ],
    vocabulary=[
        "non-résident",
        "résidence fiscale",
        "expatriation",
        "convention fiscale",
        "rachat",
        "souscripteur",
        "conformité",
    ],
    legal_sources=[
        "Code général des impôts",
        "Code des assurances",
        "Conventions fiscales internationales",
    ],
    analogies=[
        "Une assurance-vie fonctionne comme un abonnement : le contrat peut exister, mais les règles changent lorsque l'on change de pays.",
    ],
    misconceptions=[
        "Un non-résident ne peut jamais ouvrir une assurance-vie française.",
        "La fiscalité française s'applique toujours de la même manière après une expatriation.",
        "Tous les assureurs acceptent les souscriptions des expatriés.",
    ],
    common_mistakes=[
        "Confondre nationalité et résidence fiscale.",
        "Oublier de vérifier si l'assureur accepte les résidents du pays concerné.",
        "Négliger les conséquences fiscales dans le pays de résidence.",
    ],
    expert_tips=[
        "La première question n'est pas 'Puis-je ouvrir une assurance-vie ?', mais 'Cet assureur accepte-t-il les résidents de mon pays et quel sera le régime fiscal applicable ?'.",
    ],
    attention_points=[
        "Les règles diffèrent selon les assureurs et les pays de résidence.",
        "Une analyse fiscale internationale peut être nécessaire avant toute souscription ou avant un rachat.",
    ],
    client_questions=[
        "Puis-je ouvrir une assurance-vie si je vis à l'étranger ?",
        "Que devient mon contrat si je m'expatrie ?",
        "La fiscalité française continue-t-elle de s'appliquer ?",
        "Tous les assureurs acceptent-ils les expatriés ?",
    ],
    client_objections=[
        "Je pense que mon expatriation m'empêche d'ouvrir un contrat.",
        "J'ai peur que mon contrat devienne inutilisable après mon départ.",
    ],
    client_fears=[
        "Perdre les avantages de mon assurance-vie.",
        "Être imposé deux fois.",
        "Choisir un contrat incompatible avec ma résidence fiscale.",
    ],
    client_goals=[
        "Préserver son patrimoine pendant une expatriation.",
        "Investir malgré une résidence à l'étranger.",
        "Comprendre les conséquences fiscales internationales.",
    ],
    client_intents=[
        "ouvrir une assurance-vie",
        "expatriation",
        "résidence fiscale",
        "investir depuis l'étranger",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "article",
        "linkedin_post",
    ],
    related_topics=[
        "assurance_vie_ouverture_conditions",
        "assurance_vie_ouverture_comment_ouvrir",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_ouverture_conditions",
    ],
    next_topics=[
        "assurance_vie_ouverture_comment_ouvrir",
    ],
),

Topic(
    id="assurance_vie_ouverture_comment_ouvrir",
    title="Comment ouvrir une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="ouverture",
    description="Comprendre les différentes étapes de la souscription d'une assurance-vie et les choix à effectuer avant l'ouverture du contrat.",
    objective="Expliquer le parcours de souscription d'une assurance-vie afin que le lecteur comprenne les démarches, les documents nécessaires et les principaux choix à effectuer.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "ouvrir une assurance-vie",
        "souscription",
        "ouvrir un contrat",
        "démarches",
        "documents",
        "versement initial",
        "profil investisseur",
        "KYC",
    ],
    key_points=[
        "L'ouverture d'une assurance-vie commence par le choix d'un contrat adapté à ses objectifs patrimoniaux.",
        "Le souscripteur doit compléter un dossier comprenant notamment des informations personnelles, patrimoniales et financières.",
        "L'assureur est tenu de recueillir des informations sur les objectifs d'investissement et le profil de risque du client.",
        "Un premier versement est généralement réalisé lors de la souscription, selon les conditions du contrat.",
        "Une fois le dossier accepté par l'assureur, le contrat est ouvert et peut être alimenté par des versements complémentaires.",
    ],
    examples=[
        "Julie compare plusieurs contrats avant de choisir celui dont les frais sont les plus compétitifs.",
        "Paul remplit son questionnaire investisseur puis réalise un premier versement de 1 000 € lors de l'ouverture de son contrat.",
        "Élodie ouvre son assurance-vie entièrement en ligne en moins d'une heure après avoir transmis ses justificatifs.",
    ],
    vocabulary=[
        "souscription",
        "questionnaire investisseur",
        "profil de risque",
        "KYC",
        "versement initial",
        "bulletin de souscription",
        "pièce d'identité",
        "justificatif de domicile",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
        "Réglementation LCB-FT",
    ],
    analogies=[
        "Ouvrir une assurance-vie ressemble à l'ouverture d'un compte bancaire : avant d'investir, l'établissement doit vérifier votre identité et comprendre votre situation.",
    ],
    misconceptions=[
        "L'ouverture d'une assurance-vie est longue et compliquée.",
        "Il suffit de verser de l'argent pour ouvrir un contrat.",
        "Toutes les assurances-vie se ressemblent.",
    ],
    common_mistakes=[
        "Choisir un contrat sans comparer les frais.",
        "Remplir rapidement le questionnaire investisseur sans réfléchir à son horizon de placement.",
        "Signer un contrat sans lire les caractéristiques des supports proposés.",
    ],
    expert_tips=[
        "Le temps consacré à choisir le bon contrat est souvent plus rentable que la recherche d'un rendement légèrement supérieur.",
    ],
    attention_points=[
        "Les frais peuvent fortement varier d'un contrat à l'autre.",
        "Le questionnaire investisseur est une obligation réglementaire et conditionne les recommandations du distributeur.",
        "Le choix des supports d'investissement mérite une réflexion distincte de l'ouverture du contrat.",
    ],
    client_questions=[
        "Comment ouvrir une assurance-vie ?",
        "Quels documents faut-il fournir ?",
        "Combien de temps faut-il pour ouvrir un contrat ?",
        "Puis-je tout faire en ligne ?",
    ],
    client_objections=[
        "Les démarches me semblent compliquées.",
        "Je n'ai pas envie de remplir beaucoup de documents.",
        "Je préfère attendre d'être conseillé avant d'ouvrir un contrat.",
    ],
    client_fears=[
        "Faire une erreur lors de la souscription.",
        "Choisir un mauvais contrat.",
        "Signer un document que je ne comprends pas.",
    ],
    client_goals=[
        "Ouvrir un contrat simplement.",
        "Choisir une assurance-vie adaptée.",
        "Commencer à investir sereinement.",
    ],
    client_intents=[
        "ouvrir une assurance-vie",
        "comparer les contrats",
        "commencer à investir",
        "préparer son épargne",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_ouverture_pourquoi_ouvrir",
        "assurance_vie_ouverture_conditions",
        "assurance_vie_ouverture_premier_versement",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_ouverture_conditions",
    ],
    next_topics=[
        "assurance_vie_ouverture_choisir_contrat",
        "assurance_vie_ouverture_premier_versement",
        "assurance_vie_ouverture_erreurs",
    ],
),

Topic(
    id="assurance_vie_ouverture_comment_ouvrir",
    title="Comment ouvrir une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="ouverture",
    description="Comprendre les différentes étapes de la souscription d'une assurance-vie et les choix à effectuer avant l'ouverture du contrat.",
    objective="Expliquer le parcours de souscription d'une assurance-vie afin que le lecteur comprenne les démarches, les documents nécessaires et les principaux choix à effectuer.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "ouvrir une assurance-vie",
        "souscription",
        "ouvrir un contrat",
        "démarches",
        "documents",
        "versement initial",
        "profil investisseur",
        "KYC",
    ],
    key_points=[
        "L'ouverture d'une assurance-vie commence par le choix d'un contrat adapté à ses objectifs patrimoniaux.",
        "Le souscripteur doit compléter un dossier comprenant notamment des informations personnelles, patrimoniales et financières.",
        "L'assureur est tenu de recueillir des informations sur les objectifs d'investissement et le profil de risque du client.",
        "Un premier versement est généralement réalisé lors de la souscription, selon les conditions du contrat.",
        "Une fois le dossier accepté par l'assureur, le contrat est ouvert et peut être alimenté par des versements complémentaires.",
    ],
    examples=[
        "Julie compare plusieurs contrats avant de choisir celui dont les frais sont les plus compétitifs.",
        "Paul remplit son questionnaire investisseur puis réalise un premier versement de 1 000 € lors de l'ouverture de son contrat.",
        "Élodie ouvre son assurance-vie entièrement en ligne en moins d'une heure après avoir transmis ses justificatifs.",
    ],
    vocabulary=[
        "souscription",
        "questionnaire investisseur",
        "profil de risque",
        "KYC",
        "versement initial",
        "bulletin de souscription",
        "pièce d'identité",
        "justificatif de domicile",
    ],
    legal_sources=[
        "Code des assurances",
        "Code monétaire et financier",
        "Réglementation LCB-FT",
    ],
    analogies=[
        "Ouvrir une assurance-vie ressemble à l'ouverture d'un compte bancaire : avant d'investir, l'établissement doit vérifier votre identité et comprendre votre situation.",
    ],
    misconceptions=[
        "L'ouverture d'une assurance-vie est longue et compliquée.",
        "Il suffit de verser de l'argent pour ouvrir un contrat.",
        "Toutes les assurances-vie se ressemblent.",
    ],
    common_mistakes=[
        "Choisir un contrat sans comparer les frais.",
        "Remplir rapidement le questionnaire investisseur sans réfléchir à son horizon de placement.",
        "Signer un contrat sans lire les caractéristiques des supports proposés.",
    ],
    expert_tips=[
        "Le temps consacré à choisir le bon contrat est souvent plus rentable que la recherche d'un rendement légèrement supérieur.",
    ],
    attention_points=[
        "Les frais peuvent fortement varier d'un contrat à l'autre.",
        "Le questionnaire investisseur est une obligation réglementaire et conditionne les recommandations du distributeur.",
        "Le choix des supports d'investissement mérite une réflexion distincte de l'ouverture du contrat.",
    ],
    client_questions=[
        "Comment ouvrir une assurance-vie ?",
        "Quels documents faut-il fournir ?",
        "Combien de temps faut-il pour ouvrir un contrat ?",
        "Puis-je tout faire en ligne ?",
    ],
    client_objections=[
        "Les démarches me semblent compliquées.",
        "Je n'ai pas envie de remplir beaucoup de documents.",
        "Je préfère attendre d'être conseillé avant d'ouvrir un contrat.",
    ],
    client_fears=[
        "Faire une erreur lors de la souscription.",
        "Choisir un mauvais contrat.",
        "Signer un document que je ne comprends pas.",
    ],
    client_goals=[
        "Ouvrir un contrat simplement.",
        "Choisir une assurance-vie adaptée.",
        "Commencer à investir sereinement.",
    ],
    client_intents=[
        "ouvrir une assurance-vie",
        "comparer les contrats",
        "commencer à investir",
        "préparer son épargne",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_ouverture_pourquoi_ouvrir",
        "assurance_vie_ouverture_conditions",
        "assurance_vie_ouverture_premier_versement",
    ],
    prerequisites=[
        "assurance_vie_fondamentaux_definition",
        "assurance_vie_ouverture_conditions",
    ],
    next_topics=[
        "assurance_vie_ouverture_choisir_contrat",
        "assurance_vie_ouverture_premier_versement",
        "assurance_vie_ouverture_erreurs",
    ],
),

Topic(
    id="assurance_vie_ouverture_premier_versement",
    title="Quel montant verser à l'ouverture d'une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="ouverture",
    description="Comprendre comment déterminer le montant du premier versement lors de l'ouverture d'une assurance-vie.",
    objective="Expliquer que le premier versement doit être cohérent avec les objectifs patrimoniaux, la capacité d'épargne et le contrat choisi.",
    difficulty="Débutant",
    priority=8,
    version=1,
    keywords=[
        "premier versement",
        "versement initial",
        "montant ouverture",
        "épargne",
        "investissement",
        "assurance-vie",
        "capacité d'épargne",
    ],
    key_points=[
        "Le montant minimum dépend des conditions prévues par le contrat.",
        "Il n'est pas nécessaire d'investir une somme importante dès l'ouverture.",
        "Le premier versement doit rester compatible avec la situation financière du souscripteur.",
        "Une stratégie de versements programmés peut être plus pertinente qu'un versement unique important.",
        "Le plus important reste la régularité de l'épargne sur le long terme.",
    ],
    examples=[
        "Paul ouvre son contrat avec 500 € puis met en place un versement mensuel de 100 €.",
        "Claire préfère investir progressivement plutôt que d'immobiliser une somme importante dès le départ.",
    ],
    vocabulary=[
        "versement initial",
        "versements programmés",
        "versements libres",
        "effort d'épargne",
        "capital",
        "allocation",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Le premier versement est comparable au premier pas d'un marathon : il est plus important de commencer que de partir trop vite.",
    ],
    misconceptions=[
        "Il faut investir beaucoup dès l'ouverture.",
        "Un petit premier versement ne sert à rien.",
    ],
    common_mistakes=[
        "Immobiliser une épargne de précaution dans son assurance-vie.",
        "Verser un montant inadapté à sa capacité financière.",
        "Négliger les versements réguliers.",
    ],
    expert_tips=[
        "Un premier versement raisonnable complété par une épargne régulière constitue souvent une stratégie plus efficace qu'un investissement important ponctuel.",
    ],
    attention_points=[
        "Le montant minimum varie selon les contrats.",
        "L'épargne de précaution doit rester disponible en dehors de l'assurance-vie.",
    ],
    client_questions=[
        "Combien dois-je verser à l'ouverture ?",
        "Existe-t-il un minimum ?",
        "Puis-je commencer avec un petit montant ?",
    ],
    client_objections=[
        "Je n'ai pas beaucoup d'argent à investir.",
        "Je préfère attendre d'avoir une somme plus importante.",
    ],
    client_fears=[
        "Investir trop d'argent.",
        "Ne pas investir suffisamment.",
    ],
    client_goals=[
        "Commencer à investir.",
        "Construire progressivement un patrimoine.",
        "Mettre en place une épargne régulière.",
    ],
    client_intents=[
        "ouvrir une assurance-vie",
        "faire un premier versement",
        "épargner progressivement",
    ],
    recommended_formats=[
        "instagram_reel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_ouverture_sans_gros_capital",
        "assurance_vie_ouverture_comment_ouvrir",
        "assurance_vie_ouverture_choisir_contrat",
    ],
    prerequisites=[
        "assurance_vie_ouverture_comment_ouvrir",
    ],
    next_topics=[
        "assurance_vie_ouverture_erreurs",
    ],
),

Topic(
    id="assurance_vie_ouverture_erreurs",
    title="Quelles erreurs éviter lors de l'ouverture d'une assurance-vie ?",
    pillar="epargner",
    family="assurance_vie",
    chapter="ouverture",
    description="Identifier les principales erreurs commises lors de la souscription d'une assurance-vie afin de faire un choix durable.",
    objective="Aider le lecteur à éviter les erreurs les plus fréquentes lors de l'ouverture d'un contrat.",
    difficulty="Débutant",
    priority=9,
    version=1,
    keywords=[
        "erreurs assurance-vie",
        "mauvais contrat",
        "frais",
        "versement",
        "supports",
        "ouverture",
        "conseils",
    ],
    key_points=[
        "Choisir un contrat uniquement parce qu'il est proposé par sa banque est rarement une bonne méthode.",
        "Les frais doivent être analysés avant toute souscription.",
        "L'assurance-vie doit répondre à un objectif patrimonial clairement identifié.",
        "Le choix des supports d'investissement est aussi important que le choix du contrat.",
        "Une assurance-vie peut évoluer dans le temps grâce aux arbitrages et aux nouveaux versements.",
    ],
    examples=[
        "Un épargnant choisit le contrat de sa banque sans comparer les frais avec ceux d'autres contrats.",
        "Une cliente investit tout son capital sur un seul support sans diversification.",
    ],
    vocabulary=[
        "frais",
        "arbitrage",
        "allocation",
        "diversification",
        "gestion libre",
        "gestion pilotée",
    ],
    legal_sources=[
        "Code des assurances",
    ],
    analogies=[
        "Choisir une assurance-vie sans comparer les contrats revient à acheter une voiture sans regarder son prix ni ses équipements.",
    ],
    misconceptions=[
        "Toutes les assurances-vie sont identiques.",
        "Le meilleur contrat est forcément celui de ma banque.",
        "Une fois le contrat ouvert, je ne peux plus rien modifier.",
    ],
    common_mistakes=[
        "Ne pas comparer les frais.",
        "Choisir un contrat uniquement pour sa performance passée.",
        "Oublier de définir son objectif patrimonial.",
        "Ignorer la qualité des supports d'investissement.",
    ],
    expert_tips=[
        "Un bon contrat peut accompagner un épargnant pendant plusieurs décennies : il mérite d'être choisi avec soin.",
    ],
    attention_points=[
        "Les performances passées ne garantissent jamais les performances futures.",
        "La qualité du contrat influence durablement les résultats obtenus.",
    ],
    client_questions=[
        "Quelles sont les erreurs les plus fréquentes ?",
        "Comment éviter de choisir un mauvais contrat ?",
        "Quels critères faut-il vérifier ?",
    ],
    client_objections=[
        "Tous les contrats se ressemblent.",
        "Je fais confiance à ma banque sans comparer.",
    ],
    client_fears=[
        "Choisir un mauvais contrat.",
        "Payer trop de frais.",
        "Faire un mauvais investissement.",
    ],
    client_goals=[
        "Faire un choix éclairé.",
        "Éviter les erreurs classiques.",
        "Construire un patrimoine durable.",
    ],
    client_intents=[
        "éviter les erreurs",
        "ouvrir une assurance-vie",
        "choisir un contrat",
    ],
    recommended_formats=[
        "instagram_reel",
        "carrousel",
        "faq",
        "article",
    ],
    related_topics=[
        "assurance_vie_ouverture_comment_ouvrir",
        "assurance_vie_ouverture_choisir_contrat",
        "assurance_vie_ouverture_premier_versement",
    ],
    prerequisites=[
        "assurance_vie_ouverture_choisir_contrat",
    ],
    next_topics=[
        "assurance_vie_versements_libres",
    ],
),

]